Serval App MVP
sillsdev/serval pull request #192
Opened 2023-10-23 16:11 UTC by Enkidu93

Fixes #132. 

Once this is merged, I can deploy it. 

I can also pretty up code down the line if you' prefer, but it's all pretty straightforward.

2023-10-23 16:28 UTC, johnml1135 commented
*[`samples/ServalApp/README.md` line 11 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSMO6k1TDAJwfTfgb4:-NhSMO6k1TDAJwfTfgb5:b3lkgy4) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/README.md#L11)):*
> ```Markdown
> When the Serval API is updated, use the tool [swagger-to](https://pypi.org/project/swagger-to/) to generate a new `serval_client_module.py` using the following command:
> ```
> swagger_to_py_client.py --swagger_path path/to/swagger.json --outpath serval_client_module.py
> ```

Where is the json file?  Where should I run the command?  i.e., go to this sub folder of the repo and run it exactly like this...


<!-- Sent from Reviewable.io -->

2023-10-23 16:32 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 29 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSNPKV4ZBUC8g1hq8e:-NhSNPKV4ZBUC8g1hq8f:b-uu46ew) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L29)):*
> ```Python
>             print(f"\tFaulted {build}")
>             session.delete(build)
>             email_server.send_build_faulted_email(build.email, error=data)
> ```

Delete after you do everything else.


<!-- Sent from Reviewable.io -->

2023-10-23 16:41 UTC, johnml1135 commented
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhSP-Z6C3ebWdSEZ9eh:b1u6i4m) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
> ```Python
>         msg['From'] = self.sender_address
>         msg['To'] = recipient_address
>         msg['Subject'] = 'Your NMT build job is complete!'
> ```

There should be more information for distinguishing this.  The initial and final emails should have an ID number that is shared (can use the build ID).  Also, there should be a place for a "name of build" that the user can enter - in case they are making many translations and want to distinguish between them.


<!-- Sent from Reviewable.io -->

2023-10-23 16:44 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhSQ1fQCh8OIbfOz4D6:b-ik82zy) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

As per the other comment, we should allow the user to name an arbitrary string for the engine/build name.
</blockquote></details>

That is, an arbitrary string that we strip of all special characters and normalize.


<!-- Sent from Reviewable.io -->

2023-10-23 16:45 UTC, johnml1135 commented
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhSQKr02vUysvehIOGF:b-kaa4h5) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There should be more information for distinguishing this.  The initial and final emails should have an ID number that is shared (can use the build ID).  Also, there should be a place for a "name of build" that the user can enter - in case they are making many translations and want to distinguish between them.
</blockquote></details>

Also, the source and target languages, along with the names of the Paratext files uploaded should be included in one or both emails.


<!-- Sent from Reviewable.io -->

2023-10-23 16:49 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 113 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSR1Xb-7I5gWuX6xp6:-NhSR1Xb-7I5gWuX6xp7:b-e0b4jq) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L113)):*
> ```Python
>             )
>         )
>         build = json.loads(client.translation_engines_start_build(engine['id'], TranslationBuildConfig(pretranslate=[PretranslateCorpusConfig(corpus_id=corpus["id"], text_ids= [] if st.session_state['source_files'][0].name[-4:] == '.zip' else list(map(lambda f: f.name, st.session_state['source_files'])))], options="{\"max_steps\":10}")))
> ```

max steps 10!?!?!?!??!  At very least have this be set by an environment variable - so we can make a deployment of this either for test or real life.


<!-- Sent from Reviewable.io -->

2023-10-23 16:50 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 126 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSRQ7DD2zHSlTBzQoE:-NhSRQ7DD2zHSlTBzQoF:b-sa50ug) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L126)):*
> ```Python
>         st.session_state['source_language'] = st.text_input(label="Source language tag*", placeholder="en")
>         if st.session_state.get('source_language','') == '' and tried_to_submit:
>             st.error("Please enter a source language tag before submitting", icon='⬆️')
> ```

Point to NLLB-200 language codes - provide a link.


<!-- Sent from Reviewable.io -->

2023-10-23 16:54 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhSSAg-9RXBjw-qPG2y:bpa2g62) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
> ```Python
>             if already_active_build_for(st.session_state['email']):
>                 st.session_state['tried_to_submit'] = True
>                 st.session_state['error'] = "There is already an a pending or active build associated with this email address. Please wait for the previous build to finish."
> ```

Are we sure we want to do this?  There may be one person supporting multiple teams.  How about "You already have {number} build job[s] running.  Are you sure you want to add another one?" 


<!-- Sent from Reviewable.io -->

2023-10-23 16:56 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 154 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSd5yE2nvpWqvKDHN:-NhSSd5yE2nvpWqvKDHO:bnke8g) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L154)):*
> ```Python
>                 st.session_state['tried_to_submit'] = True
>                 st.session_state['error'] = "There is already an a pending or active build associated with this email address. Please wait for the previous build to finish."
>                 st.rerun()
> ```

Also, we should be able to log into the email address sending these emails to periodically check who and how many translations are being made.


<!-- Sent from Reviewable.io -->

2023-10-23 16:56 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhSSqiECyuZziGzN4O1:b-oz6uxj) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
> ```Python
>                 st.session_state['error'] = "Some required fields were left blank. Please fill in all fields above"
>                 st.rerun()
>         st.markdown("<sub>\* Use IETF tags if possible. See [here](https://en.wikipedia.org/wiki/IETF_language_tag) for more information on IETF tags.</sub>", unsafe_allow_html=True)
> ```

Also call out NLLB-200 language codes.


<!-- Sent from Reviewable.io -->

2023-10-23 16:59 UTC, johnml1135 commented
*[`samples/ServalApp/serval_email_module.py` line 69 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTJqx43kTsy2EJLCW:-NhSTJqx43kTsy2EJLCX:b-4ij2at) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L69)):*
> ```Python
> If you are experiencing difficulties using this application, please contact eli_lowry@sil.org.
> 
> Thank you!
> ```

Here is where all the info about the build should be dumped - all the files uploaded, the name chosen, the source and target language, etc.


<!-- Sent from Reviewable.io -->

2023-10-23 17:01 UTC, johnml1135 commented
Did you use black formatting?  Where are the poetry, launch, updated gitignore, etc. files?





<!-- Sent from Reviewable.io -->

2023-10-23 17:01 UTC, johnml1135 requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 18 unresolved discussions (waiting on @Enkidu93)

___
*[`samples/ServalApp/builds.db` line 0 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhSTZB70r_3nsc4moXJ:b39ilci) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L0)):*
This should not be uploaded to Github - but rather should be ignored.
___
*[`samples/ServalApp/serval_app.py` line 33 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSNNGr7StwazF1aYQU:-NhSNNGr7StwazF1aYQV:b-uu46ew) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L33)):*
> ```Python
>         def completed(build:Build, email_server:ServalAppEmailServer, data=None):
>             print(f"\tCompleted {build}")
>             session.delete(build)
> ```

Delete after you do everything else.
___
*[`samples/ServalApp/serval_app.py` line 49 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSO68j1GMQOUgTluVx:-NhSO68j1GMQOUgTluVy:b-x0f291) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L49)):*
> ```Python
>                 started(build, email_server)
>             else:
>                 responses.get(build_update.state, update)(build, email_server, build_update.message)
> ```

For all the times that it is just normally Pending or Active, what happens?  There is no `responses.get` for normal updates.  Will it throw an exception?
`
___
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhSQ_iH5NMcCRTFHC8H:b-abpgm1) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
> ```Python
>     def submit():
>         engine = json.loads(client.translation_engines_create(TranslationEngineConfig(source_language=st.session_state['source_language'],target_language=st.session_state['target_language'],type='Nmt',name=f'serval_app_engine:{st.session_state["email"]}')))
>         source_files = [json.loads(client.data_files_create(st.session_state['source_files'][i], format="Paratext" if st.session_state['source_files'][i].name[-4:] == '.zip' else "Text")) for i in range(len(st.session_state['source_files']))]
> ```

not all Paratext zips have a zip extension.  Either we add the other potential extensions (and say which ones we support), or we give the users a choice.


<!-- Sent from Reviewable.io -->

2023-10-23 18:14 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 18 unresolved discussions (waiting on @johnml1135)

___
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhSfTIK2njg1naZIyvw:b6jzu7j) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should not be uploaded to Github - but rather should be ignored.
</blockquote></details>

I will add it to the .gitignore, but because of the awkwardness of background processes in streamlit and the necessity to rerun the page (which will include any and all code present), I've uploaded an empty, placeholder with the appropriate table added db. 
___
*[`samples/ServalApp/serval_app.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSORmPEcmRFx6Ikv4o:-NhSfyu-AnD6Y3XBcEDq:ba65wnp) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is this never called?
</blockquote></details>

See comment on line 49. 
___
*[`samples/ServalApp/serval_app.py` line 49 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSO68j1GMQOUgTluVx:-NhSg0P3-wWIPdpljsvc:b-hvq9wv) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L49)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

For all the times that it is just normally Pending or Active, what happens?  There is no `responses.get` for normal updates.  Will it throw an exception?
`
</blockquote></details>

The syntax for python dicts is `get(key, default)`. I'm passing a default `update(...)` function to it as a default. I did this for quicker extensibility and fewer lines of code. 
___
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhSgKY9Cup4M5YB4Hnd:b-5wqy5g) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That is, an arbitrary string that we strip of all special characters and normalize.
</blockquote></details>

You mean for this to be synonymous with the `buildName` parameter, yes? There's no such normalization in Serval (except something automagical, maybe). Why the normalization here specifically?
___
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhSgtBK7VDJVOBwYSju:bif9okq) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

not all Paratext zips have a zip extension.  Either we add the other potential extensions (and say which ones we support), or we give the users a choice.
</blockquote></details>

What other zip formats do we support (I didn't realize we did)? .tar? .tar.gz? (It would be good to know and document in general regardless of the solution here).
___
*[`samples/ServalApp/serval_app.py` line 113 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSR1Xb-7I5gWuX6xp6:-NhSh_U79iT3xRLeUyYU:bxs5y8c) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L113)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

max steps 10!?!?!?!??!  At very least have this be set by an environment variable - so we can make a deployment of this either for test or real life.
</blockquote></details>

Good catch! I'll make it configurable.
___
*[`samples/ServalApp/serval_app.py` line 126 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSRQ7DD2zHSlTBzQoE:-NhShde6EBx-2GKfSbOu:bkuqdma) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L126)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Point to NLLB-200 language codes - provide a link.
</blockquote></details>

Addressed in comment on line 166.
___
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhShjAjDw-ur9ZxIiTD:bpy0z7g) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Are we sure we want to do this?  There may be one person supporting multiple teams.  How about "You already have {number} build job[s] running.  Are you sure you want to add another one?"
</blockquote></details>

Would you prefer it to be one build per engine per user? It depends on the most common use-case. I just thought it would keep folks who are playing around a bit from flooding us with jobs. Who do you expect to be the most frequent user?
___
*[`samples/ServalApp/serval_app.py` line 154 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSd5yE2nvpWqvKDHN:-NhSi54SCAq4SxhU6tVP:b-4tqm1k) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L154)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Also, we should be able to log into the email address sending these emails to periodically check who and how many translations are being made.
</blockquote></details>

Yep, we can. I can give you the log-in info if you like.
___
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhSi8HVAoL65gHiJc7v:bnhgwpm) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Also call out NLLB-200 language codes.
</blockquote></details>

Why is this necessary? Just because folks might be confused because they know we use NLLB? Any interaction the user has is completely abstracted from NLLB and maybe that's for the best if we end up switching or allowing for different models? I just want to keep it as simple and un-overwhelming as possible - unlike swagger - and maintain the abstraction as appropriate. 
___
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhSitIFD9Uyy7g6dzNw:bfxyhjy) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Also, the source and target languages, along with the names of the Paratext files uploaded should be included in one or both emails.
</blockquote></details>

OK, I can do that (and the comment on line 69). Everything we want to include will become things we need to store in the db - or mean more API calls - and the list of file names should probably just be stored as a single string if you're OK with that.


<!-- Sent from Reviewable.io -->

2023-10-23 18:24 UTC, Enkidu93 commented
I can add updates to the .gitignore. I can go ahead and add dependencies, yes. As for launch, I don't know if that's appropriate, is it? And OK, I'll use Black Formatting. I actually didn't know what formatting we were using for Python.





<!-- Sent from Reviewable.io -->

2023-10-23 18:32 UTC, johnml1135 commented
Please add the full poetry env - even if it's under the subfolder.  Then it will be easier to run repeatably.





<!-- Sent from Reviewable.io -->

2023-10-23 18:39 UTC, Enkidu93 commented
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhSp1-O80JeVpZd5PTu:bfsv08i) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

You mean for this to be synonymous with the `buildName` parameter, yes? There's no such normalization in Serval (except something automagical, maybe). Why the normalization here specifically?
</blockquote></details>

Follow-up question: It seems to me that it'd be best to simplify this to one user-chosen name (???). Probably build name?


<!-- Sent from Reviewable.io -->

2023-10-23 18:40 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 18 unresolved discussions (waiting on @johnml1135)

___
*[`samples/ServalApp/README.md` line 11 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSMO6k1TDAJwfTfgb4:-NhSmTLnCIOsl8W_wJai:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/README.md#L11)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Where is the json file?  Where should I run the command?  i.e., go to this sub folder of the repo and run it exactly like this...
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 23 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSMslG3FK11dibm0XK:-NhSmeRb7DKVurruqc6N:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L23)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The email sending may fail.  Delete the build after trying to send.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 29 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSNPKV4ZBUC8g1hq8e:-NhSmf9y7d4xwFcp1JOj:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L29)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Delete after you do everything else.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 33 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSNNGr7StwazF1aYQU:-NhSmgBe2cgAF5FWZ5bK:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L33)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Delete after you do everything else.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 41 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSOfYqDdxvaiqYugua:-NhSn8ulDd-X_Tjll5xP:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L41)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should be configurable - for pointing to ext-qa.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 66 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSO_iqCnuJscQPRJHD:-NhSnSSg0qy78mu9UeZi:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L66)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This would be nice to configure - especially for testing.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-23 20:20 UTC, ddaspit reviewed
You can take a look at Machine.py to get an idea (poetry, Black, flake8, etc.).

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192#-:-NhT7rUgBk9jM4Kx_gpN:b-30vb0l)* status: all files reviewed, 18 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhT3FrE7j68T5yav7yg:bg1m7m9) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I will add it to the .gitignore, but because of the awkwardness of background processes in streamlit and the necessity to rerun the page (which will include any and all code present), I've uploaded an empty, placeholder with the appropriate table added db.
</blockquote></details>

I'm not sure I understand what including an empty `builds.db` accomplishes. It is generally a bad idea to check in binary files.
___
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhT7U8dBhsVj_wZ_9Gr:blplic8) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Would you prefer it to be one build per engine per user? It depends on the most common use-case. I just thought it would keep folks who are playing around a bit from flooding us with jobs. Who do you expect to be the most frequent user?
</blockquote></details>

I kind of like the idea of restricting a user to a single build at a time.
___
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhTB6Q36OxVqOxPPFXZ:bkrvjzu) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why is this necessary? Just because folks might be confused because they know we use NLLB? Any interaction the user has is completely abstracted from NLLB and maybe that's for the best if we end up switching or allowing for different models? I just want to keep it as simple and un-overwhelming as possible - unlike swagger - and maintain the abstraction as appropriate.
</blockquote></details>

I agree. I don't think we need to specifically call out the NLLB language codes. We could give a list of the languages that we support and state that a supported language should be used on either the source or target.


<!-- Sent from Reviewable.io -->

2023-10-24 11:19 UTC, johnml1135 commented
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhWPE2L8jIA96TbQKOW:bxh0r0o) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand what including an empty `builds.db` accomplishes. It is generally a bad idea to check in binary files.
</blockquote></details>

You should be able to remove it entirely and then add it to gitignore.  That is the preference.


<!-- Sent from Reviewable.io -->

2023-10-24 11:24 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSORmPEcmRFx6Ikv4o:-NhWQN-o6jlZfA6Midmm:bgswaal) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L37)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

See comment on line 49.
</blockquote></details>

Which file?  There is no comment on line 49.


<!-- Sent from Reviewable.io -->

2023-10-24 11:25 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 49 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSO68j1GMQOUgTluVx:-NhWQYap48hEfGvXM5mU:b-tpxydt) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L49)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

The syntax for python dicts is `get(key, default)`. I'm passing a default `update(...)` function to it as a default. I did this for quicker extensibility and fewer lines of code.
</blockquote></details>

Ah, now I see!


<!-- Sent from Reviewable.io -->

2023-10-24 11:30 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSORmPEcmRFx6Ikv4o:-NhWQd5a8y_vwXynbkIK:b-b7twt6) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Which file?  There is no comment on line 49.
</blockquote></details>

Hmm.  Can it be renamed to default_update?  Then it should be clearer.


<!-- Sent from Reviewable.io -->

2023-10-24 11:32 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhWRyoVEj2K60t1glPe:b386cix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Follow-up question: It seems to me that it'd be best to simplify this to one user-chosen name (???). Probably build name?
</blockquote></details>

Yes, one build name that is character constrained - or at least escaped enough.  It would be (likely) passed down to Serval as both the engine's `name` as well as the build's `buildName`.  This would allow for recon as well.


<!-- Sent from Reviewable.io -->

2023-10-24 11:46 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhWVLwn2-tEPHmoTNGe:bg20oco) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

What other zip formats do we support (I didn't realize we did)? .tar? .tar.gz? (It would be good to know and document in general regardless of the solution here).
</blockquote></details>

I'll ask Damien.


<!-- Sent from Reviewable.io -->

2023-10-24 11:52 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 153 at r2](https://reviewable.io/reviews/sillsdev/serval/192#-NhWWnV6-DPpPTgEfIGf:-NhWWnV6-DPpPTgEfIGg:bmf8aym) ([raw file](https://github.com/sillsdev/serval/blob/e205576d3ea3771d9c55dad501c47651e6cefd00/samples/ServalApp/serval_app.py#L153)):*
> ```Python
>             if already_active_build_for(st.session_state['email']):
>                 st.session_state['tried_to_submit'] = True
>                 st.session_state['error'] = "There is already an a pending or active build associated with this email address. Please wait for the previous build to finish."
> ```

There is a data leak here - people can type in a random email address to see if a person is making builds.  This could be a security issue.  One way to resolve it is to make it unique per email and client ID and make sure the person is authenticated before they can try to build (and check if there is a build running already).


<!-- Sent from Reviewable.io -->

2023-10-24 11:53 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhWWxb_9ERQ-CZUq2et:b-rdeqaj) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I agree. I don't think we need to specifically call out the NLLB language codes. We could give a list of the languages that we support and state that a supported language should be used on either the source or target.
</blockquote></details>

ok - that is fine.


<!-- Sent from Reviewable.io -->

2023-10-24 11:55 UTC, johnml1135 commented
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhWXHrzBgcWKbJEnnr-:bopx408) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, I can do that (and the comment on line 69). Everything we want to include will become things we need to store in the db - or mean more API calls - and the list of file names should probably just be stored as a single string if you're OK with that.
</blockquote></details>

One possibility is to just have the `Build` class print itself in a nice format and include that. 


<!-- Sent from Reviewable.io -->

2023-10-24 11:55 UTC, johnml1135 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 9 unresolved discussions (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2023-10-24 14:43 UTC, Enkidu93 reviewed
Thank you! Done (I believe).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192#-:-NhX5_s166PSzU-uPxe7:b-z5x67f)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`samples/ServalApp/serval_app.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSORmPEcmRFx6Ikv4o:-NhX5eYR83z2cKw0DjxF:bbcqbmd) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L37)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Hmm.  Can it be renamed to default_update?  Then it should be clearer.
</blockquote></details>

(Sorry, the line numbers changed after reformatting). Yes, I can rename it.
___
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhX5pA9DSOChlhnunuJ:b-6uinyp) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes, one build name that is character constrained - or at least escaped enough.  It would be (likely) passed down to Serval as both the engine's `name` as well as the build's `buildName`.  This would allow for recon as well.
</blockquote></details>

OK, but what kind of escaping is required? Does Serval have specifications in this regard? Does it enforce them? What's the goal here? (I understand not wanting to ingest arbitrary data, but I just want to make it consistent with Serval).  
___
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhX6AQqEbQvVb8d2bs5:brxp9sq) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I'll ask Damien.
</blockquote></details>

Sounds good.
___
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhX6C1JCpYwai0Kmd3B:b-264p5t) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

We could keep it this way now and change if needed.  As per a conversation yesterday with management, scaling up users will be with Scripture Forge, not with this app.  Therefore, it should be confined to small ones.
  Should we add the capability to cancel and restart a build?  Is that needed?
</blockquote></details>

Alrighty. I'll leave it then as is. I don't think cancelling a build is necessary at this time given the use-cases and the simplicity of the app, but if you both think I should add it, I can as a "You already have a running build. Would you like to cancel it first?"
___
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhX75808ANH0ZGD0xEm:b-m9tfs7) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

ok - that is fine.
</blockquote></details>

OK, so would you like me to list those on the page? Or just keep it as is with the IETF tag link (although, of course, all of those might not be supported by NLLB)?
___
*[`samples/ServalApp/serval_app.py` line 153 at r2](https://reviewable.io/reviews/sillsdev/serval/192#-NhWWnV6-DPpPTgEfIGf:-NhX6ZGE0VUU04ZHLnfx:bkhzdse) ([raw file](https://github.com/sillsdev/serval/blob/e205576d3ea3771d9c55dad501c47651e6cefd00/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There is a data leak here - people can type in a random email address to see if a person is making builds.  This could be a security issue.  One way to resolve it is to make it unique per email and client ID and make sure the person is authenticated before they can try to build (and check if there is a build running already).
</blockquote></details>

The person cannot check emails until they've been authenticated, but I could make it per client ID if you like as well. Do you expect to give unique creds to most users?
___
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhX7N0F-A-THBLbzbD1:b-9j9thx) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

One possibility is to just have the `Build` class print itself in a nice format and include that.
</blockquote></details>

Right, but the class is tied to the db. I can just add fields - not a big deal. Just pushing for simplicity as much as possible. 
___
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhX7bQt9vaooB4SXzPf:b-51dd9r) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

You should be able to remove it entirely and then add it to gitignore.  That is the preference.
</blockquote></details>

OK, I've removed it. In the past (and ONLY with sqlite dbs), I've been instructed to check in empty dbs for ease, but it really doesn't make a huge difference in this case - even with streamlit's oddities. 


<!-- Sent from Reviewable.io -->

2023-10-24 14:53 UTC, Enkidu93 commented
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhX9yFT-8Edu746rWWP:bnenyy2) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, but what kind of escaping is required? Does Serval have specifications in this regard? Does it enforce them? What's the goal here? (I understand not wanting to ingest arbitrary data, but I just want to make it consistent with Serval).
</blockquote></details>

Also, at the moment, as a default, I have the name as 'serval_app_engine:<email address>'; is that reasonable?


<!-- Sent from Reviewable.io -->

2023-10-24 15:14 UTC, johnml1135 commented
*[`.vscode/settings.json` line 35 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFB0mBvAXYY00N2sN:-NhXFB0nAPgJl1btT4qL:b4pzsqz) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/.vscode/settings.json#L35)):*
> ```JSON
>   "[python]": {
>     "editor.defaultFormatter": "ms-python.black-formatter"
>   }
> ```

And format on save.


<!-- Sent from Reviewable.io -->

2023-10-24 15:15 UTC, johnml1135 commented
*[`.vscode/settings.json` line 35 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFB0mBvAXYY00N2sN:-NhXFHpr6UGvG3AZMp-v:b8tv127) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/.vscode/settings.json#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

And format on save.
</blockquote></details>

    "editor.formatOnSave": true


<!-- Sent from Reviewable.io -->

2023-10-24 15:16 UTC, johnml1135 commented
*[`samples/ServalApp/.flake8` line 5 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFSyb788cy-FLBEP0:-NhXFSyb788cy-FLBEP1:b-c68z65) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/.flake8#L5)):*
> ```INI
> per-file-ignores = serval_app.py:F821,W605
> exclude =
>     serval_client_module.py
> ```

per-file-ignores = **/*.pyi:E252,E301,E302,E305,E501,E701,E704,E741,F401,F811,F821
exclude =
    .git,
    __pycache__,
    .venv


<!-- Sent from Reviewable.io -->

2023-10-24 15:17 UTC, johnml1135 commented
*[`samples/ServalApp/pyproject.toml` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFl6d5cYhxM0pPi_B:-NhXFl6d5cYhxM0pPi_C:b-2oschu) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L9)):*
> ```TOML
> 
> [tool.poetry.dependencies]
> python = ">=3.8,<3.9.7 || >3.9.7,<4.0"
> ```

Why not 3.9.7?  Why not >=3.11?


<!-- Sent from Reviewable.io -->

2023-10-24 15:19 UTC, johnml1135 commented
*[`samples/ServalApp/pyproject.toml` line 14 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG-L47vZV8jvUx0Ev:-NhXG-L47vZV8jvUx0Ew:b-tpjwpx) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L14)):*
> ```TOML
> requests = "^2.31.0"
> SQLAlchemy = "^2.0.22"
> ```

Obviously, you can update the versions.  But there should be dev dependencies.
```
[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
black = "^23.3.0"
flake8 = "^3.9.2"
isort = "^5.9.3"
ipykernel = "^6.7.0"
jupyter = "^1.0.0"
pyright = "^1.1.331"
```


<!-- Sent from Reviewable.io -->

2023-10-24 15:21 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG_RC88nW14BtXVHK:-NhXG_RC88nW14BtXVHL:b-8r0ps1) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/serval_app.py#L95)):*
> ```Python
>                         get_update(build, email_server)
>                     except Exception as e:
>                         print(f"\tFailed to update {build} because of exception {e}")
> ```

Any reason for all the prints rather than actually using a logger?  Then it would be more straightforward to log the exception.


<!-- Sent from Reviewable.io -->

2023-10-24 15:23 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhXHASg0Ih_N4Q_z7KW:boftwgd) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sounds good.
</blockquote></details>

@ddaspit - what are the range of paratext zip extensions?


<!-- Sent from Reviewable.io -->

2023-10-24 15:27 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 153 at r2](https://reviewable.io/reviews/sillsdev/serval/192#-NhWWnV6-DPpPTgEfIGf:-NhXHZlQ9503xtU7qJq4:b3lytw4) ([raw file](https://github.com/sillsdev/serval/blob/e205576d3ea3771d9c55dad501c47651e6cefd00/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

The person cannot check emails until they've been authenticated, but I could make it per client ID if you like as well. Do you expect to give unique creds to most users?
</blockquote></details>

As this is not for many users - probably one per group.  I will assume that the creds will only be shared between a known small group of users (and they can see everything on the Serval site itself if they share creds).  I would just want security between credentials.
  Yes, unique per Email:ClientID combo.


<!-- Sent from Reviewable.io -->

2023-10-24 15:29 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhXI7XK35_Bi01ZxBqG:b-epmq2p) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, so would you like me to list those on the page? Or just keep it as is with the IETF tag link (although, of course, all of those might not be supported by NLLB)?
</blockquote></details>

Conversely, you could provide a link to the Serval swagger doc that talks about language codes: `f"{os.environ.get("SERVAL_HOST_URL")}/swagger/index.html#/Translation%20Engines/TranslationEngines_Create"`


<!-- Sent from Reviewable.io -->

2023-10-24 15:32 UTC, johnml1135 commented
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhXIlvp4IDCY-sdsNUJ:b-dggdlx) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Right, but the class is tied to the db. I can just add fields - not a big deal. Just pushing for simplicity as much as possible.
</blockquote></details>

Whatever implementation you feel is best.  A full record of all the information that they put in (including the ClientID, but not the ClientSecret) would in my mind be the best set of information.  It should also include the engine and build ID in Serval.  The failure or complete emails should just reference the build name that they gave us (which may not be unique) and the engine and build ID (which are).


<!-- Sent from Reviewable.io -->

2023-10-24 15:33 UTC, johnml1135 commented
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhXJLnI4O_YbtDx-iIY:b-n2k69f) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, I've removed it. In the past (and ONLY with sqlite dbs), I've been instructed to check in empty dbs for ease, but it really doesn't make a huge difference in this case - even with streamlit's oddities.
</blockquote></details>

If there is no empty DB, will SQLite crash, or will it automatically create one?  If it crashes, can you add code to automatically create an empty file if it doesn't exist?


<!-- Sent from Reviewable.io -->

2023-10-24 15:35 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhXJhhxBiAZNzorYYeM:b-8aa8rp) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Alrighty. I'll leave it then as is. I don't think cancelling a build is necessary at this time given the use-cases and the simplicity of the app, but if you both think I should add it, I can as a "You already have a running build. Would you like to cancel it first?"
</blockquote></details>

Let's cross the bridge when we come to it.  I like your idea though about asking the user first.


<!-- Sent from Reviewable.io -->

2023-10-24 15:35 UTC, johnml1135 requested changes
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 13 unresolved discussions (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2023-10-24 15:53 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 13 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`samples/ServalApp/.flake8` line 5 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFSyb788cy-FLBEP0:-NhXLfnQ19sLWW0Ijytc:b-pm57y8) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/.flake8#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

per-file-ignores = **/*.pyi:E252,E301,E302,E305,E501,E701,E704,E741,F401,F811,F821
exclude =
    .git,
    __pycache__,
    .venv
</blockquote></details>

May I ask why this is necessary? Doesn't flake8 know to only examine .py files? I thought it did. Also, I don't intend to check in the pycache and I'm not running flake8 on startup, so it that needed?
___
*[`samples/ServalApp/pyproject.toml` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFl6d5cYhxM0pPi_B:-NhXM2rx-a1oihZBhife:b-dklhj2) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why not 3.9.7?  Why not >=3.11?
</blockquote></details>

There's a conflict among the dependencies. This was poetry's recommended solution.
___
*[`samples/ServalApp/pyproject.toml` line 14 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG-L47vZV8jvUx0Ev:-NhXMG7u2YFNjXS17fAb:bokd3j8) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L14)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Obviously, you can update the versions.  But there should be dev dependencies.
```
[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
black = "^23.3.0"
flake8 = "^3.9.2"
isort = "^5.9.3"
ipykernel = "^6.7.0"
jupyter = "^1.0.0"
pyright = "^1.1.331"
```
</blockquote></details>

OK, should I be using 'pyright'? Do you want me to write tests? (it'd be kind of difficult given that it's pretty much all UI) Why jupyter etc.? (Or is this just copy-pasted from machine.py?) I'll go ahead and add the ones I think make sense, and you can correct me.
___
*[`samples/ServalApp/serval_app.py` line 100 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSPwW4DP6_lmzx_2MS:-NhXMvn03HXJ1P3l7ohf:b2nhktp) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L100)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That should be fine.  It will just be for us to look at.  As for filtering out bad characters - it may not actually matter, as long as there is appropriate escaping and any json or string representations are not messed up.
</blockquote></details>

OK.
___
*[`samples/ServalApp/serval_app.py` line 153 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSAg-9RXBjw-qPG2x:-NhXN-azAa9dP-4244Kg:b6cne7e) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Let's cross the bridge when we come to it.  I like your idea though about asking the user first.
</blockquote></details>

OK, sounds good :thumbsup:.
___
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhXNJp25qkfXIcU15mS:b-o7ad8u) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Conversely, you could provide a link to the Serval swagger doc that talks about language codes: `f"{os.environ.get("SERVAL_HOST_URL")}/swagger/index.html#/Translation%20Engines/TranslationEngines_Create"`
</blockquote></details>

True. I wonder if that defeats some of the purpose though given swagger's complexity and the fact that we're trying to hide that. I could include it as a "For more information, see..." kind of thing?
___
*[`samples/ServalApp/serval_app.py` line 153 at r2](https://reviewable.io/reviews/sillsdev/serval/192#-NhWWnV6-DPpPTgEfIGf:-NhXN9c36vIVgj091TjE:b8y0ap5) ([raw file](https://github.com/sillsdev/serval/blob/e205576d3ea3771d9c55dad501c47651e6cefd00/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

As this is not for many users - probably one per group.  I will assume that the creds will only be shared between a known small group of users (and they can see everything on the Serval site itself if they share creds).  I would just want security between credentials.
  Yes, unique per Email:ClientID combo.
</blockquote></details>

OK, the only security complication there is that it would require storing the client ids in the db. That should be alright, correct?
___
*[`samples/ServalApp/serval_app.py` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG_RC88nW14BtXVHK:-NhXMgH9CvLtFG8e5LHz:badd25k) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/serval_app.py#L95)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Any reason for all the prints rather than actually using a logger?  Then it would be more straightforward to log the exception.
</blockquote></details>

I should just use the streamlit logger if possible - good call.
___
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhXNXWl-_Axa23ilGAl:b-76zvog) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Whatever implementation you feel is best.  A full record of all the information that they put in (including the ClientID, but not the ClientSecret) would in my mind be the best set of information.  It should also include the engine and build ID in Serval.  The failure or complete emails should just reference the build name that they gave us (which may not be unique) and the engine and build ID (which are).
</blockquote></details>

OK, so you do or do not want to have a list of file names as well?
___
*[`samples/ServalApp/builds.db` line  at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTZB70r_3nsc4moXI:-NhXNf_OAluA_MMwLeZl:bwrx27b) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/builds.db#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If there is no empty DB, will SQLite crash, or will it automatically create one?  If it crashes, can you add code to automatically create an empty file if it doesn't exist?
</blockquote></details>

Yes, I already took care of it. It will now recreate as needed. The complication (and the reason I was avoiding it) is because streamlit is awkward in that it reruns the entire file at times, so it just adds more complexity and simultaneous db sessions to check and possibly create each time, but it really shouldn't be an issue. 


<!-- Sent from Reviewable.io -->

2023-10-24 16:55 UTC, Enkidu93 commented
*[`.vscode/settings.json` line 35 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFB0mBvAXYY00N2sN:-NhXayF0-iWZtfNCQ141:b-w8gu5o) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/.vscode/settings.json#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

"editor.formatOnSave": true
</blockquote></details>

I believe there's a general setting (line 3 of this file) that takes care of this. Format on save works on my end.


<!-- Sent from Reviewable.io -->

2023-10-24 18:29 UTC, johnml1135 commented
*[`.vscode/settings.json` line 35 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFB0mBvAXYY00N2sN:-NhXwcbU141hih4B4HMc:b-87bzln) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/.vscode/settings.json#L35)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I believe there's a general setting (line 3 of this file) that takes care of this. Format on save works on my end.
</blockquote></details>

I only saw the diff - now I see it.


<!-- Sent from Reviewable.io -->

2023-10-24 18:30 UTC, johnml1135 commented
*[`samples/ServalApp/.flake8` line 5 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFSyb788cy-FLBEP0:-NhXwjz5DIyFdukIux7n:b-4uf9d1) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/.flake8#L5)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

May I ask why this is necessary? Doesn't flake8 know to only examine .py files? I thought it did. Also, I don't intend to check in the pycache and I'm not running flake8 on startup, so it that needed?
</blockquote></details>

If it is ok without it, then let it be.  I was just comparing to Machine.py.


<!-- Sent from Reviewable.io -->

2023-10-24 18:30 UTC, johnml1135 commented
*[`samples/ServalApp/pyproject.toml` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFl6d5cYhxM0pPi_B:-NhXwuyzDeI5fga7xQg6:bzvg5r) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L9)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

There's a conflict among the dependencies. This was poetry's recommended solution.
</blockquote></details>

Good enough- as long as it is intentional.


<!-- Sent from Reviewable.io -->

2023-10-24 18:37 UTC, johnml1135 commented
*[`samples/ServalApp/pyproject.toml` line 14 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG-L47vZV8jvUx0Ev:-NhXyR--C7jYEUAnC0dp:btbvog1) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, should I be using 'pyright'? Do you want me to write tests? (it'd be kind of difficult given that it's pretty much all UI) Why jupyter etc.? (Or is this just copy-pasted from machine.py?) I'll go ahead and add the ones I think make sense, and you can correct me.
</blockquote></details>

Add the ones that make sense - that you need for your development.  We don't need testing.


<!-- Sent from Reviewable.io -->

2023-10-24 18:37 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG_RC88nW14BtXVHK:-NhXyZUh6gIpsXd-J5Ng:b-ucdj9k) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/serval_app.py#L95)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I should just use the streamlit logger if possible - good call.
</blockquote></details>

Yes, that sounds good.


<!-- Sent from Reviewable.io -->

2023-10-24 18:41 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: 7 of 12 files reviewed, 13 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`.vscode/settings.json` line 35 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFB0mBvAXYY00N2sN:-NhXz0tD03MQG_wPpzBi:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/.vscode/settings.json#L35)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I only saw the diff - now I see it.
</blockquote></details>

Done.
___
*[`samples/ServalApp/.flake8` line 5 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFSyb788cy-FLBEP0:-NhXz48D4rq8r_fwDqlT:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/.flake8#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If it is ok without it, then let it be.  I was just comparing to Machine.py.
</blockquote></details>

Done.
___
*[`samples/ServalApp/pyproject.toml` line 9 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXFl6d5cYhxM0pPi_B:-NhXzCpaEh5Nqe_SkGED:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Good enough- as long as it is intentional.
</blockquote></details>

Done.
___
*[`samples/ServalApp/pyproject.toml` line 14 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG-L47vZV8jvUx0Ev:-NhXzE9F8nIBDGr9Usoz:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/pyproject.toml#L14)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Add the ones that make sense - that you need for your development.  We don't need testing.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 37 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSORmPEcmRFx6Ikv4o:-NhXzFh5AC8rJU_0Gkj6:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L37)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

(Sorry, the line numbers changed after reformatting). Yes, I can rename it.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_app.py` line 153 at r2](https://reviewable.io/reviews/sillsdev/serval/192#-NhWWnV6-DPpPTgEfIGf:-NhXzLKr1FL2uan9t-Nh:b9iiutu) ([raw file](https://github.com/sillsdev/serval/blob/e205576d3ea3771d9c55dad501c47651e6cefd00/samples/ServalApp/serval_app.py#L153)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, the only security complication there is that it would require storing the client ids in the db. That should be alright, correct?
</blockquote></details>

I went ahead with this. Should be fine. I
___
*[`samples/ServalApp/serval_app.py` line 95 at r3](https://reviewable.io/reviews/sillsdev/serval/192#-NhXG_RC88nW14BtXVHK:-NhXzH0b9IC8Rous0zyB:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/bfa3be98baac77dc699815282f0d84a03efbe634/samples/ServalApp/serval_app.py#L95)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes, that sounds good.
</blockquote></details>

Done.
___
*[`samples/ServalApp/serval_email_module.py` line 39 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSP-Z6C3ebWdSEZ9eg:-NhXzWsMASKdtAUX7E0y:b-n2buy4) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L39)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, so you do or do not want to have a list of file names as well?
</blockquote></details>

I went ahead and included it all - including file names.
___
*[`samples/ServalApp/serval_email_module.py` line 69 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSTJqx43kTsy2EJLCW:-NhXzXvy-xry9AVnwfxg:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_email_module.py#L69)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Here is where all the info about the build should be dumped - all the files uploaded, the name chosen, the source and target language, etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 18:42 UTC, Enkidu93 commented
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhXzeNbAfceSlV0Ea6D:b-tae82z) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - what are the range of paratext zip extensions?
</blockquote></details>

I went ahead and added just .tar(.gz) until further notice.


<!-- Sent from Reviewable.io -->

2023-10-24 19:10 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhY4w3mB_dRjo3uhph0:b-87tldk) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

True. I wonder if that defeats some of the purpose though given swagger's complexity and the fact that we're trying to hide that. I could include it as a "For more information, see..." kind of thing?
</blockquote></details>

That sounds good.  If it's easy, it should be easy.  If it's challenging, there should be the ability to find the right answer.


<!-- Sent from Reviewable.io -->

2023-10-24 19:14 UTC, johnml1135 commented
*[`samples/ServalApp/serval_app.py` line 101 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSQ_iH5NMcCRTFHC8G:-NhY65Ib7BGREJ49Z0Z8:b-ylf8kg) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L101)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I went ahead and added just .tar(.gz) until further notice.
</blockquote></details>

good enough.


<!-- Sent from Reviewable.io -->

2023-10-24 19:16 UTC, johnml1135 reviewed
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2023-10-24 19:30 UTC, Enkidu93 commented
*[`samples/ServalApp/serval_app.py` line 166 at r1](https://reviewable.io/reviews/sillsdev/serval/192#-NhSSqiECyuZziGzN4O0:-NhY9ZQ-Cru59J5e0xCI:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/e96ef708a68c547a5fddcc83667177beb2ed6119/samples/ServalApp/serval_app.py#L166)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That sounds good.  If it's easy, it should be easy.  If it's challenging, there should be the ability to find the right answer.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 20:59 UTC, johnml1135 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/192)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2023-10-24 21:00 UTC, merged