Download file endpoint
sillsdev/serval pull request #235
Opened 2023-12-08 17:20 UTC by johnml1135

This resolves #232.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/serval/235)

2023-12-08 20:42 UTC, ddaspit requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/235)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlA96bm30GYAs0ytBqi:bt0uxi6) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
> ```Smalltalk
>         foreach (Version version in versions)
>         {
>             services.AddSwaggerGen(o =>
> ```

I don't think this is necessary. I tried removing it and the generated client still looks correct.
___
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA7rVlBCRg_9lyiV4T:-NlA7rVm6Ll_3rW3PGGE:b-6anxey) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.DataFiles/Controllers/DataFilesController.cs#L149)):*
> ```Smalltalk
>     /// <response code="503">A necessary service is currently unavailable. Check `/health` for more details. </response>
>     [Authorize(Scopes.ReadFiles)]
>     [HttpPost("{id}/download")]
> ```

I would prefer the endpoint `{id}/contents`. Nouns are preferred for hypertext resources.


<!-- Sent from Reviewable.io -->

2023-12-08 21:12 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlAGX8gA-eTne1QVnf1:btws84d) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this is necessary. I tried removing it and the generated client still looks correct.
</blockquote></details>

I removed swashbuckle too.  I don't know why it is all working now...


<!-- Sent from Reviewable.io -->

2023-12-08 21:12 UTC, johnml1135 commented
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA7rVlBCRg_9lyiV4T:-NlAGbfX1W5i0lb4thul:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.DataFiles/Controllers/DataFilesController.cs#L149)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer the endpoint `{id}/contents`. Nouns are preferred for hypertext resources.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-08 21:18 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/235)* status: 11 of 14 files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlAHbm99PFnqyqXiqbe:b-xqe54k) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Correction - swashbuckle is needed but no other configuration.
</blockquote></details>

I removed Swashbuckle and it seems to work fine without it.


<!-- Sent from Reviewable.io -->

2023-12-08 21:18 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlAHuDq2EBBT99ogAmX:bi7nnvs) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I removed Swashbuckle and it seems to work fine without it.
</blockquote></details>

Rebuild and run the integration E2E tests. 


<!-- Sent from Reviewable.io -->

2023-12-08 21:48 UTC, ddaspit reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/235)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlAOZIxEphN_TZ404Md:b-25hp6m) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Rebuild and run the integration E2E tests.
</blockquote></details>

I rebuilt and ran the integration tests. They all passed. What is failing on your end?


<!-- Sent from Reviewable.io -->

2023-12-09 03:17 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 119 at r1](https://reviewable.io/reviews/sillsdev/serval/235#-NlA96bm30GYAs0ytBqh:-NlB_2So3p9iy7ztiFa1:boel9bw) ([raw file](https://github.com/sillsdev/serval/blob/a0e46aec41b0fd38866e196c03b2a420e454c60d/src/Serval.ApiServer/Startup.cs#L119)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I rebuilt and ran the integration tests. They all passed. What is failing on your end?
</blockquote></details>

I checked again and now all the tests are passing without Swashbuckle.  I removed it.


<!-- Sent from Reviewable.io -->

2023-12-11 17:52 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/235#-:-NlP-dWP6fzdl0usl03L:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2023-12-11 20:14 UTC, merged