Add health and version endpoints
sillsdev/serval pull request #238
Opened 2023-12-11 19:59 UTC by johnml1135

Supporting #184 and #223 - specifically:
* Show the version endpoint to enable SF to know what it is actually querying if it so desires
* Have the (enhanced!) health check endpoint behind authentication that can replace the exposed one

2023-12-11 20:17 UTC, ddaspit reviewed
What is the difference between the new health endpoint and the existing health endpoint? They are very similar. Do we still need the old one?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238#-:-NlPWceNCax8OqlKQVao:babo6xr)* status: 0 of 8 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-12-11 21:02 UTC, johnml1135 commented
When we move the deployment infrastructure to the new one, we can decommission the old one.





<!-- Sent from Reviewable.io -->

2023-12-11 21:39 UTC, ddaspit requested changes
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 7 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/DeploymentVersion.cs` line 0 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn1f28G9RvGpSxB-t:-NlPn1f28G9RvGpSxB-u:b-unt1lo) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L0)):*
I think this project has gotten sufficiently complex at this point that it would be useful to use the same directory structure as the rest of the projects, so this class should be moved to the `Contracts` folder.
___
*[`src/Serval.ApiServer/DeploymentVersion.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPmMaFDwDxN8udLrtw:-NlPmMaFDwDxN8udLrtx:b-6l2mql) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L3)):*
> ```Smalltalk
> namespace Serval.ApiServer.Controllers;
> 
> public class DeploymentVersion
> ```

This should end with the `Dto` suffix. I would also rename this to `VersionInfoDto`.
___
*[`src/Serval.ApiServer/DeploymentVersion.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPnIbd1XOMf7OiwNCz:-NlPnIbd1XOMf7OiwND-:bzbtefd) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L5)):*
> ```Smalltalk
> public class DeploymentVersion
> {
>     public string servalAppVersion { get; set; } = "Unknown";
> ```

This should be pascal case. Also, I think `ServalServerVersion` would be better.
___
*[`src/Serval.ApiServer/HealthreportDto.cs` line 0 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn_MKAexC8AIp642u:-NlPn_MKAexC8AIp642v:boygp8l) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L0)):*
This should be moved to the `Contracts` folder.
___
*[`src/Serval.ApiServer/HealthreportDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPngHd6QcfczznBERK:-NlPngHd6QcfczznBERL:b-r3jb56) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L3)):*
> ```Smalltalk
> namespace Serval.ApiServer.Controllers;
> 
> public class HealthReportDto
> ```

To ease the move from the old endpoint to the new endpoint, it would probably make sense to use the [same model](https://github.com/sillsdev/serval/blob/0e04baefef036d8b238f18dc9ae35680a180e862/src/Serval.ApiServer/Startup.cs#L228C32-L228C32) as the old endpoint. 
___
*[`src/Serval.ApiServer/StatusController.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPi1u44shuW0l9MkIs:-NlPi1u44shuW0l9MkIt:b-qa6ny0) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L29)):*
> ```Smalltalk
>     [ProducesResponseType(typeof(void), StatusCodes.Status401Unauthorized)]
>     [ProducesResponseType(typeof(void), StatusCodes.Status403Forbidden)]
>     public async Task<IActionResult> GetHealth()
> ```

The return type should be `Task<ActionResult<HealthReportDto>>`. The method name should be `GetHealthAsync`.
___
*[`src/Serval.ApiServer/StatusController.cs` line 43 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPlUUK3RJNpwQfWHSY:-NlPlUUK3RJNpwQfWHSZ:bocki9u) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L43)):*
> ```Smalltalk
>     /// <response code="403">The authenticated client cannot perform the operation</response>
>     [Authorize(Scopes.ReadStatus)]
>     [HttpGet("app_version")]
> ```

I feel like `app_version` might be confusing. "App" usually connotes the calling application. I think just `version` would be fine.


<!-- Sent from Reviewable.io -->

2023-12-12 13:07 UTC, johnml1135 commented
*[`src/Serval.ApiServer/DeploymentVersion.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn1f28G9RvGpSxB-t:-NlT7nqtBcutcII1OFQ1:b-4e34f9) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think this project has gotten sufficiently complex at this point that it would be useful to use the same directory structure as the rest of the projects, so this class should be moved to the `Contracts` folder.
</blockquote></details>

Moved the single file.


<!-- Sent from Reviewable.io -->

2023-12-12 13:07 UTC, johnml1135 commented
*[`src/Serval.ApiServer/DeploymentVersion.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPmMaFDwDxN8udLrtw:-NlT7sYbAzF5IBYIhRhC:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should end with the `Dto` suffix. I would also rename this to `VersionInfoDto`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 13:08 UTC, johnml1135 commented
*[`src/Serval.ApiServer/DeploymentVersion.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPnIbd1XOMf7OiwNCz:-NlT7uXa0NnwIrvIf1RT:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be pascal case. Also, I think `ServalServerVersion` would be better.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 13:09 UTC, johnml1135 commented
*[`src/Serval.ApiServer/HealthreportDto.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn_MKAexC8AIp642u:-NlT8ROJA5tdMo4gPZzE:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be moved to the `Contracts` folder.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-12 13:14 UTC, johnml1135 commented
*[`src/Serval.ApiServer/HealthreportDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPngHd6QcfczznBERK:-NlT98gpCtg7W9e1ZXjt:bf0aynt) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

To ease the move from the old endpoint to the new endpoint, it would probably make sense to use the [same model](https://github.com/sillsdev/serval/blob/0e04baefef036d8b238f18dc9ae35680a180e862/src/Serval.ApiServer/Startup.cs#L228C32-L228C32) as the old endpoint.
</blockquote></details>

I didn't see that at all.  Let's talk today at the meeting.  I am inclined to follow the DTO route rather than the parsing function.  The only difference would be how to handle the data.


<!-- Sent from Reviewable.io -->

2023-12-12 13:21 UTC, johnml1135 commented
*[`src/Serval.ApiServer/HealthreportDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPngHd6QcfczznBERK:-NlTAzoWEeaPpV5HtR6a:b-uhzc4q) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I didn't see that at all.  Let's talk today at the meeting.  I am inclined to follow the DTO route rather than the parsing function.  The only difference would be how to handle the data.
</blockquote></details>

I enumerated the data in the dto.


<!-- Sent from Reviewable.io -->

2023-12-12 13:23 UTC, johnml1135 commented
*[`src/Serval.ApiServer/StatusController.cs` line 29 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPi1u44shuW0l9MkIs:-NlTBYcCDmqPASoAVMqe:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The return type should be `Task<ActionResult<HealthReportDto>>`. The method name should be `GetHealthAsync`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-12 13:25 UTC, johnml1135 commented
*[`src/Serval.ApiServer/StatusController.cs` line 43 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPlUUK3RJNpwQfWHSY:-NlTBf8aAh3pV9S4OQUr:b-ba9qm9) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I feel like `app_version` might be confusing. "App" usually connotes the calling application. I think just `version` would be fine.
</blockquote></details>

Would we add versions of other things in the future?  Machine version?  machine.py version?  whether it is a production or staging deployment?  Should we call it DeploymentInfo?


<!-- Sent from Reviewable.io -->

2023-12-12 17:34 UTC, ddaspit reviewed
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/StatusController.cs` line 43 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPlUUK3RJNpwQfWHSY:-NlU2j4cAoJm1VzddiTH:b-ucayu4) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L43)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Would we add versions of other things in the future?  Machine version?  machine.py version?  whether it is a production or staging deployment?  Should we call it DeploymentInfo?
</blockquote></details>

I think that's fine. We use kebab case for all endpoints, so it should be `deployment-info`.
___
*[`src/Serval.ApiServer/StatusController.cs` line 0 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU3MS_86yCNMCIVg8C:-NlU3MS_86yCNMCIVg8D:bi0816l) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.ApiServer/StatusController.cs#L0)):*
This should be moved to the `Controllers` folder in this project.
___
*[`src/Serval.Shared/Contracts/DeploymentInfoDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU4FeiEsK9J70gFi7G:-NlU4FeiEsK9J70gFi7H:b-jjzodu) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.Shared/Contracts/DeploymentInfoDto.cs#L5)):*
> ```Smalltalk
> public class DeploymentInfoDto
> {
>     public string ServalServerVersion { get; set; } = "Unknown";
> ```

Are we differentiating between the version of the `Serval.ApiServer` and the whole deployment? For example, we could ship a new deployment that only updates Machine and not the Serval server. In this scenario, would we only update the deployment version and not the Serval server version? 
___
*[`src/Serval.ApiServer/DeploymentVersion.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn1f28G9RvGpSxB-t:-NlU4mvDD4P-FmUq5viz:b2iakvf) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Moved the single file.
</blockquote></details>

I meant that this should be moved to the `Contracts` folder in the `Serval.ApiServer` project.
___
*[`src/Serval.ApiServer/HealthreportDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPngHd6QcfczznBERK:-NlU3fv52MKU9P3033Gs:b-xepp9t) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I enumerated the data in the dto.
</blockquote></details>

I'm not saying that you need to use the same code to build the response. I'm just saying that the DTO should reflect the structure of the original health endpoint. You should be able to follow the code and update the DTO to match the output of the old endpoint.
___
*[`src/Serval.ApiServer/HealthreportDto.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn_MKAexC8AIp642u:-NlU3UsY27GQnKqeRMiB:b-bxtsth) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I should have been clearer. I meant create a `Contracts` folder in the `Serval.ApiServer` project and move it there.


<!-- Sent from Reviewable.io -->

2023-12-12 17:43 UTC, johnml1135 commented
*[`src/Serval.ApiServer/StatusController.cs` line  at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU3MS_86yCNMCIVg8C:-NlU6pFEDrgd4pJhyesL:b25ma7y) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.ApiServer/StatusController.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be moved to the `Controllers` folder in this project.
</blockquote></details>

So, should I add Nswag to controllers as well?  It is tested as integration and appears most applicable here.  Especially in that it uses the Serval.ApiServer version as the version.


<!-- Sent from Reviewable.io -->

2023-12-12 17:43 UTC, johnml1135 commented
*[`src/Serval.ApiServer/StatusController.cs` line 43 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPlUUK3RJNpwQfWHSY:-NlU7AlMBPGD3DMtXFG9:b-7rl0jd) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/StatusController.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think that's fine. We use kebab case for all endpoints, so it should be `deployment-info`.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2023-12-12 17:47 UTC, johnml1135 commented
*[`src/Serval.Shared/Contracts/DeploymentInfoDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU4FeiEsK9J70gFi7G:-NlU7_7m4mTeaRJ4x40r:bc7zoe) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.Shared/Contracts/DeploymentInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Are we differentiating between the version of the `Serval.ApiServer` and the whole deployment? For example, we could ship a new deployment that only updates Machine and not the Serval server. In this scenario, would we only update the deployment version and not the Serval server version?
</blockquote></details>

I was thinking of using Serval.ApiServer as an indicator for the whole deployment, changing the version as needed.  Do you have a better way to track the version?  If it is only git tags, the deployment would not be able to know what version it was at.  Yet we also need git tags to have proper releases.  I was thinking of using the Serval.ApiServer project to coincide with git tag versions for deployments including 1.1.RC1, 1.2.3, etc.


<!-- Sent from Reviewable.io -->

2023-12-12 17:58 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/StatusController.cs` line  at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU3MS_86yCNMCIVg8C:-NlU9y2MDHSaxI5Cu1n4:b-hqbb1j) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.ApiServer/StatusController.cs#L)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, should I add Nswag to controllers as well?  It is tested as integration and appears most applicable here.  Especially in that it uses the Serval.ApiServer version as the version.
</blockquote></details>

I'm not sure I understand what you mean by "should I add Nswag to controllers as well?". All I'm saying is that you should create a `Controllers` folder in `Serval.ApiServer` and move this file there. Generally, the folder structure should reflect the namespace structure.


<!-- Sent from Reviewable.io -->

2023-12-12 18:51 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Shared/Contracts/DeploymentInfoDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU4FeiEsK9J70gFi7G:-NlUAieoCfg4ln5lwQGl:b5gynk) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.Shared/Contracts/DeploymentInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I was thinking of using Serval.ApiServer as an indicator for the whole deployment, changing the version as needed.  Do you have a better way to track the version?  If it is only git tags, the deployment would not be able to know what version it was at.  Yet we also need git tags to have proper releases.  I was thinking of using the Serval.ApiServer project to coincide with git tag versions for deployments including 1.1.RC1, 1.2.3, etc.
</blockquote></details>

It might be useful to differentiate the deployment version and the Serval server version. If we differentiate between all of the other components of the deployment, except the Serval server, then we are being inconsistent and losing relevant information. We could easily specify the deployment version in the appsettings file.


<!-- Sent from Reviewable.io -->

2023-12-12 20:44 UTC, johnml1135 commented
*[`src/Serval.ApiServer/HealthreportDto.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn_MKAexC8AIp642u:-NlUlTQQ83KfZFH_HDD0:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I should have been clearer. I meant create a `Contracts` folder in the `Serval.ApiServer` project and move it there.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-12 20:51 UTC, ddaspit reviewed
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 5 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Contracts/HealthreportEntryDto.cs` line 0 at r5](https://reviewable.io/reviews/sillsdev/serval/238#-NlUmrDU0NLchv4BbxaN:-NlUmrDU0NLchv4BbxaO:b-vy5kd) ([raw file](https://github.com/sillsdev/serval/blob/aeca814270bf7231c55b84c35e12d9fd8acb8e41/src/Serval.ApiServer/Contracts/HealthreportEntryDto.cs#L0)):*
The "r" in "report" is not capitalized in the filename. 


<!-- Sent from Reviewable.io -->

2023-12-12 20:59 UTC, johnml1135 commented
*[`src/Serval.ApiServer/StatusController.cs` line  at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU3MS_86yCNMCIVg8C:-NlUp-692UoPTQ4VRY6n:btn5oe4) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.ApiServer/StatusController.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand what you mean by "should I add Nswag to controllers as well?". All I'm saying is that you should create a `Controllers` folder in `Serval.ApiServer` and move this file there. Generally, the folder structure should reflect the namespace structure.
</blockquote></details>

Gotit.


<!-- Sent from Reviewable.io -->

2023-12-12 20:59 UTC, johnml1135 commented
*[`src/Serval.ApiServer/DeploymentVersion.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPn1f28G9RvGpSxB-t:-NlUp25_6OmNoYPIlsdH:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/DeploymentVersion.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I meant that this should be moved to the `Contracts` folder in the `Serval.ApiServer` project.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 21:02 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Contracts/HealthreportEntryDto.cs` line  at r5](https://reviewable.io/reviews/sillsdev/serval/238#-NlUmrDU0NLchv4BbxaN:-NlUpcjv53cJDoR6MDOL:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/aeca814270bf7231c55b84c35e12d9fd8acb8e41/src/Serval.ApiServer/Contracts/HealthreportEntryDto.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The "r" in "report" is not capitalized in the filename.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-12 21:04 UTC, johnml1135 commented
*[`src/Serval.Shared/Contracts/DeploymentInfoDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU4FeiEsK9J70gFi7G:-NlUq4knDowX3wK_kp9H:bubvoib) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.Shared/Contracts/DeploymentInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It might be useful to differentiate the deployment version and the Serval server version. If we differentiate between all of the other components of the deployment, except the Serval server, then we are being inconsistent and losing relevant information. We could easily specify the deployment version in the appsettings file.
</blockquote></details>

Sure - I like it.  I was just thinking that there should be a proper place for it.


<!-- Sent from Reviewable.io -->

2023-12-12 21:27 UTC, johnml1135 commented
*[`src/Serval.ApiServer/HealthreportDto.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/238#-NlPngHd6QcfczznBERK:-NlUvFJN2PeL2oYmZou_:b-vjgb1c) ([raw file](https://github.com/sillsdev/serval/blob/50da03c5247d37375f270608ef704d5d970c2969/src/Serval.ApiServer/HealthreportDto.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not saying that you need to use the same code to build the response. I'm just saying that the DTO should reflect the structure of the original health endpoint. You should be able to follow the code and update the DTO to match the output of the old endpoint.
</blockquote></details>

I changed "Entries" to "Results".  Other than that, I am only adding fields.  We are not using them, but since they are secure, I see little risk in including them.


<!-- Sent from Reviewable.io -->

2023-12-12 21:27 UTC, johnml1135 commented
*[`src/Serval.Shared/Contracts/DeploymentInfoDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/238#-NlU4FeiEsK9J70gFi7G:-NlUtuwZ3v6aQ3zCYHo8:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/332fe96dd1732b91cbd6c8f31c526befb0f437cd/src/Serval.Shared/Contracts/DeploymentInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Sure - I like it.  I was just thinking that there should be a proper place for it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-12-13 12:57 UTC, johnml1135 commented
*[`deploy/values.yaml` line 3 at r6](https://reviewable.io/reviews/sillsdev/serval/238#-NlYEvGqAFyNn4egg7xD:-NlYEvGqAFyNn4egg7xE:b-7oq6ck) ([raw file](https://github.com/sillsdev/serval/blob/8dcbe6a03b27079d896ffff20641464cd09bd89b/deploy/values.yaml#L3)):*
> ```YAML
> externalHost: prod.serval-api.org
> environment: Production
> deploymentVersion: '1.1.0'
> ```

Switched deployment version to actual deployment files, that is, k8s.  This allows us to update the deployment without needing to update the docker image of serval-api.


<!-- Sent from Reviewable.io -->

2023-12-13 15:32 UTC, ddaspit reviewed
> Reviewed 12 of 13 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NlYnSIZ-fuHXuyXmdaD:bb5dezf) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
> ```Smalltalk
>     public string Status { get; set; } = default!;
>     public string Duration { get; set; } = default!;
>     public string Description { get; set; } = default!;
> ```

You should make `Description`, `Exception`, and `Data` optional, since these are optional in the underlying health check report entries.


<!-- Sent from Reviewable.io -->

2023-12-13 15:40 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NlYpV4d2LNtKoaMYaHd:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should make `Description`, `Exception`, and `Data` optional, since these are optional in the underlying health check report entries.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-13 16:09 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NlYvxhs9-teutNU36Cg:b7as1u1) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Data appears to not be optional, namely, in HealthReportEntry.


<!-- Sent from Reviewable.io -->

2023-12-13 17:13 UTC, ddaspit reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NlZ9U8o06iZJYOAoEj_:bbvcep1) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Data appears to not be optional, namely, in HealthReportEntry.
</blockquote></details>

If it is empty, set it to `null`.


<!-- Sent from Reviewable.io -->

2023-12-14 00:50 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-Nl_n2CWAWX9RebWGBW5:b8lvop0) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If it is empty, set it to `null`.
</blockquote></details>

It is clearer.  Ill change it.


<!-- Sent from Reviewable.io -->

2023-12-14 17:44 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NldPl249lgfvNRAAO65:b5m9sya) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It is clearer.  Ill change it.
</blockquote></details>

Sorry, I was talking about the `Data` property. There is no need to include the `Data` property if it is empty. This is also consistent with the old endpoint. I would make it optional. The general rule of thumb for DTOs is that we only include a property if it has a value or data assigned to it. We want our DTOs to be as efficient as possible.


<!-- Sent from Reviewable.io -->

2023-12-14 18:10 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs` line 7 at r7](https://reviewable.io/reviews/sillsdev/serval/238#-NlYnSIZ-fuHXuyXmdaC:-NldWUtu7789V2OyKmER:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a971fc25e8da16ff7a13fea4e5f1f90ec85b0ce3/src/Serval.ApiServer/Contracts/HealthReportEntryDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Sorry, I was talking about the `Data` property. There is no need to include the `Data` property if it is empty. This is also consistent with the old endpoint. I would make it optional. The general rule of thumb for DTOs is that we only include a property if it has a value or data assigned to it. We want our DTOs to be as efficient as possible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 19:54 UTC, ddaspit reviewed
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/Controllers/StatusController.cs` line 87 at r10](https://reviewable.io/reviews/sillsdev/serval/238#-Nlds_TO-5HfEsB6HU8X:-Nlds_TO-5HfEsB6HU8Y:b86guhk) ([raw file](https://github.com/sillsdev/serval/blob/927315d0433c63a49feb5291604da9f65f04dde4/src/Serval.ApiServer/Controllers/StatusController.cs#L87)):*
> ```Smalltalk
>             Exception = healthReportEntry.Exception?.ToString(),
>             Data =
>                 (healthReportEntry.Data is null | healthReportEntry.Data!.Count == 0)
> ```

You are using the bitwise OR operator. It should be `||`. Also, you don't need to check if `healthReportEntry.Data` is `null`. It is not a nullable property. Once you make these changes, you should be able to get rid of the null-forgiving operator.


<!-- Sent from Reviewable.io -->

2023-12-14 20:39 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Controllers/StatusController.cs` line 87 at r10](https://reviewable.io/reviews/sillsdev/serval/238#-Nlds_TO-5HfEsB6HU8X:-Nle2S4N-FAD8y_KG850:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/927315d0433c63a49feb5291604da9f65f04dde4/src/Serval.ApiServer/Controllers/StatusController.cs#L87)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You are using the bitwise OR operator. It should be `||`. Also, you don't need to check if `healthReportEntry.Data` is `null`. It is not a nullable property. Once you make these changes, you should be able to get rid of the null-forgiving operator.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 20:39 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/238#-:-Nle2Z5dA8-4hm9gIIXJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2023-12-14 20:40 UTC, merged