Drive health
sillsdev/serval pull request #269
Opened 2024-01-11 18:08 UTC by johnml1135

Resolves https://github.com/sillsdev/machine/issues/141 and https://github.com/sillsdev/serval/issues/243.

2024-01-11 19:24 UTC, ddaspit requested changes
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269)* status: all files reviewed, 14 unresolved discussions (waiting on @johnml1135)

___
*[`samples/EchoTranslationEngine/EchoTranslationEngine.csproj` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntkXQiBa9tIYp5mwnD:-NntkXQiBa9tIYp5mwnE:b-a6bqt) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/EchoTranslationEngine.csproj#L16)):*
> ```XML
>   <ItemGroup>
>     <ProjectReference Include="..\..\src\Serval.Grpc\Serval.Grpc.csproj" />
> 		<ProjectReference Include="..\..\src\Serval.Shared\Serval.Shared.csproj" />
> ```

I don't think this is needed.
___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntvjMgDd7kh9_UaThH:-NntvjMgDd7kh9_UaThI:b-fsir2n) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L3)):*
> ```Smalltalk
> namespace EchoTranslationEngine;
> 
> public class TranslationEngineServiceV1(BackgroundTaskQueue taskQueue, HealthCheckService healthCheckService) : TranslationEngineApi.TranslationEngineApiBase
> ```

You should update csharpier so that this get formatted correctly.
___
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-NntsTEJD9vsAyTjisWC:bwbak35) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
> ```Smalltalk
>         services.AddHealthChecks().AddIdentityServer(new Uri(authority), name: "Auth0");
> 
>         string DataFilesDir = Configuration!.GetSection(DataFileOptions.Key)!.GetValue<string>("FilesDirectory")!;
> ```

I don't think that the null-forgiving operators are needed here.
___
*[`src/Serval.ApiServer/Startup.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsKAb3VOQHx2_Gl_s:-NntsKAb3VOQHx2_Gl_t:bs4gb6q) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L47)):*
> ```Smalltalk
>         string DataFilesDir = Configuration!.GetSection(DataFileOptions.Key)!.GetValue<string>("FilesDirectory")!;
>         // find drive letter for DataFilesDir
>         string driveLetter = Path.GetPathRoot(DataFilesDir)![..1];
> ```

Please avoid using the null-forgiving operator.
___
*[`src/Serval.ApiServer/Startup.cs` line 216 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsYuO8G8DMzFpTH_6:-NntsYuO8G8DMzFpTH_7:b-lnqxmn) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L216)):*
> ```Smalltalk
>             x.MapHangfireDashboard();
>             x.MapHealthChecks("/health", new HealthCheckOptions { ResponseWriter = WriteHealthCheckResponse.Generate });
>             ;
> ```

There is an extra semicolon here.
___
*[`src/Serval.ApiServer/Controllers/StatusController.cs` line 50 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnIkU4NePtxrBVCQ9:-NntnIkU4NePtxrBVCQA:bwc3sk0) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Controllers/StatusController.cs#L50)):*
> ```Smalltalk
>     /// <remarks>Provides an indication about the health of the API</remarks>
>     /// <response code="200">The API health status</response>
>     [HttpGet("health-public")]
> ```

I would call this something else. Maybe `ping`.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 108 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnkDF9wXIAjbKyJcU:-NntnkDGBrWRd0N7N1Sh:b-d3cqq7) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L108)):*
> ```proto
> 
> message HealthCheckResponse {
>     HealthCheckStatus Status = 1;
> ```

This should be snake case.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 109 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntq-45AupUnhIdwsxu:-Nntq-45AupUnhIdwsxv:b-yf2xpy) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L109)):*
> ```proto
> message HealthCheckResponse {
>     HealthCheckStatus Status = 1;
>     string Duration = 2;
> ```

Do we really need this?
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 110 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntr-5JCkQ1LFYl4m2R:-Nntr-5JCkQ1LFYl4m2S:bmpsxqu) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L110)):*
> ```proto
>     HealthCheckStatus Status = 1;
>     string Duration = 2;
>     map<string, string> Data = 3;
> ```

What is this used for?
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 111 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntqFlT8t8v2HFkDcpk:-NntqFlT8t8v2HFkDcpl:b3wy0zx) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L111)):*
> ```proto
>     string Duration = 2;
>     map<string, string> Data = 3;
>     optional string Exception = 4;
> ```

I would rename this to `error` or more generally `description`.  Remember this is defining an API for engines. An engine could be implemented on any tech stack. We don't need to, nor should we match the C# health check models exactly. All we really need is `status` and `description`.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 163 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntnbhm7hiGSH8O79G_:-Nntnbhn33ka_QI3Rvm2:b-gktd2r) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L163)):*
> ```proto
> 
> enum HealthCheckStatus {
>     Unhealthy = 0;
> ```

These should be all uppercase in order to be consistent with the other enums.
___
*[`src/Serval.Shared/Configuration/IServalBuilderExtensions.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntx9-a7qJKED77LrJD:-Nntx9-a7qJKED77LrJE:b-fhxhxm) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Configuration/IServalBuilderExtensions.cs#L46)):*
> ```Smalltalk
>     )
>     {
>         builder.Services.AddMongoDataAccess(builder.Configuration!.GetConnectionString("Mongo")!, "Serval", configure);
> ```

Please avoid using the null-forgiving operator. Throw an exception if necessary.
___
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntxJbADXgAgIi0YQOG:-NntxJbADXgAgIi0YQOH:b-kcxt5o) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L21)):*
> ```Smalltalk
>             _logger.Log(
>                 LogLevel.Error,
>                 "A user tried to access an unavailable service. Exception: \n{Exception}",
> ```

We already pass the exception to the `Log` method. This might be redundant.
___
*[`src/Serval.Shared/Utils/WriteHealthCheckResponse.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntxcAv9FK1bO2JOdKY:-NntxcAv9FK1bO2JOdKZ:b-vwi1o2) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Utils/WriteHealthCheckResponse.cs#L5)):*
> ```Smalltalk
> public class WriteHealthCheckResponse
> {
>     public static Task Generate(HttpContext context, HealthReport healt [...]

2024-01-11 20:04 UTC, johnml1135 commented
*[`samples/EchoTranslationEngine/EchoTranslationEngine.csproj` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntkXQiBa9tIYp5mwnD:-Nnu7934AtVPCV_ysTWF:bup161j) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/EchoTranslationEngine.csproj#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think this is needed.
</blockquote></details>

Correct.  Removed.


<!-- Sent from Reviewable.io -->

2024-01-11 20:16 UTC, johnml1135 commented
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntvjMgDd7kh9_UaThH:-Nnu7BqBEVqBPhHqRIfQ:b-onhef2) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should update csharpier so that this get formatted correctly.
</blockquote></details>

It's the new net8.0 primary constructor.


<!-- Sent from Reviewable.io -->

2024-01-11 20:18 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-Nnu9mNPEdbgSK7CUYuu:bp2t7fu) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think that the null-forgiving operators are needed here.
</blockquote></details>

net8 was complaining about it - is there a better way?  Should I use a ?  or a if statement?  If it is null, I would want to crash out of the code.


<!-- Sent from Reviewable.io -->

2024-01-11 20:26 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-NnuBuzODtIX46zVzX0d:b-3w8hm7) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

net8 was complaining about it - is there a better way?  Should I use a ?  or a if statement?  If it is null, I would want to crash out of the code.
</blockquote></details>

I see what I was doing - I was confusing the null forgiving operator in CSharp (!) with the not-null assertion operator in Kotlin (!!).  I will change them to the `?? throw` syntax.


<!-- Sent from Reviewable.io -->

2024-01-11 21:05 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsKAb3VOQHx2_Gl_s:-NnuKp6269EhtSFqOvmg:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L47)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please avoid using the null-forgiving operator.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-11 21:08 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 216 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsYuO8G8DMzFpTH_6:-NnuLk6oBlyhxbKmtUc2:b-qssebl) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L216)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is an extra semicolon here.
</blockquote></details>

fixed.


<!-- Sent from Reviewable.io -->

2024-01-11 21:10 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Controllers/StatusController.cs` line 50 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnIkU4NePtxrBVCQ9:-NnuM-r15fv2yePcN1xv:b-722l7f) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Controllers/StatusController.cs#L50)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would call this something else. Maybe `ping`.
</blockquote></details>

ping is ok.


<!-- Sent from Reviewable.io -->

2024-01-11 21:12 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 108 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnkDF9wXIAjbKyJcU:-NnuMGqVA7upikOhLv5s:b34vbl5) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be snake case.
</blockquote></details>

It should be ok - we recast as integers, not as strings.


<!-- Sent from Reviewable.io -->

2024-01-11 21:12 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 109 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntq-45AupUnhIdwsxu:-NnuMbve-xpuu8g6eaKP:bf4p8jm) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we really need this?
</blockquote></details>

It is in the standard health check - and there is no particular reason not to include it.


<!-- Sent from Reviewable.io -->

2024-01-11 21:13 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 110 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntr-5JCkQ1LFYl4m2R:-NnuMgRk4TNvuU2c0Rwz:b-bwi6mi) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L110)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is this used for?
</blockquote></details>

This is used for each of the sub-categories of checks:

```
    "SmtTransfer": {
      "status": "Healthy",
      "duration": "00:00:01.2095377",
      "description": "SmtTransfer",
      "exception": "System.Exception",
      "data": {
        "S3 Bucket": "Healthy: The S3 bucket is available",
        "Mongo": "Healthy: ",
        "Hangfire": "Healthy: ",
        "SMT Engine Storage Capacity": "Healthy: ",
        "ClearML Health Check": "Healthy: ClearML is available"
      }
    },
```


<!-- Sent from Reviewable.io -->

2024-01-11 21:13 UTC, ddaspit reviewed
Why did all of the .json, .ldml, .py files change?

> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269#-:-NnuMg0FBQdv7ViykZ7h:b-odw6ul)* status: all files reviewed, 14 unresolved discussions (waiting on @johnml1135)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntvjMgDd7kh9_UaThH:-NnuJ2bVAff1dYSTarvZ:bf0vl71) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It's the new net8.0 primary constructor.
</blockquote></details>

I know. The line is going over the 120 character limit without wrapping. If you reformat this file with CSharpier, it should fix it.
___
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-NnuM4mI0Y8hz_htPJxw:b14nua0) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I see what I was doing - I was confusing the null forgiving operator in CSharp (!) with the not-null assertion operator in Kotlin (!!).  I will change them to the `?? throw` syntax.
</blockquote></details>

I would do this instead:

``` 
var dataFileOptions = new DataFileOptions();
Configuration.GetSection(DataFileOptions.Key).Bind(dataFileOptions);
```


<!-- Sent from Reviewable.io -->

2024-01-11 21:14 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 111 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntqFlT8t8v2HFkDcpk:-NnuMta3557hI6gAt-W2:b7pfbzi) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L111)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `error` or more generally `description`.  Remember this is defining an API for engines. An engine could be implemented on any tech stack. We don't need to, nor should we match the C# health check models exactly. All we really need is `status` and `description`.
</blockquote></details>

The exception literally captures exceptions - which sometimes can be used for debugging.  They would be on the logs - but again, if it is already included, why not?


<!-- Sent from Reviewable.io -->

2024-01-11 21:17 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 163 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntnbhm7hiGSH8O79G_:-NnuNpBfDnDSLGNJLbMI:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L163)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These should be all uppercase in order to be consistent with the other enums.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-11 21:17 UTC, johnml1135 commented
*[`src/Serval.Shared/Configuration/IServalBuilderExtensions.cs` line 46 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntx9-a7qJKED77LrJD:-NnuNrRn56xIvXqOsSoq:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Configuration/IServalBuilderExtensions.cs#L46)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Please avoid using the null-forgiving operator. Throw an exception if necessary.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-11 21:20 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269)* status: all files reviewed, 13 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 108 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnkDF9wXIAjbKyJcU:-NnuO-Wv99bWU5F4qN4_:b1dh8ib) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It should be ok - we recast as integers, not as strings.
</blockquote></details>

Yes, but it is inconsistent with the rest of the API definition.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 109 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntq-45AupUnhIdwsxu:-NnuNpgC9x4k3a7psuxK:bns8fu8) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L109)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

It is in the standard health check - and there is no particular reason not to include it.
</blockquote></details>

It is in the standard health check for .NET, but this API could be implemented by some other tech stack. I would like to make this as easy as possible to be implemented.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 111 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntqFlT8t8v2HFkDcpk:-NnuNV-T2xnR0GyPdCf-:bcfthdc) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L111)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The exception literally captures exceptions - which sometimes can be used for debugging.  They would be on the logs - but again, if it is already included, why not?
</blockquote></details>

By calling it `exception`, we are assuming a particular language construct. One that some languages might not have. This API is intended to be language-agnostic. 


<!-- Sent from Reviewable.io -->

2024-01-11 21:23 UTC, johnml1135 commented
*[`src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntxJbADXgAgIi0YQOG:-NnuNsmT4ojkrxOMWu2C:b3df3b) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Controllers/ServiceUnavailableExceptionFilter.cs#L21)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We already pass the exception to the `Log` method. This might be redundant.
</blockquote></details>

I think it was needed.  I changed it because net8.0 complained about passing the exception.  I needed to switch the order of exception and message to make the function happy - done.


<!-- Sent from Reviewable.io -->

2024-01-11 21:23 UTC, johnml1135 commented
*[`src/Serval.Shared/Utils/WriteHealthCheckResponse.cs` line 5 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntxcAv9FK1bO2JOdKY:-NnuP9KH6ayaC84S5CsK:b-kwapms) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Utils/WriteHealthCheckResponse.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is only used in `Serval.ApiServer`, so you can move it there.
</blockquote></details>

I used it more places before - you are right.


<!-- Sent from Reviewable.io -->

2024-01-11 21:26 UTC, johnml1135 commented
*[`src/Serval.Shared/Contracts/HealthReportDto.cs` line  at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntyAirAbdkzpGzeY2w:-NnuPlro5Fxdzepxg2d6:b-gdh6hl) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Shared/Contracts/HealthReportDto.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why have these DTOs been moved?
</blockquote></details>

I thought we needed them more places - for sharing with machine - when I was doing the rest endpoints.  I'll move them back.


<!-- Sent from Reviewable.io -->

2024-01-11 21:30 UTC, johnml1135 commented
I ran formatting - I'll check the files again.  They changed more than I was expecting and I will revert at least the ldml.





<!-- Sent from Reviewable.io -->

2024-01-12 01:38 UTC, johnml1135 commented
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntvjMgDd7kh9_UaThH:-NnvJIK34F4-_Gvdbgnf:b-gpmy6) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I know. The line is going over the 120 character limit without wrapping. If you reformat this file with CSharpier, it should fix it.
</blockquote></details>

csharpier doesn't handle primary constructors in C#12 yet - it can only handle C#11.  I am reverting all the new primary constructors to preserve csharpier working.


<!-- Sent from Reviewable.io -->

2024-01-12 01:43 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-NnvKYTJ0z8WHUYn-CJ9:bv2g57b) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would do this instead:

``` 
var dataFileOptions = new DataFileOptions();
Configuration.GetSection(DataFileOptions.Key).Bind(dataFileOptions);
```
</blockquote></details>

What about for connection strings?  Shouldn't we fail if one is not actively defined?


<!-- Sent from Reviewable.io -->

2024-01-12 01:46 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 108 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntnkDF9wXIAjbKyJcU:-NnvLAAQ7WY6pu6Y_rZE:b45y6qz) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L108)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, but it is inconsistent with the rest of the API definition.
</blockquote></details>

updated  - it works magically, making the C# classes names as camel case already.


<!-- Sent from Reviewable.io -->

2024-01-12 01:47 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 109 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntq-45AupUnhIdwsxu:-NnvLcDC98XrKUhqgHkd:buyh7wb) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is in the standard health check for .NET, but this API could be implemented by some other tech stack. I would like to make this as easy as possible to be implemented.
</blockquote></details>

Is making it optional good enough?


<!-- Sent from Reviewable.io -->

2024-01-12 01:53 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 109 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-Nntq-45AupUnhIdwsxu:-NnvMm0oBgjUJL1cC5RA:b-2wx2gm) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L109)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is making it optional good enough?
</blockquote></details>

It isn't needed at all - the Health check function creates it's own duration independent of any data passed.  I'll remove it.


<!-- Sent from Reviewable.io -->

2024-01-12 01:58 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 111 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntqFlT8t8v2HFkDcpk:-NnvNve9C9F8l3Wdxu5o:b-th4gdw) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L111)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

By calling it `exception`, we are assuming a particular language construct. One that some languages might not have. This API is intended to be language-agnostic.
</blockquote></details>

Error is fine enough.  We can map it to exception at the C# Health Check level.


<!-- Sent from Reviewable.io -->

2024-01-12 15:30 UTC, ddaspit reviewed
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntvjMgDd7kh9_UaThH:-NnyDTPR1xf3I9CWg7q-:b1yfbr6) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

csharpier doesn't handle primary constructors in C#12 yet - it can only handle C#11.  I am reverting all the new primary constructors to preserve csharpier working.
</blockquote></details>

It seems to work fine with primary constructors once I updated to the latest version.
___
*[`src/Serval.ApiServer/Startup.cs` line 45 at r1](https://reviewable.io/reviews/sillsdev/serval/269#-NntsTEJD9vsAyTjisWB:-NnyDahq6u40eSNet_gc:bb77ufg) ([raw file](https://github.com/sillsdev/serval/blob/facb9ff641bce29500e0aab1cf8663792bd3f81f/src/Serval.ApiServer/Startup.cs#L45)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What about for connection strings?  Shouldn't we fail if one is not actively defined?
</blockquote></details>

Yes.
___
*[`src/Serval.ApiServer/Startup.cs` line 50 at r3](https://reviewable.io/reviews/sillsdev/serval/269#-NnyHANkDNKsaHAEdErw:-NnyHANkDNKsaHAEdErx:b-ofcdry) ([raw file](https://github.com/sillsdev/serval/blob/cfb3391d2b1c416bb33de6c0f3c168c5db4374e6/src/Serval.ApiServer/Startup.cs#L50)):*
> ```Smalltalk
>         Configuration.GetSection(DataFileOptions.Key).Bind(dataFileOptions);
>         // find drive letter for DataFilesDir
>         string driveLetter = Path.GetPathRoot(dataFileOptions.FilesDirectory)![..1];
> ```

You missed removing the null-forgiving operator here.
___
*[`src/Serval.Shared/Configuration/IServalBuilderExtensions.cs` line 48 at r3](https://reviewable.io/reviews/sillsdev/serval/269#-NnyFG2YE1zLeX96Whl5:-NnyFG2YE1zLeX96Whl6:ba8os0a) ([raw file](https://github.com/sillsdev/serval/blob/cfb3391d2b1c416bb33de6c0f3c168c5db4374e6/src/Serval.Shared/Configuration/IServalBuilderExtensions.cs#L48)):*
> ```Smalltalk
>         var mongoConnectionString =
>             builder.Configuration?.GetConnectionString("Mongo")
>             ?? throw new Exception("Mongo connection string not configured");
> ```

I generally try to avoid throwing `Exception`. `InvalidOperationException` would be fine in this case. Also, please avoid the `?? throw` syntax. I don't think it is as clear as a normal `if` statement.


<!-- Sent from Reviewable.io -->

2024-01-15 19:47 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Startup.cs` line 50 at r3](https://reviewable.io/reviews/sillsdev/serval/269#-NnyHANkDNKsaHAEdErw:-NoDeQjR49AkIbQdyoW0:b-886gsx) ([raw file](https://github.com/sillsdev/serval/blob/cfb3391d2b1c416bb33de6c0f3c168c5db4374e6/src/Serval.ApiServer/Startup.cs#L50)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You missed removing the null-forgiving operator here.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2024-01-16 14:38 UTC, ddaspit reviewed
> Reviewed 23 of 23 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`samples/EchoTranslationEngine/EchoTranslationEngine.csproj` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/269#-NoHgkDHBX8VSFGOfnk-:-NoHgkDHBX8VSFGOfnk0:b-u7mv12) ([raw file](https://github.com/sillsdev/serval/blob/b1eb2c10e6467913da31d97eb17567f708c7c046/samples/EchoTranslationEngine/EchoTranslationEngine.csproj#L16)):*
> ```XML
>   <ItemGroup>
>     <ProjectReference Include="..\..\src\Serval.Grpc\Serval.Grpc.csproj" />
> 		<ProjectReference Include="..\..\src\Serval.Shared\Serval.Shared.csproj" />
> ```

Why was this added back?


<!-- Sent from Reviewable.io -->

2024-01-16 14:49 UTC, johnml1135 commented
*[`samples/EchoTranslationEngine/EchoTranslationEngine.csproj` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/269#-NoHgkDHBX8VSFGOfnk-:-NoHjfwP-F-Byjt2eDXs:bp01y1s) ([raw file](https://github.com/sillsdev/serval/blob/b1eb2c10e6467913da31d97eb17567f708c7c046/samples/EchoTranslationEngine/EchoTranslationEngine.csproj#L16)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this added back?
</blockquote></details>

By accident - I removed the commit that did all the mis-formatting of files and must have removed that change from it.


<!-- Sent from Reviewable.io -->

2024-01-16 14:49 UTC, johnml1135 commented
*[`src/Serval.Shared/Configuration/IServalBuilderExtensions.cs` line 48 at r3](https://reviewable.io/reviews/sillsdev/serval/269#-NnyFG2YE1zLeX96Whl5:-NoDeo4S-K6zq68rBhv9:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/cfb3391d2b1c416bb33de6c0f3c168c5db4374e6/src/Serval.Shared/Configuration/IServalBuilderExtensions.cs#L48)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I generally try to avoid throwing `Exception`. `InvalidOperationException` would be fine in this case. Also, please avoid the `?? throw` syntax. I don't think it is as clear as a normal `if` statement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-16 16:33 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/269#-:-NoI6gFI8f_f8tDIJ3Kq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-01-16 19:15 UTC, merged