Add Language Info endpoint
sillsdev/serval pull request #283
Opened 2024-01-22 13:38 UTC by johnml1135

Move queue endpoint

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/serval/283)

2024-01-22 14:24 UTC, Enkidu93 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 303 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolYNZ0ATJUT3-vTUtp:-NolYNZ0ATJUT3-vTUtq:bi1patf) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L303)):*
> ```Smalltalk
>             new GetLanguageInfoResponse
>             {
>                 ResolvedLanguageCode = "hello",
> ```

Given that the Echo engine in general just spits back whatever you give in, would it be worth doing something more akin to that here. I get that it's a bit harder to echo this information since it needs to undergo transformation. If we do keep it this way, we should at least make sure this is documented since this is meant to be used for testing and someone might expect that the response language code, for example, is just the input (?).
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1051 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolXjlJ47N5UAPQuvoY:-NolXjlJ47N5UAPQuvoZ:b-w6q1vq) ([raw file](https://github.com/sillsdev/serval/blob/04f977f2ecde44c94b9b9306b22a966aa6242167/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1051)):*
> ```Smalltalk
>     }
> 
>     private QueueDto Map(Queue source) => new() { Size = source.Size, EngineType = source.EngineType };
> ```

Is the goal to ultimately reimplement something very much akin to this but that allows you to specify which queue? Or am I misunderstanding? Is it just that you want to be able to specify the queue on creation? I thought one of the rationales was that this could be used to probe queue loads before adding jobs (which just specifying a queue in `buildOptions` wouldn't allow you to do. If the plan is to rebuild this slightly differently, then I wonder if it's worth just doing that now in the same PR since the code will be relatively similar and not take much effort. If not, we should probably remove the corresponding code on the Machine side (?). 
___
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1424 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolWRqe6OTtNbxm7gZj:-NolWRqe6OTtNbxm7gZk:b-wd1zxt) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1424)):*
> ```Smalltalk
>         }
> 
>         public TranslationClient CreateTranslationClient(IEnumerable<string>? scope = null)
> ```

Why make a new client creation method instead of extending the previous one?


<!-- Sent from Reviewable.io -->

2024-01-22 14:26 UTC, Enkidu93 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1051 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolXjlJ47N5UAPQuvoY:-NolZAnWBuISFPs99QUL:bxqigfg) ([raw file](https://github.com/sillsdev/serval/blob/04f977f2ecde44c94b9b9306b22a966aa6242167/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1051)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is the goal to ultimately reimplement something very much akin to this but that allows you to specify which queue? Or am I misunderstanding? Is it just that you want to be able to specify the queue on creation? I thought one of the rationales was that this could be used to probe queue loads before adding jobs (which just specifying a queue in `buildOptions` wouldn't allow you to do. If the plan is to rebuild this slightly differently, then I wonder if it's worth just doing that now in the same PR since the code will be relatively similar and not take much effort. If not, we should probably remove the corresponding code on the Machine side (?).
</blockquote></details>

Oh, I see - nevermind!


<!-- Sent from Reviewable.io -->

2024-01-22 14:31 UTC, Enkidu93 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-Nol_C-a1gCdYSAWL1MT:-Nol_C-a1gCdYSAWL1MU:b-w7pc4f) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/src/Serval.Translation/Controllers/TranslationController.cs#L63)):*
> ```Smalltalk
>     [ProducesResponseType(typeof(void), StatusCodes.Status503ServiceUnavailable)]
>     public async Task<ActionResult<LanguageInfoDto>> GetLanguageInfoAsync(
>         [NotNull] string engineType,
> ```

Same as with queueDepth above. See this message from Damien on this topic during the initial queue depth PR: https://github.com/sillsdev/serval/pull/177#pullrequestreview-1674873160. This is why it inadvertently ended up being a POST request.


<!-- Sent from Reviewable.io -->

2024-01-22 14:39 UTC, johnml1135 commented
*[`samples/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 303 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolYNZ0ATJUT3-vTUtp:-Nolb5PB1tnRMZx8mMA2:b-335fhv) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/samples/EchoTranslationEngine/TranslationEngineServiceV1.cs#L303)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Given that the Echo engine in general just spits back whatever you give in, would it be worth doing something more akin to that here. I get that it's a bit harder to echo this information since it needs to undergo transformation. If we do keep it this way, we should at least make sure this is documented since this is meant to be used for testing and someone might expect that the response language code, for example, is just the input (?).
</blockquote></details>

Agreed - that makes more sense.


<!-- Sent from Reviewable.io -->

2024-01-22 14:45 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-Nol_C-a1gCdYSAWL1MT:-NolcNp999LI2usmjHNy:b-gj3d52) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/src/Serval.Translation/Controllers/TranslationController.cs#L63)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Same as with queueDepth above. See this message from Damien on this topic during the initial queue depth PR: https://github.com/sillsdev/serval/pull/177#pullrequestreview-1674873160. This is why it inadvertently ended up being a POST request.
</blockquote></details>

Can you copy the comment from that review here?  I don't know which one you are referring to.


<!-- Sent from Reviewable.io -->

2024-01-22 14:46 UTC, johnml1135 commented
This also resolves https://github.com/sillsdev/serval/issues/281.





<!-- Sent from Reviewable.io -->

2024-01-22 14:46 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1051 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolXjlJ47N5UAPQuvoY:-NolckVq7fCTB6Z67qp_:bjudz33) ([raw file](https://github.com/sillsdev/serval/blob/04f977f2ecde44c94b9b9306b22a966aa6242167/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1051)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I do still wonder if it's worth adding in that queue-specification in this PR if that is the ultimate intent.
</blockquote></details>

I added the reference to https://github.com/sillsdev/serval/issues/281 above.


<!-- Sent from Reviewable.io -->

2024-01-22 14:48 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1424 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolWRqe6OTtNbxm7gZj:-NolcsxK7ikeO-ts6k8m:b5nn4jd) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1424)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why make a new client creation method instead of extending the previous one?
</blockquote></details>

Am I able to?  The queue and the language info are now in a separate file TranslationController.cs because we needed a different endpoint.  I can merge the two files into one file called TranslationController.cs and redo all the "engines" endpoints - what do you  think is best?


<!-- Sent from Reviewable.io -->

2024-01-22 14:59 UTC, Enkidu93 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-Nol_C-a1gCdYSAWL1MT:-NolfmNB7BZH-tPGfDcC:b-1vzkcm) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/src/Serval.Translation/Controllers/TranslationController.cs#L63)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you copy the comment from that review here?  I don't know which one you are referring to.
</blockquote></details>

URLs are often treated as case insensitive. In this case, just the engine type part of the URL will be case sensitive. Unfortunately, we never expected to use the engine types in a URL, so they can't easily be converted to Pascal case. We have a couple of options:

1.  Change the engine type values to kebab case on all endpoints (breaking change). We convert to Pascal case for internal use or switch to using kebab case everywhere.
2.  Change the engine type values to kebab case only on this endpoint. We convert to Pascal case for internal use.
3.  Pass the engine type in the body or query string.
4.  Require that engine types are case insensitive everywhere.


<!-- Sent from Reviewable.io -->

2024-01-22 15:03 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-Nol_C-a1gCdYSAWL1MT:-NolgWElCqPAeFyuaZGq:b-2sosyg) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/src/Serval.Translation/Controllers/TranslationController.cs#L63)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

URLs are often treated as case insensitive. In this case, just the engine type part of the URL will be case sensitive. Unfortunately, we never expected to use the engine types in a URL, so they can't easily be converted to Pascal case. We have a couple of options:

1.  Change the engine type values to kebab case on all endpoints (breaking change). We convert to Pascal case for internal use or switch to using kebab case everywhere.
2.  Change the engine type values to kebab case only on this endpoint. We convert to Pascal case for internal use.
3.  Pass the engine type in the body or query string.
4.  Require that engine types are case insensitive everywhere.
</blockquote></details>

@ddaspit - what do you think?  I am inclined to do the case insensitive route...


<!-- Sent from Reviewable.io -->

2024-01-22 17:18 UTC, ddaspit requested changes
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 10 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 85 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-NolfsET8p_3Ot7tiX1v:-NolfsET8p_3Ot7tiX1w:b-2wewi1) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L85)):*
> ```proto
> message GetLanguageInfoRequest {
>     string engine_type = 1;
>     string language_code = 2;
> ```

This should be named `language` to be consistent with the rest of the API.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-Nom8ZA2C3U9KFT25tBA:b-wrtzoc) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
> ```Smalltalk
> public class LanguageInfoDto
> {
>     public string ResolvedLanguageCode { get; set; } = default!;
> ```

I think I would prefer a different name. I don't think "resolved" is very clear in this context. Maybe something like `InternalCode`.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-Nom96wD90oiFHjAv86D:bndt5cd) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
> ```Smalltalk
> {
>     public string ResolvedLanguageCode { get; set; } = default!;
>     public bool NativeLanguageSupport { get; set; } = default!;
> ```

To be consistent with the rest of the API, you should use `IsSupported`.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-Nom9_wA86CDahFu83mG:bibk4u1) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
> ```Smalltalk
>     public string ResolvedLanguageCode { get; set; } = default!;
>     public bool NativeLanguageSupport { get; set; } = default!;
>     public string CommonLanguageName { get; set; } = default!;
> ```

I'm not sure what "common" means in this context. I think simply `Name` should be sufficient.
___
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-Nol_C-a1gCdYSAWL1MT:-Nom7rgB44Oy0HmNqOQm:btjft73) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/src/Serval.Translation/Controllers/TranslationController.cs#L63)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - what do you think?  I am inclined to do the case insensitive route...
</blockquote></details>

I think we should go with option 1 with one modification. We still support the engine type in pascal case for existing endpoints for backwards compatibility. 
___
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom7ccW7_jIwGEaQTxk:-Nom7ccW7_jIwGEaQTxl:bwxmjqq) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L6)):*
> ```Smalltalk
> [Route("api/v{version:apiVersion}/translation")]
> [OpenApiTag("Translation Engines")]
> public class TranslationController(IAuthorizationService authService, IEngineService engineService)
> ```

This should be a translation engine types controller. The route would be `api/v{version:apiVersion}/translation/engine-types`.
___
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 57 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8JYU2ZP-0ybcBXnv:-Nom8JYU2ZP-0ybcBXnw:b-xl5cc3) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L57)):*
> ```Smalltalk
>     /// <response code="503">A necessary service is currently unavailable. Check `/health` for more details. </response>
>     [Authorize(Scopes.ReadTranslationEngines)]
>     [HttpGet("{engineType}/language-info/{languageCode}")]
> ```

I would rename the route to `languages`.
___
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9nzB1s5IzXpFx9lA:-Nom9nzB1s5IzXpFx9lB:b-lxf6iv) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L64)):*
> ```Smalltalk
>     public async Task<ActionResult<LanguageInfoDto>> GetLanguageInfoAsync(
>         [NotNull] string engineType,
>         [NotNull] string languageCode,
> ```

This should be simply `language`.


<!-- Sent from Reviewable.io -->

2024-01-22 17:37 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 85 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-NolfsET8p_3Ot7tiX1v:-NomEqL-CpoWfj2fuvD4:b-5sg3a3) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L85)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `language` to be consistent with the rest of the API.
</blockquote></details>

Replaced in all locations in serval and machine.


<!-- Sent from Reviewable.io -->

2024-01-22 17:38 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NomEuQq-nZHoxwWMQOA:b-nbl6pe) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think I would prefer a different name. I don't think "resolved" is very clear in this context. Maybe something like `InternalCode`.
</blockquote></details>

ISOLanguage?  ISO639_3Language?  InternationalLanguage?


<!-- Sent from Reviewable.io -->

2024-01-22 17:39 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-NomFFU57nNo9lABkzxQ:bpg2g3o) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

To be consistent with the rest of the API, you should use `IsSupported`.
</blockquote></details>

All languages are supported - how about `IsSupportedNatively`?


<!-- Sent from Reviewable.io -->

2024-01-22 17:40 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NomFQ-i88aWWmpw16iX:b-fhrj5f) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure what "common" means in this context. I think simply `Name` should be sufficient.
</blockquote></details>

English, etc.  They are from the table here: https://github.com/facebookresearch/flores/blob/main/flores200/README.md


<!-- Sent from Reviewable.io -->

2024-01-22 17:41 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom7ccW7_jIwGEaQTxk:-NomFsyqESyy2x-mnhY7:b-iofhvy) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be a translation engine types controller. The route would be `api/v{version:apiVersion}/translation/engine-types`.
</blockquote></details>

Changed and file renamed.


<!-- Sent from Reviewable.io -->

2024-01-22 17:42 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 57 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8JYU2ZP-0ybcBXnv:-NomFw1l7hyPO5bwbG-B:b-1om1bm) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L57)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename the route to `languages`.
</blockquote></details>

All "codes" renamed.


<!-- Sent from Reviewable.io -->

2024-01-22 17:42 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 64 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9nzB1s5IzXpFx9lA:-NomG2uHAKWDd7jkAZt0:bb7f2mf) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be simply `language`.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-01-22 17:48 UTC, Enkidu93 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1424 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolWRqe6OTtNbxm7gZj:-NolfdP7BcJnR1wyj9Vo:bc2a6xd) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1424)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Am I able to?  The queue and the language info are now in a separate file TranslationController.cs because we needed a different endpoint.  I can merge the two files into one file called TranslationController.cs and redo all the "engines" endpoints - what do you  think is best?
</blockquote></details>

I see. No, I think your refactor makes sense. 


<!-- Sent from Reviewable.io -->

2024-01-22 17:52 UTC, Enkidu93 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-NomHzOM0A2WeHraCxGG:b-w04ieg) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

All languages are supported - how about `IsSupportedNatively`?
</blockquote></details>

Where is `IsSupported` used elsewhere in the API? And to be clear, this flag just tells the user whether the language is one of NLLB's 200, right? That's what this means?


<!-- Sent from Reviewable.io -->

2024-01-22 17:56 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-NomJ3Xm5DiCDqnpqAjO:b-qlrh2j) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Where is `IsSupported` used elsewhere in the API? And to be clear, this flag just tells the user whether the language is one of NLLB's 200, right? That's what this means?
</blockquote></details>

Yes, it says if the language is in the NLLB200, and when MADLAD is supported, it will tell if it is in that model natively.  This can be used for determining if a language is supported for source text or if you can do direct inferencing on it.


<!-- Sent from Reviewable.io -->

2024-01-22 17:57 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1424 at r1](https://reviewable.io/reviews/sillsdev/serval/283#-NolWRqe6OTtNbxm7gZj:-NomJNyqET-1fMwgGcyj:b-jxy7qt) ([raw file](https://github.com/sillsdev/serval/blob/027027a95d0b224097e751e0347f1b98e187a74f/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1424)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see. No, I think your refactor makes sense.
</blockquote></details>

I will keep the refactor then and rename the file to TranslationEngineTypesController.cs (as per Damien's comment).


<!-- Sent from Reviewable.io -->

2024-01-22 17:59 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NomJy_O4sZpbK4lyqVl:b-hp9rs6) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

ISOLanguage?  ISO639_3Language?  InternationalLanguage?
</blockquote></details>

ISOLanguageCode?


<!-- Sent from Reviewable.io -->

2024-01-22 18:15 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-NomNfPi0OeMxzsYmmC1:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, yes, makes sense. I don't see an issue with something like `IsSupportedNatively` or `IsSupportedByModel`. If Damien just meant by `IsSupported` that you should give it a name with 'Is' in its name, then cool, but I do think just `IsSupported` might be confusing since we *can* support languages for which this is false in a sense - the model just doesn't have native support without fine-tuning. We can clarify in the docs of course, but it would be nice to have that meaning encoded in the name.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-22 18:17 UTC, Enkidu93 approved these changes
Everything that caught my attention has been resolved <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283#-:-NomNkHI31idsSseZSXN:b-357rbr)* status: all files reviewed, 8 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-01-22 19:36 UTC, ddaspit reviewed
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NombW-u4adw8rSwQQQN:bcm1jjg) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

ISOLanguageCode?
</blockquote></details>

`ISOLanguageCode` isn't really appropriate either. This refers to the token that is used by model to represent a language. For example, in the MADLAD-400 model the English token would be `<2en>`.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-NomboAV9ddVLdEJtZ8M:b-zh77ad) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, I was referring to the convention `Is<name>` for boolean variables. I would just go with `IsNative`. It conveys the same meaning, and it is better to be concise, especially in DTOs.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NomcyikAuTVQ6cqTb6C:bhdvyqs) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

English, etc.  They are from the table here: https://github.com/facebookresearch/flores/blob/main/flores200/README.md
</blockquote></details>

This field is just the language name. In the context of a `LanguageInfo`, all that is needed is `Name` to convey the same thing.
___
*[`src/Serval.Translation/Controllers/TranslationController.cs` line 57 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8JYU2ZP-0ybcBXnv:-NomdIuMBSxHnab0b3jn:b-2fpo61) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Controllers/TranslationController.cs#L57)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

All "codes" renamed.
</blockquote></details>

Sorry, I was referring to the route, i.e. `{engineType}/languages/{languageCode}`.


<!-- Sent from Reviewable.io -->

2024-01-22 19:47 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NomhZMy1hcDcErGoibY:bk2fbhq) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`ISOLanguageCode` isn't really appropriate either. This refers to the token that is used by model to represent a language. For example, in the MADLAD-400 model the English token would be `<2en>`.
</blockquote></details>

I'll switch to InternalCode.


<!-- Sent from Reviewable.io -->

2024-01-22 19:49 UTC, Enkidu93 approved these changes
> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-01-22 19:51 UTC, Enkidu93 commented
@ddaspit I see you re-requested my review; was there something in particular you had in mind for me to look at?

2024-01-22 19:51 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NomiMBh4NQAsC2OXLRt:bs6j4cw) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I'll switch to InternalCode.
</blockquote></details>

I would also make this optional, since there might be engines where this is irrelevant.
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NomiTR66UVDaZ1_6_mf:b-5z5uix) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This field is just the language name. In the context of a `LanguageInfo`, all that is needed is `Name` to convey the same thing.
</blockquote></details>

I would make this optional.


<!-- Sent from Reviewable.io -->

2024-01-22 19:52 UTC, ddaspit reviewed
I'm not sure how I did that. You don't need to re-review anything.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283#-:-NomigQo4cRkwlE-zuph:bhhekcp)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-01-22 21:17 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-Non150S2Rh3Jq_q1LF0:b-8l6aq) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would also make this optional, since there might be engines where this is irrelevant.
</blockquote></details>

Hmm - then the entire endpoint would be meaningless?  Would Smt engines have native support?


<!-- Sent from Reviewable.io -->

2024-01-22 21:38 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom96wD90oiFHjAv86C:-Non631T-v1u_JQVG_P7:b-9c99zb) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, I was referring to the convention `Is<name>` for boolean variables. I would just go with `IsNative`. It conveys the same meaning, and it is better to be concise, especially in DTOs.
</blockquote></details>

IsNative.  I like it.


<!-- Sent from Reviewable.io -->

2024-01-22 21:47 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-Non7i8n05yDysn0C3Yd:bi8b7i0) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make this optional.
</blockquote></details>

Can I update to dotnet standard 2.1?  I want nullable types..


<!-- Sent from Reviewable.io -->

2024-01-22 21:55 UTC, ddaspit reviewed
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-Non8xWo8NkcnaL1xxBG:b-rodok6) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Hmm - then the entire endpoint would be meaningless?  Would Smt engines have native support?
</blockquote></details>

The main use case for the endpoint is the `IsNative` property. The `InternalCode` is only relevant for pretrained multilingual NMT models. For SMT, I guess everything is native. 
___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-Non9Sf3Do3P5E5qpTFg:b-7x1o51) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can I update to dotnet standard 2.1?  I want nullable types..
</blockquote></details>

What do you want to update to .NET Standard 2.1? This assembly is a .NET 8 DLL, so it already supports nullable types.


<!-- Sent from Reviewable.io -->

2024-01-22 21:58 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NonAUGmC2uJVDwqvjaW:bz5dj49) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What do you want to update to .NET Standard 2.1? This assembly is a .NET 8 DLL, so it already supports nullable types.
</blockquote></details>

I think I need to update the language support to "latest" and add "nullable" - https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version.  I don't need 2.1 - I was wrong.


<!-- Sent from Reviewable.io -->

2024-01-22 22:02 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NonBT3UEmAFRsyLeILD:bf45prn) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think I need to update the language support to "latest" and add "nullable" - https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version.  I don't need 2.1 - I was wrong.
</blockquote></details>

If we update to C# latest, we get 400+ warnings about nullable types.  What should we do?  Let's have a short meeting tomorrow.


<!-- Sent from Reviewable.io -->

2024-01-22 22:24 UTC, ddaspit reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NonFsdM6jwFsg1vapX0:bnlcepo) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If we update to C# latest, we get 400+ warnings about nullable types.  What should we do?  Let's have a short meeting tomorrow.
</blockquote></details>

I'm confused. This is already a .NET 8 project, so the default C# language version is 12, which supports nullable types.
___
*[`src/Serval.Translation/Controllers/TranslationEngineTypesController.cs` line 64 at r5](https://reviewable.io/reviews/sillsdev/serval/283#-NonFjVgBd8LBXuc23Dr:-NonFjVgBd8LBXuc23Ds:b-h1s66y) ([raw file](https://github.com/sillsdev/serval/blob/780f5fcb9cbc8db811eef63578f14d01d4ec1611/src/Serval.Translation/Controllers/TranslationEngineTypesController.cs#L64)):*
> ```Smalltalk
>     public async Task<ActionResult<LanguageInfoDto>> GetLanguageInfoAsync(
>         [NotNull] string engineType,
>         [NotNull] string languageCode,
> ```

This should be `language` like everything else.


<!-- Sent from Reviewable.io -->

2024-01-23 12:38 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 5 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom8ZA2C3U9KFT25tB9:-NoqJb5sEq2w0nJ4fAlu:bh1y6u8) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The main use case for the endpoint is the `IsNative` property. The `InternalCode` is only relevant for pretrained multilingual NMT models. For SMT, I guess everything is native.
</blockquote></details>

How about make IsNative an enum? IsNative: True|False|N/A


<!-- Sent from Reviewable.io -->

2024-01-23 13:17 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationInfoDto.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/serval/283#-Nom9_wA86CDahFu83mF:-NoqK-u59yVlazOJsYEZ:bt02ld1) ([raw file](https://github.com/sillsdev/serval/blob/277b4f4ed93b5486820c373c81d27051d1b00848/src/Serval.Translation/Contracts/TranslationInfoDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm confused. This is already a .NET 8 project, so the default C# language version is 12, which supports nullable types.
</blockquote></details>

It's .NET 7.3 - I can show you what I am seeing.


<!-- Sent from Reviewable.io -->

2024-01-23 18:24 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEngineTypesController.cs` line 64 at r5](https://reviewable.io/reviews/sillsdev/serval/283#-NonFjVgBd8LBXuc23Dr:-NorZJgh4g_7LQN8X5up:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/780f5fcb9cbc8db811eef63578f14d01d4ec1611/src/Serval.Translation/Controllers/TranslationEngineTypesController.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `language` like everything else.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-23 22:47 UTC, ddaspit reviewed
> Reviewed 11 of 11 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 7 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 33 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosT3KgELVvJDfYvV7O:-NosT3KgELVvJDfYvV7P:b-er7gvn) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L33)):*
> ```Smalltalk
>     {
>         get => _type;
>         set { _type = Engine.ToPascalCase(value); }
> ```

It is not the responsibility of DTOs to convert to pascal case. DTOs typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
___
*[`src/Serval.Translation/Models/Engine.cs` line 14 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVAiWD83VBscvi9Iu:-NosVAiWD83VBscvi9Iv:b-v1qp0n) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Engine.cs#L14)):*
> ```Smalltalk
>     {
>         get => _type;
>         set { _type = ToPascalCase(value); }
> ```

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
___
*[`src/Serval.Translation/Models/Engine.cs` line 29 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosUpsgAwSKABT9QQtW:-NosUpsgAwSKABT9QQtX:b1x7ot0) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Engine.cs#L29)):*
> ```Smalltalk
>     private static partial Regex SnakeCaseRegex();
> 
>     public static string ToPascalCase(string name)
> ```

Use the [CaseExtensions](https://github.com/vad3x/case-extensions) library to perform the conversion.
___
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 9 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVNkB6JFsHCk0g3aI:-NosVNkB6JFsHCk0g3aJ:b-v1qp0n) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/LanguageInfo.cs#L9)):*
> ```Smalltalk
>     {
>         get => _engineType;
>         set { _engineType = Engine.ToPascalCase(value); }
> ```

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
___
*[`src/Serval.Translation/Models/Queue.cs` line 7 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVOnY3EalBN8XFiIB:-NosVOnY3EalBN8XFiIC:b-v1qp0n) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Queue.cs#L7)):*
> ```Smalltalk
>     public int Size { get; set; } = default;
>     private string _engineType = default!;
>     public string EngineType
> ```

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
___
*[`src/Serval.Translation/Controllers/TranslationEngineTypesController.cs` line 57 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosU-XD7blVcMhOlq-V:-NosU-XD7blVcMhOlq-W:bnmzuhr) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Controllers/TranslationEngineTypesController.cs#L57)):*
> ```Smalltalk
>     /// * **EngineType**: See above
>     /// * **IsNative**: Whether language is in the base NLLB-200 model as per [this list](https://github.com/facebookresearch/flores/blob/main/nllb_seed/README.md)
>     /// * **InternalCode**: The ISO 639-3 code that the language maps to according to [these rules](https://github.com/sillsdev/serval/wiki/FLORES%E2%80%90200-Language-Code-Resolution-for-NMT-Engine)
> ```

The FLORES-200 codes are not ISO 639-3 codes. They are a combination of ISO 639-3 codes and ISO 15924 codes. They do not conform to any particular standard. Also, this is only applicable to the NMT engine type using NLLB.


<!-- Sent from Reviewable.io -->

2024-01-24 13:17 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEngineTypesController.cs` line 57 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosU-XD7blVcMhOlq-V:-NovbSzg-MHwGwJTmBQR:bq5wuc9) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Controllers/TranslationEngineTypesController.cs#L57)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The FLORES-200 codes are not ISO 639-3 codes. They are a combination of ISO 639-3 codes and ISO 15924 codes. They do not conform to any particular standard. Also, this is only applicable to the NMT engine type using NLLB.
</blockquote></details>

Updated comment.


<!-- Sent from Reviewable.io -->

2024-01-24 13:17 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/Engine.cs` line 14 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVAiWD83VBscvi9Iu:-NovbWR2-Zo_pmBc7mve:b6fih1x) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Engine.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
</blockquote></details>

I'll fix all.


<!-- Sent from Reviewable.io -->

2024-01-24 13:22 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/Engine.cs` line 29 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosUpsgAwSKABT9QQtW:-Novcf4kD_vPtEagpPgC:b-snws76) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Engine.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Use the [CaseExtensions](https://github.com/vad3x/case-extensions) library to perform the conversion.
</blockquote></details>

Done - nice find.


<!-- Sent from Reviewable.io -->

2024-01-24 13:22 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 9 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVNkB6JFsHCk0g3aI:-NovcjsU2ybESA0r6zxf:b8d2z4x) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/LanguageInfo.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
</blockquote></details>

Will fix all.


<!-- Sent from Reviewable.io -->

2024-01-24 13:22 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/Queue.cs` line 7 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVOnY3EalBN8XFiIB:-Novcm4q0ISdzBEo7QrV:b8d2z4x) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/Queue.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It is not the responsibility of models to convert to pascal case. Models typically do not contain any logic. The controller is responsible for interpreting the inputs and mapping them to models that the application/service layer can understand.
</blockquote></details>

Will fix all.


<!-- Sent from Reviewable.io -->

2024-01-24 15:24 UTC, ddaspit reviewed
> Reviewed 11 of 11 files at r7, all commit messages.
> Dismissed @Enkidu93 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 2 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 9 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVNkB6JFsHCk0g3aI:-Now2meG-6_bUA27tyP0:b-3x0ovs) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/LanguageInfo.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Will fix all.
</blockquote></details>

I think you accidentally turned this into a field instead of a property.
___
*[`tests/Serval.Translation.Tests/Services/EngineModelTests.cs` line 0 at r7](https://reviewable.io/reviews/sillsdev/serval/283#-Now30fH1XQf379PisCD:-Now30fH1XQf379PisCE:bgqry29) ([raw file](https://github.com/sillsdev/serval/blob/c38f6e877f0cd06a525cc509abbc92338c52f83f/tests/Serval.Translation.Tests/Services/EngineModelTests.cs#L0)):*
We don't need to unit test a library. You can delete this test fixture.


<!-- Sent from Reviewable.io -->

2024-01-25 22:28 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 8 at r7](https://reviewable.io/reviews/sillsdev/serval/283#-Np1j3Gb4hIQ_ppqlL6_:-Np1j3Gb4hIQ_ppqlL6a:b-8x4ma3) ([raw file](https://github.com/sillsdev/serval/blob/c38f6e877f0cd06a525cc509abbc92338c52f83f/src/Serval.Translation/Models/LanguageInfo.cs#L8)):*
> ```Smalltalk
>     public bool IsNative { get; set; } = default!;
>     public string? InternalCode { get; set; } = default!;
>     public string? Name { get; set; } = default!;
> ```

Is there an actual requirement for the language name from Scripture Forge? If not, we should just remove it. We don't need it and it will only make it more difficult to implement this in future engines.


<!-- Sent from Reviewable.io -->

2024-01-26 18:21 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 9 at r6](https://reviewable.io/reviews/sillsdev/serval/283#-NosVNkB6JFsHCk0g3aI:-Np6-ERTCxoHqKSQIhDX:b6i4sqo) ([raw file](https://github.com/sillsdev/serval/blob/87ff0d6245a43461bb0b7f8de641be174201069d/src/Serval.Translation/Models/LanguageInfo.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think you accidentally turned this into a field instead of a property.
</blockquote></details>

GAAAAAAAHHHHH!  C# has so many subtle things that have big impacts!  Fixed.


<!-- Sent from Reviewable.io -->

2024-01-26 18:26 UTC, johnml1135 commented
*[`src/Serval.Translation/Models/LanguageInfo.cs` line 8 at r7](https://reviewable.io/reviews/sillsdev/serval/283#-Np1j3Gb4hIQ_ppqlL6_:-Np60Op-5euSnAZP3bPe:b-lkgsd5) ([raw file](https://github.com/sillsdev/serval/blob/c38f6e877f0cd06a525cc509abbc92338c52f83f/src/Serval.Translation/Models/LanguageInfo.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there an actual requirement for the language name from Scripture Forge? If not, we should just remove it. We don't need it and it will only make it more difficult to implement this in future engines.
</blockquote></details>

Hmm.  I see what you mean.  I will kill it at the API level but keep the guts of it there.  If we do want it in the future it will be easy to add.  We can also grab data from the ethnologue or similar if needed.


<!-- Sent from Reviewable.io -->

2024-01-26 18:27 UTC, johnml1135 commented
*[`tests/Serval.Translation.Tests/Services/EngineModelTests.cs` line  at r7](https://reviewable.io/reviews/sillsdev/serval/283#-Now30fH1XQf379PisCD:-Np60df21RmnbV4jbwKL:bbvs8f4) ([raw file](https://github.com/sillsdev/serval/blob/c38f6e877f0cd06a525cc509abbc92338c52f83f/tests/Serval.Translation.Tests/Services/EngineModelTests.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need to unit test a library. You can delete this test fixture.
</blockquote></details>

Your right - I forgot that I didn't need this anymore.


<!-- Sent from Reviewable.io -->

2024-01-26 22:29 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283#-:-Np6t0uAEUd-MvIY68IF:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-01-27 14:14 UTC, Enkidu93 approved these changes
> Reviewed 2 of 11 files at r6, 7 of 11 files at r7, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-01-30 14:54 UTC, merged