Add endpoint to return pretanslations as USFM
sillsdev/serval pull request #292
Opened 2024-01-30 22:25 UTC by ddaspit

- add Scripture data file service
- cleanup translation controllers
- cleanup tests
- update test dependencies
- customize NSwag client template to support "text/plain" response

2024-01-31 13:44 UTC, johnml1135 commented
*[`src/Serval.ApiServer/nswag.json` line 26 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUktdfCqF7J75yjaNX:-NpUktdfCqF7J75yjaNY:b8g75fu) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.ApiServer/nswag.json#L26)):*
> ```JSON
>       "configurationClass": null,
>       "generateClientClasses": true,
>       "suppressClientClassesOutput": false,
> ```

What is the reason for these targeted changes?


<!-- Sent from Reviewable.io -->

2024-01-31 13:46 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Templates/Client.Class.ProcessResponse.liquid` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUlFc59sleWYf9rSA8:-NpUlFc6DBxA2T0d31I-:b-jh1iut) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.ApiServer/Templates/Client.Class.ProcessResponse.liquid#L1)):*
> ```Liquid
> {% if response.HasType -%}
> ```

So, you are using https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.ProcessResponse.liquid.  Why did you include it here?  What changes are in here?


<!-- Sent from Reviewable.io -->

2024-01-31 13:49 UTC, johnml1135 commented
*[`src/Serval.Client/Serval.Client.csproj` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUlmka0NsgkDQpLv-g:-NpUlmkbCnJFwVp9qeR_:b8azn3n) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Client/Serval.Client.csproj#L8)):*
> ```XML
> 		<Description>Client classes for Serval.</Description>
> 		<RootNamespace>Serval.Client</RootNamespace>
> 		<NoWarn>8618</NoWarn>
> ```

Was this because of the Nswag client generation?  Won't this be fixed through https://github.com/RicoSuter/NSwag/issues/4704?  Should we make a new issue to track removing this warning?


<!-- Sent from Reviewable.io -->

2024-01-31 13:56 UTC, johnml1135 commented
*[`src/Serval.DataFiles/Controllers/DataFilesController.cs` line 60 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUnVG202FqJ5sp4jzw:-NpUnVG202FqJ5sp4jzx:bbst1r3) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.DataFiles/Controllers/DataFilesController.cs#L60)):*
> ```Smalltalk
>     {
>         DataFile dataFile = await _dataFileService.GetAsync(id, cancellationToken);
>         await AuthorizeAsync(dataFile);
> ```

Nice refactoring!


<!-- Sent from Reviewable.io -->

2024-01-31 14:05 UTC, johnml1135 commented
*[`src/Serval.Shared/Controllers/BadRequestExceptionFilter.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUpBKp4L0y29UFZhvU:-NpUpBKq5fSkPR7vuPZL:b9evlkh) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Controllers/BadRequestExceptionFilter.cs#L7)):*
> ```Smalltalk
>     public override void OnException(ExceptionContext context)
>     {
>         if (context.Exception is InvalidOperationException)
> ```

Is this trying to address https://github.com/sillsdev/serval/issues/288?  BadRequestObjectResult will just return a 400.  That should be ok (enough). 


<!-- Sent from Reviewable.io -->

2024-01-31 14:05 UTC, johnml1135 commented
*[`src/Serval.Shared/Controllers/ErrorResultFilter.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUpiXN6n4xgTPsQT7H:-NpUpiXN6n4xgTPsQT7I:bf77saw) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Controllers/ErrorResultFilter.cs#L1)):*
> ```Smalltalk
> using System.Diagnostics;
> ```

Should this using also be stuffed into globals?


<!-- Sent from Reviewable.io -->

2024-01-31 14:18 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ScriptureDataFileService.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUse44AUS1YGvt5ojJ:-NpUse44AUS1YGvt5ojK:bnyaxzi) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ScriptureDataFileService.cs#L12)):*
> ```Smalltalk
>     {
>         using IZipContainer container = _fileSystem.OpenZipFile(GetFilePath(filename));
>         ZipParatextProjectSettingsParser settingsParser = new(_fileSystem, container);
> ```

This is duplicated code - should (likely) be replaced with `ParseProjectSettings(container)`.


<!-- Sent from Reviewable.io -->

2024-01-31 14:31 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipParatextProjectSettingsParser.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUudYH-Y8eCYetmTJu:-NpUudYH-Y8eCYetmTJv:bc4qcbn) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ZipParatextProjectSettingsParser.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Services;
> 
> public class ZipParatextProjectSettingsParser(IFileSystem fileSystem, IZipContainer projectContainer)
> ```

How is this different or distinct from the Machine ZipParatextProjectSettingsParser.cs?  You appear to be using the IZipContainer and IFileSystem in Serval (as well as the more recent version of C#) which are not available in Machine.  Is there anything else I am missing? 


<!-- Sent from Reviewable.io -->

2024-01-31 14:37 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 107 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUwuF_8oi6MZqIJXHc:-NpUwuF_8oi6MZqIJXHd:bzbp9wz) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L107)):*
> ```Smalltalk
>     /// <response code="403">The authenticated client cannot perform the operation or does not own the translation engine</response>
>     /// <response code="404">The engine does not exist</response>
>     /// <response code="503">A necessary service is currently unavailable. Check `/health` for more details. </response>
> ```

So, 422's got coalesced into 400's?


<!-- Sent from Reviewable.io -->

2024-01-31 14:54 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 354 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV-kYi5N-kiA3Jq5Q_:-NpV-kYi5N-kiA3Jq5Qa:b-og9hk1) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L354)):*
> ```Smalltalk
>         Engine engine = await _engineService.GetAsync(id, cancellationToken);
>         await AuthorizeAsync(engine);
>         Corpus corpus = await MapAsync(getDataFileClient, idGenerator.GenerateId(), corpusConfig, cancellationToken);
> ```

So, we don't care if the engine and corpus source languages don't match?  It may be an unnecessary restriction.


<!-- Sent from Reviewable.io -->

2024-01-31 15:06 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 620 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV1Kds8o6KQ0KYKN1k:-NpV1Kds8o6KQ0KYKN1l:b-jthmgj) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L620)):*
> ```Smalltalk
>     /// <param name="cancellationToken"></param>
>     /// <response code="200">The book in USFM format</response>
>     /// <response code="204">The book does not exist in the corpus</response>
> ```

Potential update: The USFM book specified does not exist in the source or target corpus.


<!-- Sent from Reviewable.io -->

2024-01-31 15:15 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEngineTypesController.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV4jyY-iTcRC6TOh2t:-NpV4jyY-iTcRC6TOh2u:b-73m6vj) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEngineTypesController.cs#L6)):*
> ```Smalltalk
> [Route("api/v{version:apiVersion}/translation/engine-types")]
> [OpenApiTag("Translation Engines")]
> public class TranslationEngineTypesController(IAuthorizationService authService, IEngineService engineService)
> ```

Nice catch.


<!-- Sent from Reviewable.io -->

2024-01-31 15:24 UTC, johnml1135 commented
*[`src/Serval.Translation/Services/EngineService.cs` line 259 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV5vS49zqopoZ0iEzV:-NpV5vS49zqopoZ0iEzW:b-6vw6xi) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/EngineService.cs#L259)):*
> ```Smalltalk
>         catch (RpcException re)
>         {
>             if (re.StatusCode is StatusCode.Aborted)
> ```

This is to handle the aborted race condition (if I am correct) so that it will appear to the outside world that the aborted engine is already gone.  Still, I don't see you throwing anything on the CancelBuildAsync in Machine that would catch this code...


<!-- Sent from Reviewable.io -->

2024-01-31 15:26 UTC, johnml1135 commented
*[`src/Serval.Translation/Services/PretranslationService.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV7BHzBYo_k4IyXZOr:-NpV7BHzBYo_k4IyXZOs:bbfdikj) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/PretranslationService.cs#L1)):*
> ```Smalltalk
> using SIL.Machine.Corpora;
> ```

Put in globals.


<!-- Sent from Reviewable.io -->

2024-01-31 15:35 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 613 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV1oC67ELoSk97kigw:-NpV95aa8FC5m6n_rvJD:b7xdayt) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L613)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Potential update: "If the USFM book exists in the target corpus, then the pretranslated text will be inserted into the target book and returned.  If the USFM book does not exist in the target corpus, then the pretranslated text will be inserted into the source book and returned."
</blockquote></details>

Further: "If the USFM book exists in the target corpus, then the pretranslated text will be inserted into **any empty segments in the** the target book and returned. If the USFM book does not exist in the target corpus, then the pretranslated text will be inserted into the source book and returned."


<!-- Sent from Reviewable.io -->

2024-01-31 15:42 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1145 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVAuKWDW8rOQv5xTXr:-NpVAuKWDW8rOQv5xTXs:blxdcbl) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1145)):*
> ```Smalltalk
>             await _env.Builds.InsertAsync(build);
>             _env.NmtClient.CancelBuildAsync(Arg.Any<CancelBuildRequest>(), null, null, Arg.Any<CancellationToken>())
>                 .Returns(CreateAsyncUnaryCall<Empty>(StatusCode.Aborted));
> ```

As per the other comment, when will this exist in real life?


<!-- Sent from Reviewable.io -->

2024-01-31 15:43 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1261 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVB9_r4-8CRQ0nqxLE:-NpVB9_r4-8CRQ0nqxLF:b-rd35zx) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1261)):*
> ```Smalltalk
>     }
> 
>     public async Task GetLanguageInfoAsync()
> ```

Why was the [Test] annotation removed?


<!-- Sent from Reviewable.io -->

2024-01-31 15:45 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1210 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVBTcj0dVRA3wXfOYO:-NpVBTcj0dVRA3wXfOYP:b91kft5) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1210)):*
> ```Smalltalk
>         await _env.Pretranslations.InsertAsync(pret);
> 
>         string usfm = await client.GetPretranslatedUsfmAsync(ECHO_ENGINE1_ID, addedCorpus.Id, "MAT");
> ```

You may do this other places, but we should test stripping all text out and also inserting into a target USFM where only some are added.


<!-- Sent from Reviewable.io -->

2024-01-31 15:47 UTC, johnml1135 commented
*[`tests/Serval.DataFiles.Tests/Services/DataFileServiceTests.cs` line 2 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVBth46IHbhQC9WMxv:-NpVBth46IHbhQC9WMxw:b-hottff) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.DataFiles.Tests/Services/DataFileServiceTests.cs#L2)):*
> ```Smalltalk
> using Serval.Shared.Contracts;
> using Serval.Shared.Utils;
> ```

Shouldn't these be put in the globals?


<!-- Sent from Reviewable.io -->

2024-01-31 15:51 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 104 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVCdf1-M2sJRWeZS4g:-NpVCdf1-M2sJRWeZS4h:b-fddglk) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.E2ETests/ServalApiTests.cs#L104)):*
> ```Smalltalk
>     public async Task NmtBatch()
>     {
>         string engineId = await _helperClient.CreateNewEngine("Nmt", "es", "en", "NMT1");
> ```

So, without ClearEngines, then there will be a glob of engines built up on the k8s services.  Are you addressing this another way?  Is there another concern you are trying to address?


<!-- Sent from Reviewable.io -->

2024-01-31 15:54 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 104 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVCdf1-M2sJRWeZS4g:-NpVDVtFBNEKOjbGAhFm:b-vdv880) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.E2ETests/ServalApiTests.cs#L104)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, without ClearEngines, then there will be a glob of engines built up on the k8s services.  Are you addressing this another way?  Is there another concern you are trying to address?
</blockquote></details>

I see - the disposal methods.


<!-- Sent from Reviewable.io -->

2024-01-31 16:51 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292)* status: 0 of 62 files reviewed, 22 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.ApiServer/nswag.json` line 26 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUktdfCqF7J75yjaNX:-NpVC-AC4mOqy8TcIMUZ:bq4h9wz) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.ApiServer/nswag.json#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What is the reason for these targeted changes?
</blockquote></details>

The new version of NSwag made these changes. I'm assuming that added/removed some properties.
___
*[`src/Serval.ApiServer/Templates/Client.Class.ProcessResponse.liquid` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUlFc59sleWYf9rSA8:-NpVCNJREV8TF2PIiUWB:b-2egab4) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.ApiServer/Templates/Client.Class.ProcessResponse.liquid#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, you are using https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.ProcessResponse.liquid.  Why did you include it here?  What changes are in here?
</blockquote></details>

I added a check for "text/plain" content type. NSwag was not generating the correct code for this case.
___
*[`src/Serval.Client/Serval.Client.csproj` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUlmka0NsgkDQpLv-g:-NpVCl5j4S3yjkzFDN3S:b27xdhu) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Client/Serval.Client.csproj#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Was this because of the Nswag client generation?  Won't this be fixed through https://github.com/RicoSuter/NSwag/issues/4704?  Should we make a new issue to track removing this warning?
</blockquote></details>

Yes, the issue you mentioned is tracking this problem. We can make an issue.
___
*[`src/Serval.Shared/Controllers/BadRequestExceptionFilter.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUpBKp4L0y29UFZhvU:-NpVDNdb6NNnyU23yF2z:br9g8s3) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Controllers/BadRequestExceptionFilter.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is this trying to address https://github.com/sillsdev/serval/issues/288?  BadRequestObjectResult will just return a 400.  That should be ok (enough).
</blockquote></details>

No, this isn't. This was just a refactoring to simplify the controller code.
___
*[`src/Serval.Shared/Services/ScriptureDataFileService.cs` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUtF2P027PK3ZRAhM7:-NpVOcJK6-88AtDOKnnd:b-j4u1f5) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ScriptureDataFileService.cs#L40)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There is some fun and crazy logic here.  Is this different versions of Paratext?  Is there some link or explanation that can be put here to help with breadcrumbs in the future when someone wants to know why these algorithms are in place?
</blockquote></details>

This is based on how Paratext interprets the naming settings internally. Unfortunately, there isn't really any documentation on it anywhere.
___
*[`src/Serval.Shared/Services/ZipParatextProjectSettingsParser.cs` line 3 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUudYH-Y8eCYetmTJu:-NpVDjaUDCffrcNiJJLL:b-4xm3rc) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ZipParatextProjectSettingsParser.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How is this different or distinct from the Machine ZipParatextProjectSettingsParser.cs?  You appear to be using the IZipContainer and IFileSystem in Serval (as well as the more recent version of C#) which are not available in Machine.  Is there anything else I am missing?
</blockquote></details>

You are correct. This is the Serval version of the `ZipParatextProjectSettingsParser`, which uses `IFileSystem` instead of the file system APIs directly.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 354 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV-kYi5N-kiA3Jq5Q_:-NpVDzae4O_sgaJ2ujBm:b-hi9ft7) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L354)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, we don't care if the engine and corpus source languages don't match?  It may be an unnecessary restriction.
</blockquote></details>

Yes, that is correct. Serval was specifically designed to allow for the case where you can include a training corpus that doesn't match the source and target language of the engine. This is to support including related language data in the training corpus.
___
*[`src/Serval.Translation/Services/EngineService.cs` line 259 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV5vS49zqopoZ0iEzV:-NpVO4q59MSWjF2xCnGm:bgmjuvz) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/EngineService.cs#L259)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is to handle the aborted race condition (if I am correct) so that it will appear to the outside world that the aborted engine is already gone.  Still, I don't see you throwing anything on the CancelBuildAsync in Machine that would catch this code...
</blockquote></details>

We should add an issue to Machine to check for this.
___
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1210 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVBTcj0dVRA3wXfOYO:-NpVEyQiDpFDEZDBgY-S:b-tnheum) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1210)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

You may do this other places, but we should test stripping all text out and also inserting into a target USFM where only some are added.
</blockquote></details>

I have tests for this in Machine.
___
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1261 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVB9_r4-8CRQ0nqxLE:-NpVF-z7EN2nG372Rik8:b9s8cpr) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1261)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why was the [Test] annotation removed?
</blockquote></details>

I missed this when I was resolving conflicts.
___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 104 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVCdf1-M2sJRWeZS4g:-NpVPzz5-Lmb15XBIdAT:bn21red) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.E2ETests/ServalApiTests.cs#L104)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I see - the disposal methods.
</blockquote></details>

Yes, that is correct. Although now that I think about it a bit more, it probably makes sense to add this call to the `SetUp` method as well just in case  [...]

2024-01-31 17:33 UTC, johnml1135 commented
ZipParatextProjectSettingsParser.cs is not tested for actual stylesheets and custom.sty - and there are a number of other caes that are not covered as per the coverage reports.





<!-- Sent from Reviewable.io -->

2024-01-31 17:36 UTC, johnml1135 commented
*[`src/Serval.Client/Serval.Client.csproj` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUlmka0NsgkDQpLv-g:-NpVa0wPDemhlRuPJKXB:b-2cele4) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Client/Serval.Client.csproj#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, the issue you mentioned is tracking this problem. We can make an issue.
</blockquote></details>

https://github.com/sillsdev/serval/issues/294


<!-- Sent from Reviewable.io -->

2024-01-31 17:37 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ScriptureDataFileService.cs` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUtF2P027PK3ZRAhM7:-NpVaC4-2-JuC3ETpmU1:bdsne94) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ScriptureDataFileService.cs#L40)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is based on how Paratext interprets the naming settings internally. Unfortunately, there isn't really any documentation on it anywhere.
</blockquote></details>

Is there at least an open source repo that you are pulling from to do this?  Such as "duplicating logic found here..."


<!-- Sent from Reviewable.io -->

2024-01-31 17:42 UTC, johnml1135 commented
*[`src/Serval.Translation/Services/EngineService.cs` line 259 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV5vS49zqopoZ0iEzV:-NpVbQgSDrdvF2oYOCvg:b-nyj5ce) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/EngineService.cs#L259)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should add an issue to Machine to check for this.
</blockquote></details>

https://github.com/sillsdev/machine/issues/162


<!-- Sent from Reviewable.io -->

2024-01-31 17:43 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1210 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVBTcj0dVRA3wXfOYO:-NpVbUoTAvZv1rGSa_tR:b3x2hkk) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1210)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I have tests for this in Machine.
</blockquote></details>

That "should" be ok...


<!-- Sent from Reviewable.io -->

2024-01-31 17:44 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 104 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVCdf1-M2sJRWeZS4g:-NpVbmCl-wRbjkKSRPMR:bd6ogzl) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.E2ETests/ServalApiTests.cs#L104)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, that is correct. Although now that I think about it a bit more, it probably makes sense to add this call to the `SetUp` method as well just in case a test crashed and never cleaned up the engines.
</blockquote></details>

That sounds like a good path forward.


<!-- Sent from Reviewable.io -->

2024-01-31 17:45 UTC, johnml1135 requested changes
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292)* status: all files reviewed, 14 unresolved discussions (waiting on @ddaspit)

___
*[`src/Serval.Shared/Controllers/ForbiddenExceptionFilter.cs` line 10 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUpote23uqiKYa5MTv:-NpUpote23uqiKYa5MTw:b-pc1rdr) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Controllers/ForbiddenExceptionFilter.cs#L10)):*
> ```Smalltalk
>         {
>             context.Result = new ForbidResult();
>             context.ExceptionHandled = true;
> ```

I see - for the refactoring.  I like it.


<!-- Sent from Reviewable.io -->

2024-01-31 22:57 UTC, ddaspit reviewed
I moved some of the Paratext project settings code over to the Machine library.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292#-:-NpWjBKK9CXjr8scTj5t:bdc7e33)* status: 48 of 63 files reviewed, 13 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.DataFiles/Consumers/GetDataFileConsumer.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUm4o10YIz-r-K5Lse:-NpWQh8267-K6S2rDAr8:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.DataFiles/Consumers/GetDataFileConsumer.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is unneeded.
</blockquote></details>

Done.
___
*[`src/Serval.Shared/Controllers/ErrorResultFilter.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUpiXN6n4xgTPsQT7H:-NpWQsnmD7lTq5tth4nF:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Controllers/ErrorResultFilter.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should this using also be stuffed into globals?
</blockquote></details>

Done.
___
*[`src/Serval.Shared/Services/ScriptureDataFileService.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUse44AUS1YGvt5ojJ:-NpWRCKI6iMQXdfUBUF_:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ScriptureDataFileService.cs#L12)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is duplicated code - should (likely) be replaced with `ParseProjectSettings(container)`.
</blockquote></details>

Done.
___
*[`src/Serval.Shared/Services/ScriptureDataFileService.cs` line 40 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUtF2P027PK3ZRAhM7:-NpWRHR8Ch6cLBZ3sMtA:bhow556) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Shared/Services/ScriptureDataFileService.cs#L40)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is there at least an open source repo that you are pulling from to do this?  Such as "duplicating logic found here..."
</blockquote></details>

No, Paratext is not open source. I think I might move this code to Machine.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 107 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpUwuF_8oi6MZqIJXHc:-NpWTCZYA7DCAxNj1gT-:b1cwwol) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L107)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, 422's got coalesced into 400's?
</blockquote></details>

I couldn't find a case where the 422 would occur.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 613 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV1oC67ELoSk97kigw:-NpWV_oA5X88DCRgW7BA:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L613)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Further: "If the USFM book exists in the target corpus, then the pretranslated text will be inserted into **any empty segments in the** the target book and returned. If the USFM book does not exist in the target corpus, then the pretranslated text will be inserted into the source book and returned."
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 620 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV1Kds8o6KQ0KYKN1k:-NpWVa6j-j7rVEk3JSSp:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L620)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Potential update: The USFM book specified does not exist in the source or target corpus.
</blockquote></details>

Done.
___
*[`src/Serval.Translation/Services/PretranslationService.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV7BHzBYo_k4IyXZOr:-NpWXkb1-SzzbTRQFVdQ:b512nx5) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/PretranslationService.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Put in globals.
</blockquote></details>

That causes naming collisions in other files.
___
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1145 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVAuKWDW8rOQv5xTXr:-NpWXr4D2P-ZsBOLIxp2:b-w29p3q) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1145)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

As per the other comment, when will this exist in real life?
</blockquote></details>

As I said elsewhere, we need to add a check in Machine.
___
*[`tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 1261 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVB9_r4-8CRQ0nqxLE:-NpWY70VBez8jYDAf7vY:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L1261)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I missed this when I was resolving conflicts.
</blockquote></details>

Done
___
*[`tests/Serval.DataFiles.Tests/Services/DataFileServiceTests.cs` line 2 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVBth46IHbhQC9WMxv:-NpWYHy-5N_ylrjedVTV:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.DataFiles.Tests/Services/DataFileServiceTests.cs#L2)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Shouldn't these be put in the globals?
</blockquote></details>

Done.
___
*[`tests/Serval.E2ETests/ServalApiTests.cs` line 104 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpVCdf1-M2sJRWeZS4g:-NpWZ2JX9Am1RqWHfrhb:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/tests/Serval.E2ETests/ServalApiTests.cs#L104)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

That sounds like a good path forward.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-01 14:59 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 613 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV1oC67ELoSk97kigw:-Np_AISxB3BuqXUiRg0B:b6djuns) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L613)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm. one more edit... "will be inserted into **an empty template created from the source USFM** book and returned."  What do you think?


<!-- Sent from Reviewable.io -->

2024-02-01 15:00 UTC, johnml1135 commented
*[`src/Serval.Translation/Services/PretranslationService.cs` line 1 at r1](https://reviewable.io/reviews/sillsdev/serval/292#-NpV7BHzBYo_k4IyXZOr:-Np_AkBn5BAaiRrNbZsD:b-vvla80) ([raw file](https://github.com/sillsdev/serval/blob/ed75d04945a82d8e2df7d4f76ffbc597d8c27991/src/Serval.Translation/Services/PretranslationService.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

That causes naming collisions in other files.
</blockquote></details>

Good enough.


<!-- Sent from Reviewable.io -->

2024-02-01 15:05 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 49 at r2](https://reviewable.io/reviews/sillsdev/serval/292#-Np_Bs1bEhgfppCMwcZj:-Np_Bs1bEhgfppCMwcZk:b-yjl3sv) ([raw file](https://github.com/sillsdev/serval/blob/1c38f0a1b699294f67b17f62f7872040ce926e43/tests/Serval.E2ETests/ServalClientHelper.cs#L49)):*
> ```Smalltalk
>             throw new InvalidOperationException("The environment variable SERVAL_CLIENT_SECRET is not set.");
> 
>         string authToken = await GetAuth0AuthenticationAsync(authUrl, _audience, clientId, clientSecret);
> ```

The only thing about this is that we are refreshing the token before every single test - I would think that we would want to just get the token and ENV variables once and then clear the engines before/after every test.


<!-- Sent from Reviewable.io -->

2024-02-01 15:05 UTC, johnml1135 reviewed
> Reviewed 15 of 15 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-02-01 18:40 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 49 at r2](https://reviewable.io/reviews/sillsdev/serval/292#-Np_Bs1bEhgfppCMwcZj:-Np_yG-zAkiB5gggzHlM:b3f1ugf) ([raw file](https://github.com/sillsdev/serval/blob/1c38f0a1b699294f67b17f62f7872040ce926e43/tests/Serval.E2ETests/ServalClientHelper.cs#L49)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We were already getting the auth token before every test. The client helper was created in the setup method and the setup method is run before every test.
</blockquote></details>

Ok - if it works, it works.


<!-- Sent from Reviewable.io -->

2024-02-01 18:41 UTC, johnml1135 commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->

2024-02-01 18:41 UTC, johnml1135 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-02-01 20:16 UTC, johnml1135 approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/292)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-02-01 20:16 UTC, merged