Nmt download
sillsdev/serval pull request #300
Opened 2024-02-05 21:03 UTC by johnml1135

Fixes https://github.com/sillsdev/serval/issues/268

2024-02-05 22:15 UTC, ddaspit requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 11 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 15 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvDGbz6LtnQW79ID75:-NpvDGbz6LtnQW79ID76:bvcuxb1) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L15)):*
> ```proto
>     rpc StartBuild(StartBuildRequest) returns (google.protobuf.Empty);
>     rpc CancelBuild(CancelBuildRequest) returns (google.protobuf.Empty);
>     rpc GetModelPresignedUrl(GetModelPresignedUrlRequest) returns (GetModelPresignedUrlResponse);
> ```

I wouldn't use `Presigned` in the name. That term is specific to S3. I would call this something like `GetModelDownloadUrl` or just `GetModelUrl`. 
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 84 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvIQhz2Purl_ouawlR:-NpvIQhz2Purl_ouawlS:bkw1jbd) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L84)):*
> ```proto
> 
> message GetModelPresignedUrlResponse {
>     string PresignedUrl = 1;
> ```

These fields should be snake case.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 85 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvI_TlBaOdgbmmmJAz:-NpvI_TlBaOdgbmmmJB-:b-e3svwu) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L85)):*
> ```proto
> message GetModelPresignedUrlResponse {
>     string PresignedUrl = 1;
>     int32 BuildRevision = 2;
> ```

This should be `model_revision`.
___
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 86 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvK9FVBYexf3wMGECH:-NpvK9FVBYexf3wMGECI:b-at5k9z) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L86)):*
> ```proto
>     string PresignedUrl = 1;
>     int32 BuildRevision = 2;
>     string UrlExpirationTime = 3;
> ```

I believe that Protobuf has `Timestamp` and `DateTime` types. 
___
*[`src/Serval.Translation/Contracts/ModelPresignedUrlDto.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvJZmk2gr4m5RMY-3w:-NpvJZmk2gr4m5RMY-3x:b-a7rxlx) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Contracts/ModelPresignedUrlDto.cs#L7)):*
> ```Smalltalk
>     public string PresignedUrl { get; set; } = default!;
>     public string BuildRevision { get; set; } = default!;
>     public string UrlExpirationTime { get; set; } = default!;
> ```

Just `ExpirationTime` should be sufficient. Also, what is this? It is a specific date/time. If so, you should use the appropriate type, such as `DateTime`.
___
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvEFEUESbaEkHYsoiu:-NpvEFEUESbaEkHYsoiv:bb75sc5) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L34)):*
> ```Smalltalk
>     /// </summary>
>     [JsonProperty(Required = Required.Always)]
>     public bool IsModelRetrievable { get; set; } = false;
> ```

We want to use the same property to enable live inferencing, so the name should be more generalized. Maybe `IsModelPersisted` or `SaveModel`.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 906 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvIowL5EUdmNLAU7aW:-NpvIowL5EUdmNLAU7aX:b58rjya) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L906)):*
> ```Smalltalk
>     /// <param name="id">The translation engine id</param>
>     /// <param name="cancellationToken"></param>
>     /// <response code="200">The build job was cancelled successfully.</response>
> ```

This is incorrect.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 920 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvGhWd6hYH6z9D_i3w:-NpvGhWd6hYH6z9D_i3x:b-8xwlvt) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L920)):*
> ```Smalltalk
>     [ProducesResponseType(typeof(void), StatusCodes.Status405MethodNotAllowed)]
>     [ProducesResponseType(typeof(void), StatusCodes.Status503ServiceUnavailable)]
>     public async Task<ActionResult<ModelPresignedUrlDto>> DownloadModelAsync(
> ```

This should be `GetModelDownloadUrlAsync` or `GetModelUrlAsync`, since it isn't actually downloading the model.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-NpvH3IH7pdkI4r1-FJz:bhw1y04) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
> ```Smalltalk
>         try
>         {
>             build.Options = Newtonsoft.Json.JsonConvert.DeserializeObject<IDictionary<string, object>>(
> ```

Is there any way to get this to work using `System.Text.Json` instead? 
___
*[`src/Serval.Translation/Services/EngineService.cs` line 281 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHizh6pttcKlGm0ia:-NpvHizh6pttcKlGm0ib:b422tie) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Services/EngineService.cs#L281)):*
> ```Smalltalk
>             cancellationToken: cancellationToken
>         );
>         return new ModelPresignedUrlDto
> ```

DTOs shouldn't be used in the service layer. The controllers are responsible for mapping between the service layer models and DTOs.
___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-NpvHNiS7qgjnI8-IapL:b-qxmq1k) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
> ```Smalltalk
>     public async ValueTask DisposeAsync()
>     {
>         await ClearEnginesAsync();
> ```

Why did you remove this? It is a good idea to clean up after every test.


<!-- Sent from Reviewable.io -->

2024-02-06 17:18 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 15 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvDGbz6LtnQW79ID75:-NpzQC1D8njQQdeLLJ7k:bha9gsq) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I wouldn't use `Presigned` in the name. That term is specific to S3. I would call this something like `GetModelDownloadUrl` or just `GetModelUrl`.
</blockquote></details>

GetModelDownloadUrl - explicit that it can be used for external clients.


<!-- Sent from Reviewable.io -->

2024-02-06 17:39 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 86 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvK9FVBYexf3wMGECH:-NpzV5ur0AbWnigPSFeI:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L86)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I believe that Protobuf has `Timestamp` and `DateTime` types.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 17:41 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/ModelPresignedUrlDto.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvJZmk2gr4m5RMY-3w:-NpzV8J7CudGHGeH-L7U:b-2fmldc) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Contracts/ModelPresignedUrlDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Just `ExpirationTime` should be sufficient. Also, what is this? It is a specific date/time. If so, you should use the appropriate type, such as `DateTime`.
</blockquote></details>

Changed to `ExpiresAt` and a DateTime.


<!-- Sent from Reviewable.io -->

2024-02-06 17:41 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvEFEUESbaEkHYsoiu:-NpzVcuV7CdO-XLjVEBp:b-2v2g5t) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We want to use the same property to enable live inferencing, so the name should be more generalized. Maybe `IsModelPersisted` or `SaveModel`.
</blockquote></details>

I like ``IsModelPersisted`.


<!-- Sent from Reviewable.io -->

2024-02-06 17:43 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 906 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvIowL5EUdmNLAU7aW:-NpzW6kD6n4fo0Sq73bo:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L906)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is incorrect.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 17:44 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 920 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvGhWd6hYH6z9D_i3w:-NpzWMu91fd2ytQdmW5J:bll9zc4) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L920)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `GetModelDownloadUrlAsync` or `GetModelUrlAsync`, since it isn't actually downloading the model.
</blockquote></details>

and what about changing the endpoint name to `model-url`?


<!-- Sent from Reviewable.io -->

2024-02-06 17:48 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-NpzWkIN3XpXyn6k1wQm:bx48l4o) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is there any way to get this to work using `System.Text.Json` instead?
</blockquote></details>

I couldn't find a way - I had to rip a custom `DictionaryJsonConverter.cs` as well.  It's because nested options don't currently work.  It's not needed for this anymore (because we aren't using `buildOptions`, but it is needed.  Is there a reason you don't want to use Newtonsoft?  It's used in quite a few places already.


<!-- Sent from Reviewable.io -->

2024-02-06 17:52 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 11 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 920 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvGhWd6hYH6z9D_i3w:-NpzWc7wEoWQTyv7GWbg:b-ubfxs6) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L920)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

and what about changing the endpoint name to `model-url`?
</blockquote></details>

We should just be consistent everywhere. If we use `GetModelDownloadUrlAsync`, then we should call it `model-download-url`. If we use `GetModelUrlAsync`, then we should call it `model-url`. I would lean towards `model-download-url`, since it is more explicit. Also, this should be a GET endopoint.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-NpzXlKY3qaSq7uLyo9S:bvx7e61) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I couldn't find a way - I had to rip a custom `DictionaryJsonConverter.cs` as well.  It's because nested options don't currently work.  It's not needed for this anymore (because we aren't using `buildOptions`, but it is needed.  Is there a reason you don't want to use Newtonsoft?  It's used in quite a few places already.
</blockquote></details>

Instead of using two JSON libraries, I would like to move us to only using the one built-in to .NET. Using two JSON libraries causes confusion.


<!-- Sent from Reviewable.io -->

2024-02-06 18:09 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 920 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvGhWd6hYH6z9D_i3w:-NpzazVLA1uKIQxXbjh7:b-la6lbh) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L920)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should just be consistent everywhere. If we use `GetModelDownloadUrlAsync`, then we should call it `model-download-url`. If we use `GetModelUrlAsync`, then we should call it `model-url`. I would lean towards `model-download-url`, since it is more explicit. Also, this should be a GET endopoint.
</blockquote></details>

model-download-url


<!-- Sent from Reviewable.io -->

2024-02-06 18:09 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-Npzb45L8emlg-rmOMdn:bfvx42n) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Instead of using two JSON libraries, I would like to move us to only using the one built-in to .NET. Using two JSON libraries causes confusion.
</blockquote></details>

What do you want to do now?  make an issue and try to clean it up later?


<!-- Sent from Reviewable.io -->

2024-02-06 18:11 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-NpzbF9S5Kzgbe_EjBZk:b-gpbu94) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why did you remove this? It is a good idea to clean up after every test.
</blockquote></details>

I sometimes want to interact with the model and data after the test has completed via swagger.  Having the data persist after the test is done accomplishes this.


<!-- Sent from Reviewable.io -->

2024-02-06 18:11 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 84 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvIQhz2Purl_ouawlR:-NpzQk6yCHMtG4cESU8J:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L84)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These fields should be snake case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 18:11 UTC, johnml1135 commented
*[`src/Serval.Grpc/Protos/serval/translation/v1/engine.proto` line 85 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvI_TlBaOdgbmmmJAz:-NpzQlHE4dJ1bax5NZXF:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Grpc/Protos/serval/translation/v1/engine.proto#L85)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be `model_revision`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-06 19:02 UTC, ddaspit reviewed
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/300#-Npzjgza1oaeBoew1dCZ:-Npzjgza1oaeBoew1dC_:b-cfe1i) ([raw file](https://github.com/sillsdev/serval/blob/24fb43b17f0a576b194a89ed60b1a9ce9c54be38/src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs#L6)):*
> ```Smalltalk
> {
>     public string Url { get; set; } = default!;
>     public string ModelRevision { get; set; } = default!;
> ```

This should be an `int`, so that it is consistent with the `TranslationEngineDto`.
___
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-Npzmlld5cWlZgWLEy5p:b-draydp) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What do you want to do now?  make an issue and try to clean it up later?
</blockquote></details>

We should be able to update the `ObjectToInferredTypesConverter` to support objects and arrays. You can either revert this and I can create a separate PR to specifically fix this issue or I can fix it in this PR.
___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-Npzjbc3CWYGiPWROn7s:ba6fv3t) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I sometimes want to interact with the model and data after the test has completed via swagger.  Having the data persist after the test is done accomplishes this.
</blockquote></details>

Is that for debugging purposes?


<!-- Sent from Reviewable.io -->

2024-02-06 19:50 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs` line 6 at r2](https://reviewable.io/reviews/sillsdev/serval/300#-Npzjgza1oaeBoew1dCZ:-NpzyAlDACk4fU6r-C1E:b32wtd) ([raw file](https://github.com/sillsdev/serval/blob/24fb43b17f0a576b194a89ed60b1a9ce9c54be38/src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be an `int`, so that it is consistent with the `TranslationEngineDto`.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2024-02-06 19:53 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-Npzyssc3jRdVkzyiMNp:bt2gome) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should be able to update the `ObjectToInferredTypesConverter` to support objects and arrays. You can either revert this and I can create a separate PR to specifically fix this issue or I can fix it in this PR.
</blockquote></details>

I'll take a shot at it - and try to test it.


<!-- Sent from Reviewable.io -->

2024-02-06 19:58 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-NpzzrihB-nE6gMdjC_8:b19vjc) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is that for debugging purposes?
</blockquote></details>

Yes, for debugging.  Should we gate it with `isDevelopment`? 


<!-- Sent from Reviewable.io -->

2024-02-06 20:53 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-Nq-B_p_Cch_jxRXMBvo:b-2uk4wc) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Yes, for debugging.  Should we gate it with `isDevelopment`?
</blockquote></details>

Yeah, that's a good idea.


<!-- Sent from Reviewable.io -->

2024-02-07 03:01 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 304 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvHNiS7qgjnI8-IapK:-Nq0Vf2T0VTVdqeJtViN:bkelzdi) ([raw file](https://github.com/sillsdev/serval/blob/7231a27c3c07ec4b95edfa9fd4fd9b87210ba04a/tests/Serval.E2ETests/ServalClientHelper.cs#L304)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yeah, that's a good idea.
</blockquote></details>

What do you think?  These are E2E tests - the environment is really about the target.  Moreover, I use "Staging" for all of my development work with docker compose.


<!-- Sent from Reviewable.io -->

2024-02-07 13:19 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 308 at r4](https://reviewable.io/reviews/sillsdev/serval/300#-Nq2iIxAA1laD6XPkAb-:-Nq2iIxAA1laD6XPkAb0:b-kst86n) ([raw file](https://github.com/sillsdev/serval/blob/5bf08b6f809c4723ed2fd941ea1cb7e5d5ad1f43/tests/Serval.E2ETests/ServalClientHelper.cs#L308)):*
> ```Smalltalk
>     public async ValueTask DisposeAsync()
>     {
>         DeploymentInfo? result = await StatusClient.GetDeploymentInfoAsync();
> ```

THis is not good - I will redo with isdevelopment - that is what we want anyway. 


<!-- Sent from Reviewable.io -->

2024-02-07 13:42 UTC, johnml1135 commented
*[`tests/Serval.E2ETests/ServalClientHelper.cs` line 308 at r4](https://reviewable.io/reviews/sillsdev/serval/300#-Nq2iIxAA1laD6XPkAb-:-Nq2n_ub6rCA8hGhN92A:b5oh50k) ([raw file](https://github.com/sillsdev/serval/blob/5bf08b6f809c4723ed2fd941ea1cb7e5d5ad1f43/tests/Serval.E2ETests/ServalClientHelper.cs#L308)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

THis is not good - I will redo with isdevelopment - that is what we want anyway.
</blockquote></details>

This is the best I can do.  Dependency injection in testing doesn't work well.


<!-- Sent from Reviewable.io -->

2024-02-07 18:14 UTC, Enkidu93 commented
I haven't been following this PR very closely along the way. I would have expected changes to `EngineServiceTests.cs` as well as (judging from the codecov report) a parsing failure case test in the `TranslationEngineTests.cs`. Is there a reason that's not the case? Are we just pushing that down the road? Or was it deemed minor enough?





<!-- Sent from Reviewable.io -->

2024-02-07 18:34 UTC, johnml1135 commented
*[`src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1032 at r1](https://reviewable.io/reviews/sillsdev/serval/300#-NpvH3IH7pdkI4r1-FJy:-Nq3qNnz-ZoyjUjqnrYO:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/f07ef1d5a1a94642f048dbd957853dd248cf43c6/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1032)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I'll take a shot at it - and try to test it.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-07 18:40 UTC, johnml1135 commented
GetModelDownloadUrl is tested in E2E tests.  I'll add a bad parsing case.





<!-- Sent from Reviewable.io -->

2024-02-07 19:14 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r6, 17 of 17 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300#-:-Nq3zbmK7if1kjJ8FNb0:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-02-07 19:49 UTC, ddaspit requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 34 at r9](https://reviewable.io/reviews/sillsdev/serval/300#-Nq46Nyk3yWRiZNqYJdN:-Nq46Nyk3yWRiZNqYJdO:b-2qq1o2) ([raw file](https://github.com/sillsdev/serval/blob/119e88d2db0bf8228f8ffa23319bc70a70ce0c01/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L34)):*
> ```Smalltalk
>     /// </summary>
>     [JsonProperty(Required = Required.Always)]
>     public bool IsModelPersisted { get; set; } = false;
> ```

This should be optional, so that each engine can determine the default.


<!-- Sent from Reviewable.io -->

2024-02-07 20:05 UTC, johnml1135 reviewed
Actually, I don't know if there is an easy way to add a bad Engine service test...

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300#-:-Nq3toqF2XoL59C0nrZh:be2vcmc)* status: 17 of 22 files reviewed, 1 unresolved discussion (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-02-07 21:01 UTC, ddaspit requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs` line 7 at r10](https://reviewable.io/reviews/sillsdev/serval/300#-Nq4MWC3C27visKMnffP:-Nq4MWC3C27visKMnffQ:b-jyxfsk) ([raw file](https://github.com/sillsdev/serval/blob/8b76e264675aa592e80f7a2d48f5f9f1398c1b03/src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs#L7)):*
> ```Smalltalk
>     public string Url { get; set; } = default!;
>     public int ModelRevision { get; set; } = default!;
>     public string ExpiresAt { get; set; } = default!;
> ```

We are already using `DateTime` in the `TranslationBuildDto`. I don't want to return two different DateTime formats.
___
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 34 at r9](https://reviewable.io/reviews/sillsdev/serval/300#-Nq46Nyk3yWRiZNqYJdN:-Nq4MnbK0pilrnyTgjtm:bq6djc1) ([raw file](https://github.com/sillsdev/serval/blob/119e88d2db0bf8228f8ffa23319bc70a70ce0c01/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L34)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Everywhere?  Optional means `bool?`?  Is there another parameter that follows a similar pattern?
</blockquote></details>

Yes, it should probably be optional everywhere in Serval. You make it optional by making it nullable. There are many other optional parameters.


<!-- Sent from Reviewable.io -->

2024-02-07 21:17 UTC, johnml1135 commented
Added some more testing.





<!-- Sent from Reviewable.io -->

2024-02-07 21:19 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs` line 7 at r10](https://reviewable.io/reviews/sillsdev/serval/300#-Nq4MWC3C27visKMnffP:-Nq4R8-h3WTqxYdzrgQT:byebuvo) ([raw file](https://github.com/sillsdev/serval/blob/8b76e264675aa592e80f7a2d48f5f9f1398c1b03/src/Serval.Translation/Contracts/ModelDownloadUrlDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We are already using `DateTime` in the `TranslationBuildDto`. I don't want to return two different DateTime formats.
</blockquote></details>

The DateTimeOffset thing was confusing me: https://stackoverflow.com/questions/72261151/does-nswag-convert-datetime-to-datetimeoffset-in-the-timezone-the-server-is-in.  I'll convert back to DateTime.


<!-- Sent from Reviewable.io -->

2024-02-07 21:37 UTC, johnml1135 commented
*[`src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs` line 34 at r9](https://reviewable.io/reviews/sillsdev/serval/300#-Nq46Nyk3yWRiZNqYJdN:-Nq4VGz-2UhLP50GBbOT:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/119e88d2db0bf8228f8ffa23319bc70a70ce0c01/src/Serval.Translation/Contracts/TranslationEngineConfigDto.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, it should probably be optional everywhere in Serval. You make it optional by making it nullable. There are many other optional parameters.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-02-07 22:20 UTC, ddaspit reviewed
> Reviewed 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 140 at r11](https://reviewable.io/reviews/sillsdev/serval/300#-Nq4drLM9FcMOvCddpri:-Nq4drLM9FcMOvCddprj:bbe6c0a) ([raw file](https://github.com/sillsdev/serval/blob/a70a22d9fc345c1e73987a0d14f5b7182d057c10/src/Serval.Translation/Services/EngineService.cs#L140)):*
> ```Smalltalk
>             if (engine.Name is not null)
>                 request.EngineName = engine.Name;
>             await client.CreateAsync(request, cancellationToken: cancellationToken);
> ```

Do you think it makes sense to return the default value for `IsModelPersisted` from the engine so we can set it on the model? Or should we leave it as null if it isn't set.


<!-- Sent from Reviewable.io -->

2024-02-08 17:59 UTC, johnml1135 commented
*[`src/Serval.Translation/Services/EngineService.cs` line 140 at r11](https://reviewable.io/reviews/sillsdev/serval/300#-Nq4drLM9FcMOvCddpri:-Nq8rlL4EPSHEQ8RFcAv:b-hf4i6i) ([raw file](https://github.com/sillsdev/serval/blob/a70a22d9fc345c1e73987a0d14f5b7182d057c10/src/Serval.Translation/Services/EngineService.cs#L140)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do you think it makes sense to return the default value for `IsModelPersisted` from the engine so we can set it on the model? Or should we leave it as null if it isn't set.
</blockquote></details>

keep it nullable for backwards compatibility?


<!-- Sent from Reviewable.io -->

2024-02-09 18:45 UTC, ddaspit reviewed
> Reviewed 1 of 3 files at r12, 7 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 140 at r13](https://reviewable.io/reviews/sillsdev/serval/300#-NqE6jC6Dr0P9CfCz_0s:-NqE6jC6Dr0P9CfCz_0t:bnnjcx9) ([raw file](https://github.com/sillsdev/serval/blob/a1b23b0fe8f96593647a15df642f9067b39369a6/src/Serval.Translation/Services/EngineService.cs#L140)):*
> ```Smalltalk
>         // IsModelPersisted may be updated by the engine with the respective default.
>         engine.IsModelPersisted = createResponse.IsModelPersisted;
>         await Entities.InsertAsync(engine, cancellationToken);
> ```

I was purposefully inserting the engine model in Mongo before creating the engine. There are a couple of reasons:
1. I don't want to get into a state where Machine has created an engine that Serval doesn't know about. It will be difficult to clean up properly. This can occur if you create the Machine engine before you insert the engine model in Mongo.
2. It is possible (although I don't think it currently happens) for the Machine engine to callback to Serval referencing an engine that hasn't been created yet.

After the `try...catch`, you should update the `IsModelPersisted` property.
```
if (engine.IsModelPersisted is null)
    await Entities.UpdateAsync(engine, u => u.Set(e => e.IsModelPersisted, createResponse.IsModelPersisted, cancellationToken: cancellationToken));
```

You should also return the engine model, so that the updated model can be returned as the response.


<!-- Sent from Reviewable.io -->

2024-02-09 18:57 UTC, johnml1135 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[`src/Serval.Translation/Services/EngineService.cs` line 140 at r13](https://reviewable.io/reviews/sillsdev/serval/300#-NqE6jC6Dr0P9CfCz_0s:-NqEDjy18v6Ex9DY1-Ai:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a1b23b0fe8f96593647a15df642f9067b39369a6/src/Serval.Translation/Services/EngineService.cs#L140)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I was purposefully inserting the engine model in Mongo before creating the engine. There are a couple of reasons:
1. I don't want to get into a state where Machine has created an engine that Serval doesn't know about. It will be difficult to clean up properly. This can occur if you create the Machine engine before you insert the engine model in Mongo.
2. It is possible (although I don't think it currently happens) for the Machine engine to callback to Serval referencing an engine that hasn't been created yet.

After the `try...catch`, you should update the `IsModelPersisted` property.
```
if (engine.IsModelPersisted is null)
    await Entities.UpdateAsync(engine, u => u.Set(e => e.IsModelPersisted, createResponse.IsModelPersisted, cancellationToken: cancellationToken));
```

You should also return the engine model, so that the updated model can be returned as the response.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-09 19:00 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/300#-:-NqEEXZG2D5eXur3qyBO:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-02-09 20:03 UTC, merged