Update .editorconfig with many changes
sillsdev/serval pull request #312
Opened 2024-02-12 19:36 UTC by johnml1135

* Enforced naming conventions
* ConfigureAwait for DataAccess (only)
* Always use primary constructor and other .NET 8 conventions
* Fix all warnings from updated editorconfig

2024-02-13 13:58 UTC, Enkidu93 requested changes
Did you get this configuration from somewhere? Was it recommended by someone? Or did you compile these specific configurations yourself?

Also, I imagine Damien will be more opinionated, so I'd definitely wait to get his feedback. I don't have many .NET-specific coding opinions.

> Reviewed 89 of 89 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312#-:-NqXj6sU9ApDYIZQ4XR4:b-r27egj)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval.Grpc/Utils/WriteGrpcHealthCheckResponse.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/serval/312#-NqXg0G-3H4PkNmaJcp0:-NqXg0G-3H4PkNmaJcp1:b-s3scdz) ([raw file](https://github.com/sillsdev/serval/blob/95e0586e9789dc7082273d591ca694b9ec96f05b/src/Serval.Grpc/Utils/WriteGrpcHealthCheckResponse.cs#L18)):*
> ```Smalltalk
>             if ((entry.Value.Exception?.ToString() ?? "") != "")
>             {
>                 if (healthCheckResultException is null)
> ```

Is this really best practice? I suppose this code is unlikely to be extended very much. I was taught to never use if without braces in c-inspired languages except perhaps in a freestanding, single-line (of course) if-statement - and absolutely never in nested statements. Without braces, it's easy to add cases or more lines of condition-guarded logic incorrectly. The auto-formatting helps, but even so. Like I said, maybe in this function it's not an issue, but I'm not sure I'd like warnings attached to all of my if statements which I might leave with braces intentionally for extensibility/readability. 
___
*[`tests/Serval.ApiServer.IntegrationTests/DataFilesTests.cs` line 70 at r1](https://reviewable.io/reviews/sillsdev/serval/312#-NqXiCKt6NytJwUn6ZE4:-NqXiCKt6NytJwUn6ZE5:b-ykd50g) ([raw file](https://github.com/sillsdev/serval/blob/95e0586e9789dc7082273d591ca694b9ec96f05b/tests/Serval.ApiServer.IntegrationTests/DataFilesTests.cs#L70)):*
> ```Smalltalk
>                 goto case 403;
>             case 403:
>                 ServalApiException? ex = Assert.ThrowsAsync<ServalApiException>(async () =>
> ```

I do think these are fairly clear with 'var', but I suppose it doesn't hurt. Maybe some of these settings should be configured differently for tests?


<!-- Sent from Reviewable.io -->

2024-02-13 15:27 UTC, johnml1135 commented
I compiled it from editorconfigs from aspdotnet and a few other areas.  It includes:
* ASPDOTNET variable naming
* fairly stringent style guidelines - there is only one way to do it
* No single-line null throwing

The goal is to have the review process take less time overall because these issues are auto-resolved.





<!-- Sent from Reviewable.io -->

2024-02-13 15:29 UTC, johnml1135 commented
*[`src/Serval.Grpc/Utils/WriteGrpcHealthCheckResponse.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/serval/312#-NqXg0G-3H4PkNmaJcp0:-NqY4Hxl6l5dMAMlRkjz:bjt31y4) ([raw file](https://github.com/sillsdev/serval/blob/95e0586e9789dc7082273d591ca694b9ec96f05b/src/Serval.Grpc/Utils/WriteGrpcHealthCheckResponse.cs#L18)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this really best practice? I suppose this code is unlikely to be extended very much. I was taught to never use if without braces in c-inspired languages except perhaps in a freestanding, single-line (of course) if-statement - and absolutely never in nested statements. Without braces, it's easy to add cases or more lines of condition-guarded logic incorrectly. The auto-formatting helps, but even so. Like I said, maybe in this function it's not an issue, but I'm not sure I'd like warnings attached to all of my if statements which I might leave with braces intentionally for extensibility/readability.
</blockquote></details>

The only issue I found with Csharpier formatting has been nested `foreach` statements.  Yes, this is relying on the nesting for clarity and having the code be readable as if it was python.  Currently, we are doing a mix of each throughout our code - this is to encode that yes, you don't have to put in braces in each place.  If you want to for clarity, it is still possible.


<!-- Sent from Reviewable.io -->

2024-02-13 15:35 UTC, johnml1135 commented
*[`tests/Serval.ApiServer.IntegrationTests/DataFilesTests.cs` line 70 at r1](https://reviewable.io/reviews/sillsdev/serval/312#-NqXiCKt6NytJwUn6ZE4:-NqY5d5q-6_w971UKiYK:bsg4tkr) ([raw file](https://github.com/sillsdev/serval/blob/95e0586e9789dc7082273d591ca694b9ec96f05b/tests/Serval.ApiServer.IntegrationTests/DataFilesTests.cs#L70)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I do think these are fairly clear with 'var', but I suppose it doesn't hurt. Maybe some of these settings should be configured differently for tests?
</blockquote></details>

These are the rules:
```
csharp_style_var_for_built_in_types = false:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_var_elsewhere = false:suggestion
```
There is a specific definition of "is apparent" which is a little different than the normal reading of it.  I have set it so that the use of var is deterministic - and there would be no questions about whether it was appropriate or not.


<!-- Sent from Reviewable.io -->

2024-02-14 17:40 UTC, Enkidu93 requested changes
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`.editorconfig` line 198 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgCHfAuzF8tL-VFBE:-NqcgCHfAuzF8tL-VFBF:b-1hxmqg) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L198)):*
> ```EditorConfig
> 
> # CA1826: Do not use Enumerable methods on indexable collections. Instead use the collection directly
> dotnet_diagnostic.CA1826.severity = suggestion
> ```

Why the change to suggestion on this particular one?
___
*[`src/SIL.DataAccess/ExpressionHelper.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgYknEIPgkBrDnv38:-NqcgYknEIPgkBrDnv39:b311dwh) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/ExpressionHelper.cs#L32)):*
> ```Smalltalk
>     }
> 
>     public static TV? FindEqualsConstantValue<T, TV>(Expression<Func<T, TV>> field, Expression expression)
> ```

Explain this one to me - what's the idea behind changing the generic name?


<!-- Sent from Reviewable.io -->

2024-02-14 19:10 UTC, johnml1135 commented
*[`.editorconfig` line 198 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgCHfAuzF8tL-VFBE:-Nqd0nb7BCBNDoxBKR_N:bhsuqpk) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L198)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why the change to suggestion on this particular one?
</blockquote></details>

This one should be a warning...


<!-- Sent from Reviewable.io -->

2024-02-14 19:14 UTC, johnml1135 commented
*[`src/SIL.DataAccess/ExpressionHelper.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgYknEIPgkBrDnv38:-Nqd1-RdA8oRklJ4SGxx:b-cff9o7) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/ExpressionHelper.cs#L32)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Explain this one to me - what's the idea behind changing the generic name?
</blockquote></details>

Renamed to TConstant.  It was complaining about https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1715.


<!-- Sent from Reviewable.io -->

2024-02-14 19:35 UTC, ddaspit requested changes
> Reviewed 78 of 89 files at r1, 14 of 14 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: all files reviewed, 10 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`.editorconfig` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKvTR8frYU13jAGB2:-NqcKvTR8frYU13jAGB3:b3y8sdy) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L27)):*
> ```EditorConfig
> 
> # Don't use this. qualifier
> dotnet_style_qualification_for_field = false:suggestion
> ```

I think this is already specified elsewhere.
___
*[`.editorconfig` line 82 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcIUlcBb1ZUcXy0rXg:-NqcIUlcBb1ZUcXy0rXh:b-bxyb4j) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L82)):*
> ```EditorConfig
> dotnet_naming_style.constant_style.capitalization = pascal_case
> 
> # Static fields are camelCase and start with s_
> ```

I don't like the `s_` for static fields. Static read-only fields are essentially constants, so I prefer them to use pascal case.
___
*[`.editorconfig` line 173 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd4OMI7d23JrzZVM_-:-Nqd4OMI7d23JrzZVM_0:biae4am) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L173)):*
> ```EditorConfig
> 
> # CA1725: Parameter names should match base declaration
> dotnet_diagnostic.CA1725.severity = warning
> ```

This should be a suggestion.
___
*[`.editorconfig` line 198 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgCHfAuzF8tL-VFBE:-Nqd1OUiCDBY3Byoyp3N:brgbej1) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L198)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This one should be a warning...
</blockquote></details>

I would leave this as a warning.
___
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-NqcKHNd6s53_8Q8R446:b-g96aaw) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
> ```Smalltalk
> namespace Serval.ApiServer;
> 
> #pragma warning disable CA1724 // Conflicts with SIL.Program
> ```

I really would prefer not to disable warnings. Is there no better way to fix this?
___
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKYw29R0ZUgT8D_qr:-NqcKYw29R0ZUgT8D_qs:baappak) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Serval.ApiServer.csproj#L11)):*
> ```XML
> 		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
> 		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
> 		<GenerateDocumentationFile>true</GenerateDocumentationFile>
> ```

If we aren't using the documentation files, then we don't need to generate them. We won't need to suppress the related warnings as well.
___
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-Nqd2okiEd_jnAJflYu_:bwtcfcs) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
> ```Smalltalk
> public class ZipContainer(string fileName) : DisposableBase, IZipContainer
> {
> #pragma warning disable CA2213 // Dispose in DisposeManagedResources
> ```

There's got to be a better way to handle this.
___
*[`src/SIL.DataAccess/MongoRepository.cs` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5BFs1DSH-fdYqraz:-Nqd5BFs1DSH-fdYqrb-:b-hg9aql) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoRepository.cs#L11)):*
> ```Smalltalk
>     public async Task<T?> GetAsync(Expression<Func<T, bool>> filter, CancellationToken cancellationToken = default)
>     {
>         if (_context.Session is not null)
> ```

Why were some braces removed for multiline `if` statements and some added?
___
*[`src/SIL.DataAccess/MongoSubscription.cs` line 109 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5Vze3mwD9noAx_SO:-Nqd5Vze3mwD9noAx_SP:b-3f0htr) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoSubscription.cs#L109)):*
> ```Smalltalk
>     protected override void DisposeManagedResources()
>     {
>         _context.Dispose();
> ```

This shouldn't be disposed here. These kinds of changes should be made in a separate PR.


<!-- Sent from Reviewable.io -->

2024-02-14 20:05 UTC, johnml1135 commented
*[`.editorconfig` line 82 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcIUlcBb1ZUcXy0rXg:-NqdCo7S6wrdCSkwvcT5:b-qh39p2) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't like the `s_` for static fields. Static read-only fields are essentially constants, so I prefer them to use pascal case.
</blockquote></details>

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-conventions

-   Static fields start with `s_`. This convention isn't the default Visual Studio behavior, nor part of the [Framework design guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields), but is [configurable in editorconfig](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules).

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules

### Example: `const` modifier includes `static` and `readonly`
Consider the following two naming rules:
1.  Constant fields are PascalCase.
2.  Non-public `static` fields are s\_camelCase.
Rule 2 is more specific and takes precedence, so all non-public constant fields are s\_camelCase. To resolve the issue, you can define an intersection rule: non-public constant fields are PascalCase.

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members
❌ DO NOT use a prefix for field names.
For example, do not use "g\_" or "s\_" to indicate static fields.


<!-- Sent from Reviewable.io -->

2024-02-14 20:09 UTC, johnml1135 commented
*[`.editorconfig` line 82 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcIUlcBb1ZUcXy0rXg:-NqdDOpIBfd0RD35wS4f:bi1lxbh) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L82)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-conventions

-   Static fields start with `s_`. This convention isn't the default Visual Studio behavior, nor part of the [Framework design guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-fields), but is [configurable in editorconfig](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules).

https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules

### Example: `const` modifier includes `static` and `readonly`
Consider the following two naming rules:
1.  Constant fields are PascalCase.
2.  Non-public `static` fields are s\_camelCase.
Rule 2 is more specific and takes precedence, so all non-public constant fields are s\_camelCase. To resolve the issue, you can define an intersection rule: non-public constant fields are PascalCase.

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members
❌ DO NOT use a prefix for field names.
For example, do not use "g\_" or "s\_" to indicate static fields.
</blockquote></details>

Ghaaa!  Microsoft contradicts itself!  What should we do?!?!?!?!
Hmm... the design principle of not adding [a-z]_ as a prefix appears sensible.  The only fixed prefixes and appended phrases are `I` for interfaces and `Async` for async calls.  Let's just use Pascal.


<!-- Sent from Reviewable.io -->

2024-02-14 20:18 UTC, johnml1135 commented
*[`.editorconfig` line 173 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd4OMI7d23JrzZVM_-:-NqdGGIcAWZ1UMSoKyv_:bxeq6wg) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L173)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be a suggestion.
</blockquote></details>

Makes sense - tell the user but don'e mandate.  EngeineService.cs is a good example.


<!-- Sent from Reviewable.io -->

2024-02-14 20:31 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-NqdGpAB9tO9xL2M6EyO:bwwx84v) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I really would prefer not to disable warnings. Is there no better way to fix this?
</blockquote></details>

I don't see a way: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1724.  Unless we want to remove the pattern (anti-pattern) of using globals, disabling the warning may be best.


<!-- Sent from Reviewable.io -->

2024-02-14 20:35 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKYw29R0ZUgT8D_qr:-NqdK28SADh2NOyxZ65d:b-scq1i8) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Serval.ApiServer.csproj#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If we aren't using the documentation files, then we don't need to generate them. We won't need to suppress the related warnings as well.
</blockquote></details>

CSC : warning EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/home/johnml1135/repos/serval/tests/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj]


<!-- Sent from Reviewable.io -->

2024-02-14 20:38 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqdKXTX-6IbSU-X_Pn1:b-ijchvl) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There's got to be a better way to handle this.
</blockquote></details>

I think it is part of using the Disposable base.  When was that written?  Can we get rid of the DisposibleBase in Serval - doesn't dotnet have something standard that fills this need?


<!-- Sent from Reviewable.io -->

2024-02-14 20:40 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqdLDyv2cN7UUuV2GDz:b59jcv8) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think it is part of using the Disposable base.  When was that written?  Can we get rid of the DisposibleBase in Serval - doesn't dotnet have something standard that fills this need?
</blockquote></details>

Will these updates work - remove DisposableBase, implement IDisposable and Dispose() and call GC.SuppressFinalize(this)?  If they work, I will use for all instances.


<!-- Sent from Reviewable.io -->

2024-02-14 20:42 UTC, johnml1135 commented
*[`src/SIL.DataAccess/MongoRepository.cs` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5BFs1DSH-fdYqraz:-NqdLk6iBP7-5WzN4PuF:b6v0le1) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoRepository.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why were some braces removed for multiline `if` statements and some added?
</blockquote></details>

I was wanting to remove most of them.  I can revert them.  Machine will not have these changes.


<!-- Sent from Reviewable.io -->

2024-02-14 20:44 UTC, johnml1135 commented
*[`src/SIL.DataAccess/MongoSubscription.cs` line 109 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5Vze3mwD9noAx_SO:-NqdLwls7iaci7hYUq0s:begcxyk) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoSubscription.cs#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This shouldn't be disposed here. These kinds of changes should be made in a separate PR.
</blockquote></details>

One option is to start this one from scratch as well - copy over the editorconfig and fix minimally.  What do you think?


<!-- Sent from Reviewable.io -->

2024-02-14 20:52 UTC, johnml1135 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: 85 of 92 files reviewed, 10 unresolved discussions (waiting on @ddaspit and @Enkidu93)

___
*[`.editorconfig` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKvTR8frYU13jAGB2:-NqdCMfW-i3zU255YHe-:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think this is already specified elsewhere.
</blockquote></details>

Done.
___
*[`.editorconfig` line 198 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgCHfAuzF8tL-VFBE:-NqdGTpi7ZvSJIfOObrX:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L198)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would leave this as a warning.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-14 20:58 UTC, johnml1135 commented
*[`src/SIL.DataAccess/MongoSubscription.cs` line 109 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5Vze3mwD9noAx_SO:-NqdPK44DnJ3Sp1kmBKw:b-sq666t) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoSubscription.cs#L109)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

One option is to start this one from scratch as well - copy over the editorconfig and fix minimally.  What do you think?
</blockquote></details>

I removed that dispose and checked - I did not add any more dispose in Serval - just a `GC.SuppressFinalize(this);` in ZipContainer.


<!-- Sent from Reviewable.io -->

2024-02-15 15:33 UTC, ddaspit reviewed
> Reviewed 7 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: 91 of 92 files reviewed, 5 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`.editorconfig` line 82 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcIUlcBb1ZUcXy0rXg:-NqhLFFn8nnaNGgD5M1Z:bt95oiu) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L82)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ghaaa!  Microsoft contradicts itself!  What should we do?!?!?!?!
Hmm... the design principle of not adding [a-z]_ as a prefix appears sensible.  The only fixed prefixes and appended phrases are `I` for interfaces and `Async` for async calls.  Let's just use Pascal.
</blockquote></details>

To tell you the truth, I never create static fields that aren't also read-only (essentially constants). To me that is a code smell.
___
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-NqhORLZ23uP7_u_qMcB:bk8s7hq) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I don't see a way: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1724.  Unless we want to remove the pattern (anti-pattern) of using globals, disabling the warning may be best.
</blockquote></details>

Can you just remove the global using that is causing this conflict?
___
*[`src/Serval.ApiServer/Serval.ApiServer.csproj` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKYw29R0ZUgT8D_qr:-NqhMu22-7I2K3-grNxO:b-wpdy2) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Serval.ApiServer.csproj#L11)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

CSC : warning EnableGenerateDocumentationFile: Set MSBuild property 'GenerateDocumentationFile' to 'true' in project file to enable IDE0005 (Remove unnecessary usings/imports) on build (https://github.com/dotnet/roslyn/issues/41640) [/home/johnml1135/repos/serval/tests/Serval.ApiServer.IntegrationTests/Serval.ApiServer.IntegrationTests.csproj]
</blockquote></details>

That is interesting. I wonder why. In any case, that's fine.
___
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqhNSy70rxh3ZR6XJtG:bka34ij) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Will these updates work - remove DisposableBase, implement IDisposable and Dispose() and call GC.SuppressFinalize(this)?  If they work, I will use for all instances.
</blockquote></details>

I think that's fine. It is better than adding ugly suppress warning pragmas in every disposable class. It is a bit annoying that we can't use the `DisposableBase` class that implements the dispose pattern for us. Maybe it would be better to just turn the check into a suggestion.
___
*[`src/SIL.DataAccess/MongoRepository.cs` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5BFs1DSH-fdYqraz:-NqhO0SM1iLODevN4aIb:bp4rwdj) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoRepository.cs#L11)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I was wanting to remove most of them.  I can revert them.  Machine will not have these changes.
</blockquote></details>

Yes, please revert them. We only want to remove the braces on `if...else` statements where every statement body is only a single line.


<!-- Sent from Reviewable.io -->

2024-02-15 19:22 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqiCwAe169BF6Dj_-Gs:b-migk05) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think that's fine. It is better than adding ugly suppress warning pragmas in every disposable class. It is a bit annoying that we can't use the `DisposableBase` class that implements the dispose pattern for us. Maybe it would be better to just turn the check into a suggestion.
</blockquote></details>

What is the difference between DisposableBase and IDisposable?  Why was DisposableBase created in the first place?


<!-- Sent from Reviewable.io -->

2024-02-15 19:38 UTC, johnml1135 commented
*[`.editorconfig` line 82 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcIUlcBb1ZUcXy0rXg:-NqiGBva1-LTVUugu3vZ:b-ec5je3) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/.editorconfig#L82)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

To tell you the truth, I never create static fields that aren't also read-only (essentially constants). To me that is a code smell.
</blockquote></details>

All to Pascal.  Also, we are checking for CA2211.


<!-- Sent from Reviewable.io -->

2024-02-15 20:05 UTC, johnml1135 commented
*[`src/SIL.DataAccess/MongoRepository.cs` line 11 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd5BFs1DSH-fdYqraz:-NqiN-420iuMNBHVUCIz:b-bw8e14) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/MongoRepository.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, please revert them. We only want to remove the braces on `if...else` statements where every statement body is only a single line.
</blockquote></details>

Updated.


<!-- Sent from Reviewable.io -->

2024-02-15 21:01 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-NqiR9eA7sN5y4ns1kFn:b6im0bo) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can you just remove the global using that is causing this conflict?
</blockquote></details>

Hmmm.  If we get rid of DisposableBase, we may be able to get rid of SIL.Core which has the SIL.Program...


<!-- Sent from Reviewable.io -->

2024-02-16 16:12 UTC, ddaspit reviewed
> Reviewed 14 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: 91 of 92 files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-NqmVH9T3WFTWCBIwR7h:byabz7q) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Hmmm.  If we get rid of DisposableBase, we may be able to get rid of SIL.Core which has the SIL.Program...
</blockquote></details>

I think we should just make this rule a suggestion.
___
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqmTVnJAz2U8a3KinPz:befub8g) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What is the difference between DisposableBase and IDisposable?  Why was DisposableBase created in the first place?
</blockquote></details>

`DisposableBase` implements the [dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) properly. It can be a bit tricky to get right and it makes it very clear where things should be disposed by providing the `DisposeManagedResources` and `DisposeUnmanagedResources` methods.


<!-- Sent from Reviewable.io -->

2024-02-16 16:14 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-NqmgbsQ9fKBl2vVmtH5:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`DisposableBase` implements the [dispose pattern](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) properly. It can be a bit tricky to get right and it makes it very clear where things should be disposed by providing the `DisposeManagedResources` and `DisposeUnmanagedResources` methods.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 16:14 UTC, johnml1135 commented
*[`src/Serval.ApiServer/Program.cs` line 3 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcKHNd6s53_8Q8R445:-Nqmgf3m0uMPznD3wybY:blggctd) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.ApiServer/Program.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we should just make this rule a suggestion.
</blockquote></details>

I'll make it a suggestion and revert changes.


<!-- Sent from Reviewable.io -->

2024-02-16 16:15 UTC, johnml1135 commented
*[`src/Serval.Shared/Services/ZipContainer.cs` line 8 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-Nqd2okiEd_jnAJflYuZ:-Nqmgqrm0DAxxnKoDXYK:b-a1xtl6) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/Serval.Shared/Services/ZipContainer.cs#L8)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'll revert all to DisposableBase.


<!-- Sent from Reviewable.io -->

2024-02-16 17:06 UTC, Enkidu93 approved these changes
> Reviewed 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/SIL.DataAccess/ExpressionHelper.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgYknEIPgkBrDnv38:-Nqmrg6S5E6A-7_e3pf_:b-gxis8o) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/ExpressionHelper.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Renamed to TConstant.  It was complaining about https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1715.
</blockquote></details>

I see - that makes sense. 


<!-- Sent from Reviewable.io -->

2024-02-16 17:48 UTC, johnml1135 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @Enkidu93)

___
*[`src/SIL.DataAccess/ExpressionHelper.cs` line 32 at r2](https://reviewable.io/reviews/sillsdev/serval/312#-NqcgYknEIPgkBrDnv38:-Nqn14sj3hdVWb7kTisR:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/f923e7338a4c770c67d55bb01aff6ad61c79d563/src/SIL.DataAccess/ExpressionHelper.cs#L32)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I see - that makes sense.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-16 18:58 UTC, ddaspit reviewed
One last thing, please add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` to all csproj files.

> Reviewed 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312#-:-NqnGbs4Cc39pQ5KMU7Y:bc0urq9)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-02-16 19:02 UTC, johnml1135 reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312#-:-NqnI08T2WaD67XH95P4:bb6un1j)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-02-16 19:03 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/312#-:-NqnIOlb-PfSqq8r3tH3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-02-16 19:07 UTC, merged