Fix #464 - add lock timeout
sillsdev/serval pull request #473
Opened 2024-09-03 20:28 UTC by johnml1135

2024-09-03 21:13 UTC, ddaspit requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/ServiceOptions.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/473#-O5tiKH26PLNeB1URWNU:-O5tiKH26PLNeB1URWNV:bpd9uer) ([raw file](https://github.com/sillsdev/serval/blob/76e5ed957bcb483285447b786fa1eef2509cfcfd/src/Machine/src/Serval.Machine.Shared/Configuration/ServiceOptions.cs#L8)):*
> ```Smalltalk
> 
>     public string ServiceId { get; set; } = "machine_api";
>     public TimeSpan ReadWriteLockTimeout { get; set; } = TimeSpan.FromSeconds(55);
> ```

I don't think we can use the same timeout for all locks. Some locks are acquired to perform a short task and others are acquired to perform a long task. We will probably need to go through every use of the distributed lock and provide an appropriate lifetime.


<!-- Sent from Reviewable.io -->

2024-09-04 12:45 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Configuration/ServiceOptions.cs` line 8 at r1](https://reviewable.io/reviews/sillsdev/serval/473#-O5tiKH26PLNeB1URWNU:-O5x2eaa7C177aqxlLiY:b-22x8vk) ([raw file](https://github.com/sillsdev/serval/blob/76e5ed957bcb483285447b786fa1eef2509cfcfd/src/Machine/src/Serval.Machine.Shared/Configuration/ServiceOptions.cs#L8)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we can use the same timeout for all locks. Some locks are acquired to perform a short task and others are acquired to perform a long task. We will probably need to go through every use of the distributed lock and provide an appropriate lifetime.
</blockquote></details>

We are expecting them to not need the timeout at all - we had "infinite" before.  What this is really only doing is (hopefully) not letting the whole server be brought down by a lock not being released and giving us breadcrumbs for figuring out which lock was the offender.  Responsiveness is not the top thing on the list for me, but rather simplicity.
  That being the case, this is just a default.  If there is a better default, let's use it.  Or conversely, if we want a small timeout (5 seconds?) and have only a few calls be longer (that may have a more hefty database operation), then let's do it.


<!-- Sent from Reviewable.io -->

2024-09-05 20:24 UTC, ddaspit requested changes
Since we haven't done profiling on how long it takes to perform many of these operations, I would feel more comfortable starting with more conservative timeouts/lifetimes. Also, have we verified what happens when a request timeout occurs? Does the cancellation token get triggered? What status code is returned?

> Reviewed 1 of 3 files at r2, 8 of 14 files at r3, 24 of 24 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473#-:-O62pmkA3WqV3lVE6QGT:bzh5aj)* status: all files reviewed, 11 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 49 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62oPJ7ACcU8CJNnNDE:-O62oPJ7ACcU8CJNnNDF:bpzdp3) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L49)):*
> ```XML
> 		<ProjectReference Include="..\..\..\DataAccess\src\SIL.DataAccess\SIL.DataAccess.csproj" />
> 		<ProjectReference Include="..\..\..\Serval\src\Serval.Grpc\Serval.Grpc.csproj" />
> 		<ProjectReference Include="..\..\..\Serval\src\Serval.Shared\Serval.Shared.csproj" />
> ```

We should not be referencing the `Serval.Shared` library in the Machine engine.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs` line 41 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62n-L8AWLhNWRlJ7Jr:-O62n-L8AWLhNWRlJ7Js:buybgtb) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs#L41)):*
> ```Smalltalk
>     {
>         string lockId = _idGenerator.GenerateId();
>         StackTrace stackTrace = new StackTrace();
> ```

I think you accidentally left this debugging code in.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferBuildJob.cs` line 117 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62nGmT8UDqy0YPJIpy:-O62nGmT8UDqy0YPJIpz:bck7oen) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferBuildJob.cs#L117)):*
> ```Smalltalk
>         await using (
>             await @lock.WriterLockAsync(
>                 lifetime: _timeoutOptions.LongProcessLockLifetime,
> ```

Is this the only place where a longer lifetime is needed? Have you checked every place where a lock is acquired?
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 3 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62X9lP0gcd59C1UlTR:-O62X9lP0gcd59C1UlTS:b-779mi2) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L3)):*
> ```Smalltalk
> namespace Serval.Shared.Configuration;
> 
> public class TimeoutOptions
> ```

This is mixing Serval and Machine timeouts. The Machine timeouts should be specified in the Machine server. 
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62VcsU2PD21-erd2Ek:-O62VcsU2PD21-erd2El:b-3019z2) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L5)):*
> ```Smalltalk
> public class TimeoutOptions
> {
>     public const string Key = "Api";
> ```

We should change this to `Timeout`.
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62VhdJ8qjALk9_jXke:-O62VhdJ8qjALk9_jXkf:bxunela) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L7)):*
> ```Smalltalk
>     public const string Key = "Api";
> 
>     public TimeSpan DefaultHttpRequestTimeout { get; set; } = TimeSpan.FromSeconds(10);
> ```

I think we should use the same request timeout for everything. The main purpose of the request timeout is to avoid unnecessarily continuing to process a request if Cloudflare kills the connection due to a timeout. [Cloudflare's timeout](https://community.cloudflare.com/t/community-tip-fixing-error-524-a-timeout-occurred/42342) seems to be 100 seconds, so we should just set all of our request timeouts to something around that, maybe 90 seconds.
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62XOBg2OgdDnlBXXYZ:-O62XOBg2OgdDnlBXXY_:b5q7wh6) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L10)):*
> ```Smalltalk
>     public TimeSpan LongHttpRequestTimeout { get; set; } = TimeSpan.FromSeconds(58); // must be less than 60 seconds Cloudflare timeout
>     public TimeSpan LongPollTimeout { get; set; } = TimeSpan.FromSeconds(40); // must be less than LongHttpRequestTimeout
>     public TimeSpan DefaultLockTimeout { get; set; } = TimeSpan.FromSeconds(8); // must be less than DefaultHttpRequestTimeout
> ```

Do we need a lock timeout if we have a request timeout?
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 11 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62WDUc3E1hW9SYToz6:-O62WDUdC2jTO8Qxrjwa:b-eby1j5) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L11)):*
> ```Smalltalk
>     public TimeSpan LongPollTimeout { get; set; } = TimeSpan.FromSeconds(40); // must be less than LongHttpRequestTimeout
>     public TimeSpan DefaultLockTimeout { get; set; } = TimeSpan.FromSeconds(8); // must be less than DefaultHttpRequestTimeout
>     public TimeSpan DefaultLockLifetime { get; set; } = TimeSpan.FromSeconds(6); // must be less than DefaultLockTimeout
> ```

We should be more conservative with the default lifetime. Maybe 60 seconds.
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62Wl4p-knU4eBNXtp6:-O62Wl4p-knU4eBNXtp7:b5ujo8u) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L12)):*
> ```Smalltalk
>     public TimeSpan DefaultLockTimeout { get; set; } = TimeSpan.FromSeconds(8); // must be less than DefaultHttpRequestTimeout
>     public TimeSpan DefaultLockLifetime { get; set; } = TimeSpan.FromSeconds(6); // must be less than DefaultLockTimeout
>     public TimeSpan LongHttpLockLifetime { get; set; } = TimeSpan.FromSeconds(56); // must be less than HttpLongRequestTimeout
> ```

I don't think we need this.
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 13 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62pGRs0kkZ7JP3h9jR:-O62pGRs0kkZ7JP3h9jS:bdmwamv) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L13)):*
> ```Smalltalk
>     public TimeSpan DefaultLockLifetime { get; set; } = TimeSpan.FromSeconds(6); // must be less than DefaultLockTimeout
>     public TimeSpan LongHttpLockLifetime { get; set; } = TimeSpan.FromSeconds(56); // must be less than HttpLongRequestTimeout
>     public TimeSpan LongProcessLockLifetime { get; set; } = TimeSpan.FromSeconds(120);
> ```

I would either remove this option or make the option name more specific to where it is used. I don't think it is useful to have a general "long" lifetime. We should tailor the lifetime to the particular task.
___
*[`src/Serval/src/Serval.Shared/Utils/TaskEx.cs` line 22 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62Xdx16P1uU1Vf20zp:-O62Xdx16P1 [...]

2024-09-05 21:05 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 49 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62oPJ7ACcU8CJNnNDE:-O63-M5d6s81DLAop6bU:b-n4zo2j) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L49)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should not be referencing the `Serval.Shared` library in the Machine engine.
</blockquote></details>

Should the Timeout routine move somewhere else then?


<!-- Sent from Reviewable.io -->

2024-09-05 21:06 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs` line 41 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62n-L8AWLhNWRlJ7Jr:-O63-fXi4RTI02F55WMa:ba3dfob) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs#L41)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think you accidentally left this debugging code in.
</blockquote></details>

Removed


<!-- Sent from Reviewable.io -->

2024-09-05 21:07 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferBuildJob.cs` line 117 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62nGmT8UDqy0YPJIpy:-O63-hRVDTxsPKlCIjbf:b-8n8a7c) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferBuildJob.cs#L117)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Is this the only place where a longer lifetime is needed? Have you checked every place where a lock is acquired?
</blockquote></details>

I have briefly and did some testing.  I also changed the Timeout for the long polling.


<!-- Sent from Reviewable.io -->

2024-09-05 21:09 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62VhdJ8qjALk9_jXke:-O6305PqB1rJjesEqHfe:b-1v21oy) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I think we should use the same request timeout for everything. The main purpose of the request timeout is to avoid unnecessarily continuing to process a request if Cloudflare kills the connection due to a timeout. [Cloudflare's timeout](https://community.cloudflare.com/t/community-tip-fixing-error-524-a-timeout-occurred/42342) seems to be 100 seconds, so we should just set all of our request timeouts to something around that, maybe 90 seconds.
</blockquote></details>

It is 60 (I am confident of that).  I am fine setting all HTTP request timeouts to 58 seconds - it minimizes the impact.


<!-- Sent from Reviewable.io -->

2024-09-05 21:12 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62XOBg2OgdDnlBXXYZ:-O630eEIDYXaU3RiUwGR:b-h0socp) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do we need a lock timeout if we have a request timeout?
</blockquote></details>

we shouldn't actually need it - it may be helpful to know whether the task failed because it's own lifetime expired or a lock was not released.  It may not need that logic though - now that ExpiresAt is mandatory.


<!-- Sent from Reviewable.io -->

2024-09-05 21:12 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 11 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62WDUc3E1hW9SYToz6:-O6313rI613AGb8tZW3P:b-mnaewl) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should be more conservative with the default lifetime. Maybe 60 seconds.
</blockquote></details>

Or, as you said above, we could remove it.


<!-- Sent from Reviewable.io -->

2024-09-05 21:14 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 13 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62pGRs0kkZ7JP3h9jR:-O631ByaEubO9JvvPC2w:b-8ph9mg) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would either remove this option or make the option name more specific to where it is used. I don't think it is useful to have a general "long" lifetime. We should tailor the lifetime to the particular task.
</blockquote></details>

This is used for post training an SMT model.  I can rename and move it to a new location.


<!-- Sent from Reviewable.io -->

2024-09-05 21:22 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Utils/TaskEx.cs` line 22 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62Xdx16P1uU1Vf20zp:-O631OxmDYzQKKBmP1Z6:btpd331) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Utils/TaskEx.cs#L22)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should return a boolean indicating if the operation timed out, so that the calling code can decide what to do about it.
</blockquote></details>

Ok - should it be consistent with both Timeouts?


<!-- Sent from Reviewable.io -->

2024-09-05 21:22 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62VcsU2PD21-erd2Ek:-O633OJ9EAaE9UNHLwaG:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should change this to `Timeout`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-05 21:25 UTC, johnml1135 commented
Partial fix uploaded.  We can discuss more tomorrow.





<!-- Sent from Reviewable.io -->

2024-09-05 22:08 UTC, ddaspit reviewed
> Reviewed 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473)* status: all files reviewed, 8 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 49 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62oPJ7ACcU8CJNnNDE:-O636ByN1y-chsxEhmw7:b-ibr9bf) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L49)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Should the Timeout routine move somewhere else then?
</blockquote></details>

If we remove the timeout from the lock, then we don't need this at all.
___
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62XOBg2OgdDnlBXXYZ:-O636Zwl8gclQwM7FRmK:b-1jt7k8) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

we shouldn't actually need it - it may be helpful to know whether the task failed because it's own lifetime expired or a lock was not released.  It may not need that logic though - now that ExpiresAt is mandatory.
</blockquote></details>

Yeah, I feel like the request timeout will handle this. It would be good to bail out of a task inside of a lock if it lasts longer than the configured lifetime. I am a bit worried about the lifetime for a lock being set to short and another thread causing data corruption or race conditions. We would need to redesign the locking call a bit.


<!-- Sent from Reviewable.io -->

2024-09-06 16:54 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 49 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62oPJ7ACcU8CJNnNDE:-O67FcAi-IzHGTWyO6sM:b-hfpv0l) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L49)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If we remove the timeout from the lock, then we don't need this at all.
</blockquote></details>

removed


<!-- Sent from Reviewable.io -->

2024-09-06 16:55 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 12 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62Wl4p-knU4eBNXtp6:-O67FhE58rQh_RTzZMgv:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we need this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-06 16:55 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 3 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62X9lP0gcd59C1UlTR:-O67FhsmAcXEhLsDiXA_:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is mixing Serval and Machine timeouts. The Machine timeouts should be specified in the Machine server.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-06 16:57 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/473#-O62XOBg2OgdDnlBXXYZ:-O67FtNG4DxMqY-1Zqhe:b-1fl4i9) ([raw file](https://github.com/sillsdev/serval/blob/9ff3c4a9e22289b749cfb063b09328bba8443429/src/Serval/src/Serval.Shared/Configuration/TimeoutOptions.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yeah, I feel like the request timeout will handle this. It would be good to bail out of a task inside of a lock if it lasts longer than the configured lifetime. I am a bit worried about the lifetime for a lock being set to short and another thread causing data corruption or race conditions. We would need to redesign the locking call a bit.
</blockquote></details>

Done.  Increased the standard lifetime to 58 seconds.


<!-- Sent from Reviewable.io -->

2024-09-09 13:45 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs` line 85 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6LwwVWC8BMrK-lnVlv:-O6LwwVWC8BMrK-lnVlw:b-egbadn) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs#L85)):*
> ```Smalltalk
>         try
>         {
>             (bool completed, T? result) = await TaskEx.Timeout(action, expiresAt - DateTime.UtcNow, cancellationToken);
> ```

You combined lifetime and Timeout into one field?


<!-- Sent from Reviewable.io -->

2024-09-09 13:52 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/HangfireBuildJob.cs` line 66 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6M24sA0q9EQ9xD66Pf:-O6M24sA0q9EQ9xD66Pg:b-xmiwf5) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/HangfireBuildJob.cs#L66)):*
> ```Smalltalk
>             {
>                 completionStatus = JobCompletionStatus.Canceled;
>                 await DataAccessContext.WithTransactionAsync(
> ```

In nearly all of these, there is only one of two database operations being done, already with a transaction.  Therefore, the lock is really not relevant.


<!-- Sent from Reviewable.io -->

2024-09-09 14:13 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineState.cs` line 1 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6M7WcqCpuQkrNutl6b:-O6M7WcqCpuQkrNutl6c:bukk4bf) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineState.cs#L1)):*
> ```Smalltalk
> using SIL.ObjectModel;
> ```

This should be a global using.


<!-- Sent from Reviewable.io -->

2024-09-09 16:08 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineStateService.cs` line 1 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6MXnWe2xxXBxwOAYe-:-O6MXnWe2xxXBxwOAYe0:b-3fyb9w) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineStateService.cs#L1)):*
> ```Smalltalk
> using SIL.ObjectModel;
> ```

Global using


<!-- Sent from Reviewable.io -->

2024-09-09 16:14 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/TaskEx.cs` line 18 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6MYB60EcAoEJ0-47EC:-O6MYB60EcAoEJ0-47ED:bawv00c) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/TaskEx.cs#L18)):*
> ```Smalltalk
>         Task<T> completedTask = await Task.WhenAny(task, Delay<T>(timeout, cancellationToken));
>         if (completedTask == task)
>             return (true, await task);
> ```

if the cancellation token is thrown, the delay task will return - and think that the task timed out.  The "RanToCompletion" status appears more reliable.


<!-- Sent from Reviewable.io -->

2024-09-09 16:26 UTC, johnml1135 reviewed
> Reviewed 1 of 14 files at r3, 16 of 27 files at r7, 1 of 1 files at r8, 1 of 1 files at r10, 37 of 37 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473)* status: all files reviewed, 17 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-09-10 00:11 UTC, johnml1135 reviewed
> Reviewed 2 of 24 files at r4, 1 of 4 files at r5, 4 of 12 files at r6, 13 of 13 files at r12, all commit messages.
> Dismissed @ddaspit from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473)* status: all files reviewed, 15 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-09-10 16:43 UTC, ddaspit reviewed
Maybe, but it isn't clear without further investigation.

> Reviewed 27 of 27 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 32 of 37 files at r11, 13 of 13 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473#-:-O6Rnb8t0CPRCyloOFO3:b-fab1tr)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 49 at r5](https://reviewable.io/reviews/sillsdev/serval/473#-O62oPJ7ACcU8CJNnNDE:-O67DWlB-7ya4xuzZqPN:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/e20bfe7e26eb8ba1aeb658c942eb3ba0c695d841/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L49)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

removed
</blockquote></details>

Done
___
*[`src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs` line 109 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6LkpiZ-p2kH74GH4SX:-O6RgGX4BvJAVS_z2VWj:b-wycfi9) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs#L109)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why are we deleting the job here?  I am assuming that it is to correct for incomplete cleanup (the engine was deleted, but the jobs were not).
</blockquote></details>

We are performing the state check and the update as a single atomic operation, since we are no longer locking. In order to do this, we must first create the job, so that we can get the job id. If the engine is in the wrong state, i.e. there is already a build running, then we need to clean up the job that we just created before returning.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs` line 85 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6LwwVWC8BMrK-lnVlv:-O6RhWmrBrlpbBiINZ52:b8efv77) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/DistributedReaderWriterLock.cs#L85)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Or, keep trying forever, but when you have it, only hold onto it for the specified time...
</blockquote></details>

This isn't the timeout for acquiring a lock. We don't need that, because the request timeout will handle it. This will bail out of the lock once the lifetime has expired. This buys us two things:

1. If the task can no longer hold on to the lock, it should stop processing as soon as possible to avoid race conditions or data corruption.
2. We can log what method actually had the lock when it expired using the `TimeoutInterceptor`. 
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ITruecaserFactory.cs` line 6 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6M4Ldj1qm0ARg44Vj9:-O6Rkp8QB6rfeK-DyVP4:b-m5k4iy) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/ITruecaserFactory.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why no longer Async?
</blockquote></details>

All of these async methods were masking the fact that the underlying SMT model calls are not actually async, so it makes it seem like they are cancelable when they actually aren't. I changed all of these SMT calls to synchronous calls, so that it is clear that they can't be canceled.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineState.cs` line 1 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6M7WcqCpuQkrNutl6b:-O6RlHGo9FlCLXB-pkLE:b-5ktvyh) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineState.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should be a global using.
</blockquote></details>

This was intentional. This using has name conflicts in other classes. By only including it here, we avoid the name conflicts.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineStateService.cs` line 1 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6MXnWe2xxXBxwOAYe-:-O6RlaRP9pMWifHJmNCA:b5trl6m) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/Machine/src/Serval.Machine.Shared/Services/SmtTransferEngineStateService.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Global using
</blockquote></details>

See my other comment on this using.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/TaskEx.cs` line 18 at r11](https://reviewable.io/reviews/sillsdev/serval/473#-O6MYB60EcAoEJ0-47EC:-O6Rlf3aBpeL28YrChGp:b-m76wri) ([raw file](https://github.com/sillsdev/serval/blob/8704dac0caa4952caa0d3e113fdaa9dda77431f3/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/TaskEx.cs#L18)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

if the cancellation token is thrown, the delay task will return - and think that the task timed out.  The "RanToCompletion" status appears more reliable.
</blockquote></details>

If the cancellation token is triggered, then `TaskCanceledException` will be thrown, so this check is never called and therefore doesn't matter. Checking `delayTask.Status` can result in a race condition. If delay task completes right after the main task completes and before the `if` check, it will be incorrectly treated as a timeout.


<!-- Sent from Reviewable.io -->

2024-09-10 17:38 UTC, johnml1135 reviewed
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/473)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-09-10 17:38 UTC, merged