Serval-side mixed source support
sillsdev/serval pull request #497
Opened 2024-09-23 20:56 UTC by Enkidu93

**THIS IS A DRAFT**

There are still tests to add, refactoring to do, and documentation to add as well as a relatively small change to the Machine repo to allow it to handle multiple target files appropriately, but I think you can see the idea. I'll set this aside until I have your feedback and either your OK to wrap things up or your instructions to jump ship and use a different API design. That being said, I may work on the change to machine since I believe that will be needed regardless.

2024-09-24 15:33 UTC, Enkidu93 commented
Note: I'm realizing I'm accidentally mixing across corpus pairs (easy to fix) but in case someone gets to looking at this before I make that change, I'm aware.

2024-09-30 22:41 UTC, ddaspit commented
I took a quick look. This looks like a good direction. You should continue down this path.

2024-10-03 23:03 UTC, ddaspit requested changes
I'm not finished reviewing yet, but here is the first batch of suggestions. So far this is looking really good.

> Reviewed 38 of 44 files at r1, 6 of 8 files at r2, 12 of 25 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497#-:-O8Jb_9nDOJaBB4eI71d:b-kys8zn)* status: 52 of 65 files reviewed, 18 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval/src/Serval.DataFiles/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JbODS2rRNyFycpr40:-O8JbODS2rRNyFycpr41:bfuwmfr) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.DataFiles/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L27)):*
> ```Smalltalk
>     }
> 
>     public static IMongoDataAccessConfigurator AddCorporaRepository(this IMongoDataAccessConfigurator configurator)
> ```

This can be merged into the `AddDataFilesRepositories`.
___
*[`src/Serval/src/Serval.DataFiles/Configuration/IServalBuilderExtensions.cs` line 17 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JbI58AD8_GKu_23to:-O8JbI58AD8_GKu_23tp:b-tz408k) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.DataFiles/Configuration/IServalBuilderExtensions.cs#L17)):*
> ```Smalltalk
>     }
> 
>     public static IServalBuilder AddCorpora(this IServalBuilder builder)
> ```

This can be merged into the `AddDataFiles` method.
___
*[`src/Serval/src/Serval.Translation/Contracts/ParallelCorpusDto.cs` line 0 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JR6yn8UoqNDdr5yl8:-O8JR6yn8UoqNDdr5yl9:bgw0pxo) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/ParallelCorpusDto.cs#L0)):*
I don't believe this file is used anywhere.
___
*[`src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JapItCTyph2xeV6YC:-O8JapItCTyph2xeV6YD:b-2f6oar) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs#L5)):*
> ```Smalltalk
> public record ParallelCorpusFilterConfigDto
> {
>     public required string CorpusRef { get; init; }
> ```

This should be named `CorpusId`.
___
*[`src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusConfigDto.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JaY5k6ZOvGMQTsmTQ:-O8JaY5k6ZOvGMQTsmTR:b-eie8f9) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusConfigDto.cs#L13)):*
> ```Smalltalk
>     public string? ParallelCorpusId { get; init; }
>     public IReadOnlyList<ParallelCorpusFilterConfigDto>? SourceFilters { get; init; }
>     public IReadOnlyList<ParallelCorpusFilterConfigDto>? TargetFilters { get; init; }
> ```

The `TargetFilters` property isn't necessary.
___
*[`src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusDto.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JadkO8AVZDeYF5TiE:-O8JadkO8AVZDeYF5TiF:b-eie8f9) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusDto.cs#L13)):*
> ```Smalltalk
>     public ResourceLinkDto? ParallelCorpus { get; init; }
>     public IReadOnlyList<ParallelCorpusFilterDto>? SourceFilters { get; init; }
>     public IReadOnlyList<ParallelCorpusFilterDto>? TargetFilters { get; init; }
> ```

The `TargetFilters` property isn't necessary.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusConfigDto.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JZ0_dBck0uhYLWkDv:-O8JZ0_dBck0uhYLWkDw:bz7izhd) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusConfigDto.cs#L10)):*
> ```Smalltalk
>     public string? Name { get; init; }
> 
>     public required IReadOnlyList<string> SourceCorporaRefs { get; init; } = new List<string>();
> ```

I would rename this to `SourceCorpusIds`.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8J_9huEe4GX5PZvLQY:-O8J_9huEe4GX5PZvLQZ:b7p4429) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs#L9)):*
> ```Smalltalk
>     public required ResourceLinkDto Engine { get; init; }
> 
>     public required IReadOnlyList<TranslationMonolingualCorpusDto> SourceCorpora { get; init; } =
> ```

This should be a list of `ResourceLinkDto`s.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JYbrk6azYvuqNQbxl:-O8JYbrk6azYvuqNQbxm:b-g2cvry) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs#L10)):*
> ```Smalltalk
> 
>     public required IReadOnlyList<TranslationMonolingualCorpusDto> SourceCorpora { get; init; } =
>         new List<TranslationMonolingualCorpusDto>();
> ```

For `required` properties with `init` setters, it isn't necessary to supply a default value. It will just result in an unnecessary list allocation.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusUpdateDto.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JZywOEzGqV9RM0I1Z:-O8JZywOEzGqV9RM0I1_:bz7izhd) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusUpdateDto.cs#L7)):*
> ```Smalltalk
> public record TranslationParallelCorpusUpdateConfigDto : IValidatableObject
> {
>     public IReadOnlyList<string>? SourceCorpusRefs { get; init; }
> ```

I would rename this to `SourceCorpusIds`.
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 558 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTJgTBvNBJPk606rk:-O8JTJgU2PunI-bwSRC5:b-4cjpv1) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L558)):*
> ```Smalltalk
>         await AuthorizeAsync(engine);
>         Corpus corpus = await MapAsync(getDataFileClient, idGenerator.GenerateId(), corpusConfig, cancellationToken);
>         await _engineService.AddCorpusAsync(id, corpus, cancellationToken);
> ```

Should this be adding a `ParallelCorpus`?
___
*[`src/Serval/src/Serval.Translation/Models/PretranslateCorpus.cs` line 11 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JPIYU30boWt77kEyE:-O8JPIYU30boWt77kEyF:bh1e8hv) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Models/PretranslateCorpus.cs#L11)):*
> ```Smalltalk
>     public string? ParallelCorpusRef { get; set; }
>     public IReadOnlyList<ParallelCorpusFilter>? SourceFilters { get; set; }
>     public IReadOnlyList<ParallelCorpusFilter>? TargetFilters { get; set; } //TODO is this needed?
> ```

We don't need this.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 419 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTgkp1LUhI4-HG-UF:-O8JTgkp1LUhI4-HG-UG:b-yoc5y2) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L419)):*
> ```Smalltalk
>     }
> 
>     publi [...]

2024-10-04 22:10 UTC, Enkidu93 reviewed
Great! Thank you! Sorry it's taken so long.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497#-:-O8MuI3W6MsC78FbCl24:b-xjza1g)* status: 48 of 65 files reviewed, 20 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 811 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8NV3OI1fwcoVH8B0IW:-O8OQ2ow5bgmOZhAGNL5:bppkfxn) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L811)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You can move these static methods into the test fixture class.
</blockquote></details>

I can move these but it's a bit more complicated than just moving these functions since they rely on `ParatextFile` and `TextFile` which rely on the `_tempDir` and `TestDataPath` property. Do you still want me to do that?
___
*[`src/Serval/src/Serval.DataFiles/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 27 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JbODS2rRNyFycpr40:-O8MuKqs30ebOT2mBDik:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.DataFiles/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be merged into the `AddDataFilesRepositories`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.DataFiles/Configuration/IServalBuilderExtensions.cs` line 17 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JbI58AD8_GKu_23to:-O8MuLclENpxTJfWJtlG:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.DataFiles/Configuration/IServalBuilderExtensions.cs#L17)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be merged into the `AddDataFiles` method.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JapItCTyph2xeV6YC:-O8MuNG0Cck8a0B9rKSG:b-82anio) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `CorpusId`.
</blockquote></details>

Done. In general, what's the pattern you're going for in Serval for when to use`...Id` vs. `...Ref`? It didn't seem wholly consistent. My impression was that we were using `Id` when it's in reference to the identifier for that object itself but `Ref`when it's referring to another object's id. Is that about it?
___
*[`src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusConfigDto.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JaY5k6ZOvGMQTsmTQ:-O8MuO-G7tHlA58tojLZ:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusConfigDto.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `TargetFilters` property isn't necessary.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusDto.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JadkO8AVZDeYF5TiE:-O8Mv25aCnSrhnw55WmI:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/PretranslateCorpusDto.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `TargetFilters` property isn't necessary.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusConfigDto.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JZ0_dBck0uhYLWkDv:-O8Mv30O7R2QG7w6iLTS:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusConfigDto.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `SourceCorpusIds`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8J_9huEe4GX5PZvLQY:-O8Mv4ql58tScqBAtqRT:bm3yqt3) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs#L9)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be a list of `ResourceLinkDto`s.
</blockquote></details>

OK, done.
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JYbrk6azYvuqNQbxl:-O8Mv6bV7B-eBMaEaXe-:b-8qgh63) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusDto.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

For `required` properties with `init` setters, it isn't necessary to supply a default value. It will just result in an unnecessary list allocation.
</blockquote></details>

Oops, sorry - I think I previously didn't have it as required with an init and didn't change it. Thanks!
___
*[`src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusUpdateDto.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JZywOEzGqV9RM0I1Z:-O8MvRYw0jysJqkFwBNp:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/TranslationParallelCorpusUpdateDto.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `SourceCorpusIds`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 558 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTJgTBvNBJPk606rk:-O8MvdT55xKGCD-yGPYN:b-a4wcvi) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L558)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Should this be adding a `ParallelCorpus`?
</blockquote></details>

Oops. Done.
___
*[`src/Serval/src/Serval.Translation/Models/PretranslateCorpus.cs` line 11 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JPIYU30boWt77kEyE:-O8MvgRsE4SvD3V3CZGU:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Models/PretranslateCorpus.cs#L11)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We don't need this.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 419 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTgkp1LUhI4-HG-UF:-O8MvhSJBeuRPO7RbrEu:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L419)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `AddParallelCorpus [...]

2024-10-04 22:10 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497)* status: 48 of 65 files reviewed, 20 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 134 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8NTghY4w6YrCb9s3_t:-O8O_QhSCfDI7w77Nu9x:b-y42mmj) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L134)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is really hard for me to follow. It would help readability if we merge the two `Select` calls into one and break up the complex conditional in the second `Select` into functions. There seems to be some overlap between the logic in the training corpora and the pretranslate corpora that could be shared by refactoring into functions.
</blockquote></details>

Let me know if this is clear enough now.


<!-- Sent from Reviewable.io -->

2024-10-04 22:13 UTC, Enkidu93 commented
Also, I realize more testing is needed. Would you like that to be a separate PR or should I go ahead and do that now?

2024-10-08 15:17 UTC, ddaspit reviewed
You can add the tests in this PR.

> Reviewed 17 of 17 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497#-:-O8gc8TN7IbLs5TWrf-p:brfxn0i)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 134 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8NTghY4w6YrCb9s3_t:-O8gcON609FBf6Y-8TET:b-lqwoam) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L134)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Let me know if this is clear enough now.
</blockquote></details>

This is much clearer. Good job.
___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 811 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8NV3OI1fwcoVH8B0IW:-O8gd9p9DLflp8rpVnVi:b-telo9h) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L811)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I can move these but it's a bit more complicated than just moving these functions since they rely on `ParatextFile` and `TextFile` which rely on the `_tempDir` and `TestDataPath` property. Do you still want me to do that?
</blockquote></details>

It looks like you can move `TextFileCorpus`, `TextFile`, and `TestDataPath`, then you don't have to reference them by the `TestEnvironment` class name. This isn't really a big deal, so it is fine if you don't want to bother with it.
___
*[`src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs` line 5 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JapItCTyph2xeV6YC:-O8gehYv68qEu3No7A-L:b-9m4514) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Contracts/ParallelCorpusFilterConfigDto.cs#L5)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. In general, what's the pattern you're going for in Serval for when to use`...Id` vs. `...Ref`? It didn't seem wholly consistent. My impression was that we were using `Id` when it's in reference to the identifier for that object itself but `Ref`when it's referring to another object's id. Is that about it?
</blockquote></details>

We use `Id` in DTOs and `Ref` in database models. Mongo doesn't really have the concept of foreign keys like you see in SQL DBs, so I use `Ref` as a way to indicate that a field is a foreign key. There is also a class map convention that ensures that the type of `Ref` properties is an `ObjectId`.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 425 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTyHl-w76X2K1jYgu:-O8gg7UOA3w-xHq5BAFV:b-t9zs59) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L425)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

That's a good question: I didn't know what we wanted in that regard. Ultimately, I know the plan is to deprecate and then remove the old corpus functionality, but I wasn't sure if there would be a reason to allow for both on a single engine in the meantime. Maybe for testing/transitioning? I.e., make an engine that has each, run both jobs, and confirm that the behavior is the same? Or add the equivalent parallel corpus and rerun and confirm before switching things over? @johnml1135, do you have any thoughts? There will be some small changes needed either way.
</blockquote></details>

SF will need to migrate engines from the old API to the new API. During this transition, it might be simpler if engines can have both, so maybe we should just allow it for now.


<!-- Sent from Reviewable.io -->

2024-10-08 17:29 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 425 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTyHl-w76X2K1jYgu:-O8hAFZX85Y-jLrk31le:b-k31zj0) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L425)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

SF will need to migrate engines from the old API to the new API. During this transition, it might be simpler if engines can have both, so maybe we should just allow it for now.
</blockquote></details>

Since this will only be temporary functionality, I don't see why extra checks are needed.


<!-- Sent from Reviewable.io -->

2024-10-08 17:29 UTC, johnml1135 reviewed
> Reviewed 6 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-09 00:12 UTC, Enkidu93 commented
> > Reviewed 3 of 3 files at r7, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497)_ status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)
> 
> _[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 808 at r7](https://reviewable.io/reviews/sillsdev/serval/497#-O8halDm5Z1yTHMDIPSS:-O8halDm5Z1yTHMDIPST:b-ykv3s3) ([raw file](https://github.com/sillsdev/serval/blob/3357c69eb58074de9ccb30a46cc856e454d38c5f/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L808)):_
> 
> > ```smalltalk
> >     [TestCase(new[] { Scopes.UpdateTranslationEngines }, 404, DOES_NOT_EXIST_ENGINE_ID)]
> >     [TestCase(new[] { Scopes.ReadFiles }, 403, ECHO_ENGINE1_ID)] //Arbitrary unrelated privilege
> >     public async Task AddParallelCorpusToEngineByIdAsync(
> > ```
> 
> I find using test cases in this way makes the tests difficult to follow. Can you refactor these test cases into separate tests?

I know you do; I'm sorry. I only wrote them like this for consistency with the existing corpus tests - this way, they're totally parallel and we can be certain we're testing the same breadth of things. But sure, given that the non-parallel-corpus-style corpus tests will eventually be removed, I can refactor these.

2024-10-09 15:40 UTC, Enkidu93 reviewed
> Reviewed 24 of 44 files at r1, 6 of 8 files at r2, 18 of 25 files at r4, 17 of 17 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497)* status: 62 of 68 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 808 at r7](https://reviewable.io/reviews/sillsdev/serval/497#-O8halDm5Z1yTHMDIPSS:-O8lvuEW6mrYklY6zAGM:b56z6xk) ([raw file](https://github.com/sillsdev/serval/blob/3357c69eb58074de9ccb30a46cc856e454d38c5f/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L808)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I know you do; I'm sorry. I only wrote them like this for consistency with the existing corpus tests - this way, they're totally parallel and we can be certain we're testing the same breadth of things. But sure, given that the non-parallel-corpus-style corpus tests will eventually be removed, I can refactor these.
</blockquote></details>

Alrighty, done! I also added a few more tests to improve coverage. At some point, I'd like to go back and add additional testing in general.


<!-- Sent from Reviewable.io -->

2024-10-09 15:40 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497)* status: 62 of 68 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 425 at r4](https://reviewable.io/reviews/sillsdev/serval/497#-O8JTyHl-w76X2K1jYgu:-O8lw5sg63k61eAWWRoK:b-cttudf) ([raw file](https://github.com/sillsdev/serval/blob/2a6983ff37d18abdecb31a6bb8689e8f46ed549b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L425)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Since this will only be temporary functionality, I don't see why extra checks are needed.
</blockquote></details>

Alright, we should be good to go then.


<!-- Sent from Reviewable.io -->

2024-10-09 18:53 UTC, ddaspit approved these changes
Excellent work.

> Reviewed 4 of 6 files at r8, 3 of 3 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497#-:-O8mDNCh7C4hM39OJ7gy:b-3dqv3m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-09 20:24 UTC, Enkidu93 reviewed
Thank you! Sorry it was so long coming.

Yes, I'll go ahead and do that, John!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/497#-:-O8O_Yg5B7UwPKZHoTDF:b-zd01uw)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-09 21:23 UTC, merged