Add Word Alignment engine:
sillsdev/serval pull request #506
Opened 2024-10-09 16:38 UTC by johnml1135

* Add HTTP API
* Add Grpc
* Add Echo
* Add Serval services

2024-11-06 16:08 UTC, johnml1135 commented
@ddaspit - this is finally ready for review.

2025-01-24 19:07 UTC, Enkidu93 commented
I'll need to update the branch and otherwise might have some small TODOs floating around, but I think this PR is generally ready for review, @johnml1135 @ddaspit :partying_face:

2025-01-27 17:18 UTC, johnml1135 commented
*[`-- commits` line 47 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclIPE383hUmuWgvx7:-OHclIPE383hUmuWgvx8:b4t1884):*
When you get to it, can you clean up the commit message and rebase?


<!-- Sent from Reviewable.io -->

2025-01-27 17:19 UTC, johnml1135 commented
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OHclXyeAbkLEKRO7EOS:b-e6aqzt) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
> ```YAML
>       - ASPNETCORE_WordAlignment__Engines__0__Type=EchoWordAlignment
>       - ASPNETCORE_WordAlignment__Engines__0__Address=http://echo
>       - ASPNETCORE_WordAlignment__Engines__1__Type=Statistical
> ```

One general question - I called the word alignment engine "Statistical" instead of "Nmt".  I couldn't come up with a better name.


<!-- Sent from Reviewable.io -->

2025-01-27 17:21 UTC, johnml1135 commented
Rebasing will be needed - there are a number of changes that have happened that will need to be merged in.





<!-- Sent from Reviewable.io -->

2025-01-27 17:21 UTC, johnml1135 commented
*[`.github/workflows/ci.yml` line 22 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcm1Fd6efaw60lLrYD:-OHcm1Fd6efaw60lLrYE:b6m0j8d) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L22)):*
> ```YAML
>         uses: supercharge/mongodb-github-action@1.8.0
>         with:
>           mongodb-version: "6.0"
> ```

This should be "8.0"


<!-- Sent from Reviewable.io -->

2025-01-27 17:22 UTC, johnml1135 commented
*[`.github/workflows/ci.yml` line 30 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmCOd3dyyTdiuLOMe:-OHcmCOd3dyyTdiuLOMf:b-f2gdy9) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L30)):*
> ```YAML
>         continue-on-error: true
>         if: ${{ github.ref_name }} != "main"
>         run: cd .. && git clone https://github.com/sillsdev/machine.git --branch ${{ github.ref_name }} && dotnet build machine
> ```

I though this was already working.  Was something wrong with it?


<!-- Sent from Reviewable.io -->

2025-01-27 17:25 UTC, johnml1135 commented
*[`src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs` line 81 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmrT4BDHY7M6nuIR0:-OHcmrT4BDHY7M6nuIR1:bvrw7d6) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs#L81)):*
> ```Smalltalk
>                 {
>                     using (
>                         AsyncClientStreamingCall<InsertPretranslationsRequest, Empty> call =
> ```

Odd - I don't remember needing to redo the Echo translation engine much.  Was this to handle the ParallelCorpus changes?


<!-- Sent from Reviewable.io -->

2025-01-27 17:27 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.EngineServer/Program.cs` line 14 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcnQ9X4iMzIsH96Bs0:-OHcnQ9X4iMzIsH96Bs1:bp8tc07) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.EngineServer/Program.cs#L14)):*
> ```Smalltalk
>     .AddServalTranslationEngineService()
>     .AddServalWordAlignmentEngineService()
>     .AddServalTranslationPlatformService()
> ```

Do we know why the translation platform service was not enabled before?  Was it split out?


<!-- Sent from Reviewable.io -->

2025-01-27 17:37 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 203 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcpSKE59CnutfD78D6:-OHcpSKF4smF7A6DW-Og:bgc9io7) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L203)):*
> ```Smalltalk
>                 case EngineType.SmtTransfer:
>                     builder.Services.AddSingleton<SmtTransferEngineStateService>();
>                     builder.Services.AddHostedService<SmtTransferEngineCommitService>();
> ```

Just trying to remember - the "engine commit service" is all about training pairs and committing the new engine (something done in SMT but not WA).  Thot is needed for both, so it is specified separately.


<!-- Sent from Reviewable.io -->

2025-01-27 17:41 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 534 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcqMtTEMd3VeAx1Jma:-OHcqMtTEMd3VeAx1Jmb:b-79rimv) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L534)):*
> ```Smalltalk
>             throw new InvalidOperationException("SMT Engine and Statistical directory is required");
>         if (smtDriveLetter != statisticsDriveLetter)
>             throw new InvalidOperationException("SMT Engine and Statistical directory must be on the same drive");
> ```

It's a configuration limitation and duplication (having SMT and WA share the same drive), but good enough for right now.  I see no compelling reason to change it at this time.


<!-- Sent from Reviewable.io -->

2025-01-27 17:56 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcu9hX8BsYTyvKRe3Y:-OHcu9hX8BsYTyvKRe3Z:bb76mu4) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs#L7)):*
> ```Smalltalk
>     where TEngine : ITrainingEngine
> {
>     // TODO: make some sort of service to get the engine repos.
> ```

Why?


<!-- Sent from Reviewable.io -->

2025-01-27 18:12 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/IWordAlignmentModelFactory.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcxd0E322VivGuL-Lx:-OHcxd0E322VivGuL-Ly:bx49kvh) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/IWordAlignmentModelFactory.cs#L1)):*
> ```Smalltalk
> namespace Serval.Machine.Shared.Services;
> ```

Why not have this (and ISmtModelFactory) both inherit from IModelFactory?


<!-- Sent from Reviewable.io -->

2025-01-27 18:14 UTC, johnml1135 commented
Have the E2E tests been run yet?





<!-- Sent from Reviewable.io -->

2025-01-27 18:23 UTC, Enkidu93 reviewed
Yes, thank you - will do.

Yes, the E2E tests pass last time I ran them (which I believe was with this code).

> Reviewed 39 of 123 files at r3, 48 of 115 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OHcyNUd3OtNjCuOSO-A:bgr1blb)* status: 87 of 211 files reviewed, 11 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OHcyffOBz2BXlqTLgra:bpi13fv) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

One general question - I called the word alignment engine "Statistical" instead of "Nmt".  I couldn't come up with a better name.
</blockquote></details>

I'm up for whatever you think is best. Why not just call it `WordAlignment`? Because once we add AQUA it'll be confusing?
___
*[`.github/workflows/ci.yml` line 22 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcm1Fd6efaw60lLrYD:-OHcz-hyBB7Y7jnrMSrZ:b1hnbj8) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L22)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This should be "8.0"
</blockquote></details>

OK, will do
___
*[`.github/workflows/ci.yml` line 30 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmCOd3dyyTdiuLOMe:-OHcyvYR3tPqs1HMTbOO:b-cuvncm) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L30)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I though this was already working.  Was something wrong with it?
</blockquote></details>

I don't know, John. I don't remember making changes here; this wasn't part of your work, was it? 
___
*[`src/Machine/src/Serval.Machine.EngineServer/Program.cs` line 14 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcnQ9X4iMzIsH96Bs0:-OHczU1E5on3gzFeaEdF:b1e3jid) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.EngineServer/Program.cs#L14)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Do we know why the translation platform service was not enabled before?  Was it split out?
</blockquote></details>

I'm not sure. Did you author this commit or did I? :laughing: 
___
*[`src/Machine/src/Serval.Machine.Shared/Models/WordAlignment.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHctGZCAaoXEo8gAmqq:-OHczhrd9A8v0iaG0A6w:b-tb3cmy) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Models/WordAlignment.cs#L10)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So, 3 options:
A. Leave as is
B. Switch both to put confidences in "AlignedWordPair"
C. Make a new structure that just has the pairs, and not the confidences?

Currently, I am for A.
</blockquote></details>

That's totally fine. I'm not sure it's worth the change. Maybe when we make a 2.0 :)
___
*[`src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcu9hX8BsYTyvKRe3Y:-OHczo505Z8askCQ9fy7:b81rp3n) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

This was your TODO message - I left it in. I was hoping maybe you'd know why haha. 
___
*[`src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs` line 81 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmrT4BDHY7M6nuIR0:-OHczEZF1grAuR1FTXSm:b-us7lom) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs#L81)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Odd - I don't remember needing to redo the Echo translation engine much.  Was this to handle the ParallelCorpus changes?
</blockquote></details>

This looks like a place where a rebase is needed. This is what it looked like before I added the ParallelCorpus changes.


<!-- Sent from Reviewable.io -->

2025-01-27 18:31 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OHd0T_q6ie2j5_cPvcX:bx0g0in) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
> ```Smalltalk
>     }
> 
>     internal class WordAlignmentConverter : JsonConverter<Models.WordAlignment>
> ```

Check this PR out - https://github.com/sillsdev/serval/pull/592.  In it it talks about using the protobuf serialization add-on.  That may resolve issues here and remove the need for this internal class.


<!-- Sent from Reviewable.io -->

2025-01-27 19:07 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 982 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd9J4D2_izG0LCmlsF:-OHd9J4D2_izG0LCmlsG:b-pfk3pt) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.Translation/Services/EngineService.cs#L982)):*
> ```Smalltalk
>                 "Cannot specify both TextIds and ScriptureRange in the training filter."
>             );
>         }
> ```

I don't remember - was this implemented in a separate PR as well?


<!-- Sent from Reviewable.io -->

2025-01-27 19:10 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 982 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd9J4D2_izG0LCmlsF:-OHd9ZTS33JMHfd_VNv5:b-y94gd3) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.Translation/Services/EngineService.cs#L982)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I don't remember - was this implemented in a separate PR as well?
</blockquote></details>

#610 - new issue created.


<!-- Sent from Reviewable.io -->

2025-01-27 19:13 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdAZG43MYQVCqWHs5I:-OHdAZG43MYQVCqWHs5J:b5x9y66) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs#L9)):*
> ```Smalltalk
>     )
>     {
>         configurator.AddConsumer<DataFileDeletedConsumer>();
> ```

There have been some data file and corpus consumer updates to main.  We need to make sure that they get properly propagated to work alignment when merging in the changes.


<!-- Sent from Reviewable.io -->

2025-01-27 19:15 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 32 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdB7MJ3rZhNOWdOHaO:-OHdB7MJ3rZhNOWdOHaP:bh14w3d) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L32)):*
> ```Smalltalk
>                 await c.Indexes.CreateOrUpdateAsync(
>                     new CreateIndexModel<Build>(Builders<Build>.IndexKeys.Ascending(b => b.DateCreated))
>                 );
> ```

Note that when merging in main, executionData will need to be added to word alignment as well.


<!-- Sent from Reviewable.io -->

2025-01-27 19:18 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdBctcExmKiB7f7z-w:-OHdBctcExmKiB7f7z-x:b-6f3dy2) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L1)):*
> ```Smalltalk
> namespace Serval.Machine.Shared.Services;
> ```

We will need to ensure that all changes from main are faithfully propagated when rebasing, starting with #571 on Dec 12.


<!-- Sent from Reviewable.io -->

2025-01-27 19:21 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentBuildDto.cs` line 30 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdCau0-LlWJpa_e0RK:-OHdCau0-LlWJpa_e0RL:b-gfnjqz) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentBuildDto.cs#L30)):*
> ```Smalltalk
>     /// </example>
>     public object? Options { get; init; }
>     public string? DeploymentVersion { get; init; }
> ```

This will need executionData.


<!-- Sent from Reviewable.io -->

2025-01-27 19:29 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Models/Build.cs` line 20 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdEELY-yYebAxw_5XB:-OHdEELY-yYebAxw_5XC:b-vqdioc) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Models/Build.cs#L20)):*
> ```Smalltalk
>     public string? DeploymentVersion { get; init; }
>     public bool? IsInitialized { get; set; }
>     public DateTime? DateCreated { get; set; }
> ```

Needs ExecutionData.


<!-- Sent from Reviewable.io -->

2025-01-27 19:56 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Services/WordAlignmentPlatformServiceV1.cs` line 6 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdKTOf8-IM6W-LaYIH:-OHdKTOf8-IM6W-LaYII:bq3xpab) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Services/WordAlignmentPlatformServiceV1.cs#L6)):*
> ```Smalltalk
> namespace Serval.WordAlignment.Services;
> 
> public class WordAlignmentPlatformServiceV1(
> ```

ExecutionData will need to be passed up in this function.


<!-- Sent from Reviewable.io -->

2025-01-27 20:05 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 239 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdMNS303Vsmdo11puH:-OHdMNS303Vsmdo11puI:b-e1umtr) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L239)):*
> ```Smalltalk
>     }
> 
>     private static IEnumerable<(Row, bool)> CollapsePretranslateRanges(NParallelTextRow[] rows)
> ```

I don't remember this code - is this new?  Is this solving a different problem?  Can an issue be opened up describing what this is trying to solve?


<!-- Sent from Reviewable.io -->

2025-01-27 20:06 UTC, johnml1135 reviewed
> Reviewed 21 of 71 files at r1, 6 of 9 files at r2, 69 of 123 files at r3, 115 of 115 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 23 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2025-01-27 20:07 UTC, Enkidu93 commented
> _[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdBctcExmKiB7f7z-w:-OHdBctcExmKiB7f7z-x:b-6f3dy2) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L1)):_
> 
> > ```smalltalk
> > namespace Serval.Machine.Shared.Services;
> > ```
> 
> We will need to ensure that all changes from main are faithfully propagated when rebasing, starting with #571 on Dec 12.

Will do. It's an undertaking :laughing:. Starting on it now.

2025-01-27 20:08 UTC, johnml1135 commented
*[`.github/workflows/ci.yml` line 30 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmCOd3dyyTdiuLOMe:-OHdNCJ78zZ0iw-jII8z:bd0xhdo) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L30)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I don't know, John. I don't remember making changes here; this wasn't part of your work, was it?
</blockquote></details>

Ah, yes it was me.  I fixed it so it would work for matching the machine branch.


<!-- Sent from Reviewable.io -->

2025-01-27 20:09 UTC, Enkidu93 commented
> _[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 239 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdMNS303Vsmdo11puH:-OHdMNS303Vsmdo11puI:b-e1umtr) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L239)):_
> 
> > ```smalltalk
> >     }
> > 
> >     private static IEnumerable<(Row, bool)> CollapsePretranslateRanges(NParallelTextRow[] rows)
> > ```
> 
> I don't remember this code - is this new? Is this solving a different problem? Can an issue be opened up describing what this is trying to solve?

This is basically the same as the previous `CollapseRanges` function, but it's operating on `NParallelTextRow`s rather than `ParallelTextRow`s. This is to allow for the logic changes that support inferencing that requires a source and a target. I did wonder if maybe we should try and move some of this into Machine instead so that the interaction here is more straightforward.

2025-01-27 20:09 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.EngineServer/Program.cs` line 14 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcnQ9X4iMzIsH96Bs0:-OHdNWFfBkXnyTRSv9sf:b-nnjz4u) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.EngineServer/Program.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm not sure. Did you author this commit or did I? :laughing:
</blockquote></details>

I figured it out more now - I see the matching changes other places.


<!-- Sent from Reviewable.io -->

2025-01-27 20:10 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Models/WordAlignment.cs` line 10 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHctGZCAaoXEo8gAmqq:-OHdNcEx23EB2CiUgYw4:bjq6caa) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Models/WordAlignment.cs#L10)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

That's totally fine. I'm not sure it's worth the change. Maybe when we make a 2.0 :)
</blockquote></details>

Let's document it in an issue rather than a TODO then...


<!-- Sent from Reviewable.io -->

2025-01-27 20:13 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcu9hX8BsYTyvKRe3Y:-OHdO4kpD_Vs2AGMuLXn:bnjxc3i) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This was your TODO message - I left it in. I was hoping maybe you'd know why haha.
</blockquote></details>

Just take it out.  I think it was an in-process thought that is probably obsolete.


<!-- Sent from Reviewable.io -->

2025-01-27 20:14 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs` line 7 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcu9hX8BsYTyvKRe3Y:-OHdOYdH9rD6X-QeN7KU:b-e3gf5u) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/BuildJobService.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Just take it out.  I think it was an in-process thought that is probably obsolete.
</blockquote></details>

It was before all engines were templated out to TEngine.


<!-- Sent from Reviewable.io -->

2025-01-27 20:15 UTC, Enkidu93 commented
> _[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OHdMrZC0tLpu-E8Blq3:be7p60h) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):_
> Previously, Enkidu93 (Eli C. Lowry) wrote…
> 
> > I'm up for whatever you think is best. Why not just call it `WordAlignment`? Because once we add AQUA it'll be confusing?
> 
> A word alignment engine type called "word alignment"? What if we add a neural network alignment type? Statistical makes sense (what type of word alignment engines is it) I just don't know if there is a better definition. IBM?

Sorry, I see now. Yes, that would be silly haha. I didn't understand the question. I thought maybe you were referencing the name `Statistical` used elsewhere more broadly like `StatisticalEngineService`, `StatisticalTrainBuildJob`, etc. which I do think might benefit from being named something like `StatisticalWordAlignmentEngineService` etc.

2025-01-27 20:17 UTC, johnml1135 commented
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OHdPKD84r9Wzcyw3NF0:b-2oh0d3) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry, I see now. Yes, that would be silly haha. I didn't understand the question. I thought maybe you were referencing the name `Statistical` used elsewhere more broadly like `StatisticalEngineService`, `StatisticalTrainBuildJob`, etc. which I do think might benefit from being named something like `StatisticalWordAlignmentEngineService` etc.
</blockquote></details>

More words... My instinct is to let @ddaspit pass the deciding vote.


<!-- Sent from Reviewable.io -->

2025-01-27 20:20 UTC, Enkidu93 commented
> _[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 239 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdMNS303Vsmdo11puH:-OHdOxS80Uae-jpzG8-F:b-auax3i) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L239)):_
> Previously, Enkidu93 (Eli C. Lowry) wrote…
> 
> Why is it needed in this PR? Was it missed before?

Because it's new to word alignment. Previously, inferencing only required source data, but now it requires source and target (since the inference is a word alignment, not a translation), so the data preprocessing and include/exclude logic has to look a little different. This was the cleanest way that came to mind for me to keep the logic for pretranslation while make the logic make sense for word alignment.

2025-01-27 21:11 UTC, ddaspit reviewed
Is this ready to be reviewed now?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OHdahu_0Y_1j2igInNU:b8hmtak)* status: all files reviewed, 23 unresolved discussions (waiting on @Enkidu93 and @johnml1135)



<!-- Sent from Reviewable.io -->

2025-01-27 21:17 UTC, Enkidu93 commented
> Is this ready to be reviewed now?
> 
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OHdahu_0Y_1j2igInNU:b8hmtak)_ status: all files reviewed, 23 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

It's up to you. Things are working E2E - the main thing left to do is a lot of rebasing. If you'd like to look at it now, you're welcome to; or if you'd rather wait until the rebasing is done, that's fine too.

2025-01-29 15:51 UTC, Enkidu93 commented
(If something looks weird in the commit history, I tried using a rebase command through the VSCode GUI and it did something unexpected :grimacing::laughing:) Working on rebasing properly now.

2025-01-29 21:34 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 178 of 224 files reviewed, 23 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 982 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd9J4D2_izG0LCmlsF:-OHnyWrT6YcTXEOBdSB8:bsb4m44) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.Translation/Services/EngineService.cs#L982)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

#610 - new issue created.
</blockquote></details>

Is this case covered in `TranslationEnginesController`, line 1484:

```
    private static ParallelCorpusFilter Map(ParallelCorpusFilterConfigDto source)
    {
        if (source.TextIds != null && source.ScriptureRange != null)
        {
            throw new InvalidOperationException(
                $"The parallel corpus filter for corpus {source.CorpusId} is not valid: At most, one of TextIds and ScriptureRange can be set."
            );
        }
...
```


<!-- Sent from Reviewable.io -->

2025-01-31 14:46 UTC, johnml1135 commented
*[`-- commits` line 76 at r8](https://reviewable.io/reviews/sillsdev/serval/506#-OHwoztZ6CQSXPju9i82:-OHwozt_-iBmeeOqMXAU:bxqzolm):*
Is it ready now?


<!-- Sent from Reviewable.io -->

2025-01-31 15:06 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 161 of 225 files reviewed, 24 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 76 at r8](https://reviewable.io/reviews/sillsdev/serval/506#-OHwoztZ6CQSXPju9i82:-OHwtF_P6MfMNPEW1Byy:b-f55rzy):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Is it ready now?
</blockquote></details>

Yes, still working on responding to comments here and on the Machine PR, but some things have already been addressed and the rebase has been done. @ddaspit @johnml1135 


<!-- Sent from Reviewable.io -->

2025-02-03 16:11 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 158 of 227 files reviewed, 14 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 47 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclIPE383hUmuWgvx7:-OIBZl1r2Z64ak8tTtj0:b-8fx2u7):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

When you get to it, can you clean up the commit message and rebase?
</blockquote></details>

:+1: 
___
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OIB_1MQ6uxtfq2yabrN:b714rn8) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

More words... My instinct is to let @ddaspit pass the deciding vote.
</blockquote></details>

OK, I'm happy either way.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/IWordAlignmentModelFactory.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcxd0E322VivGuL-Lx:-OIBVm4bDyHmd6Ccpr3G:bfg8tg7) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/IWordAlignmentModelFactory.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why not have this (and ISmtModelFactory) both inherit from IModelFactory?
</blockquote></details>

Done. I don't know - not sure if I did that or you :laughing: 
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OIBVwgz6K37T7PvSdGB:bcjdxcz) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Check this PR out - https://github.com/sillsdev/serval/pull/592.  In it it talks about using the protobuf serialization add-on.  That may resolve issues here and remove the need for this internal class.
</blockquote></details>

I think it's the AlignedWordPair string parsing that's key, and I don't think the protobuf serialization add-on would cover that / could be adapted to cover that - can it?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineStateService.cs` line 46 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd594q-vlk5za1yFqB:-OIBWMyq55Dcnpc675w-:b-x53xv0) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineStateService.cs#L46)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Wait - "commit" will never write to disk...  Is this the right way to handle this?
</blockquote></details>

I think this has been fixed. Lmk.
___
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdAZG43MYQVCqWHs5I:-OIBWTFN2klZymZKy5Zc:b-d1owtu) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs#L9)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

There have been some data file and corpus consumer updates to main.  We need to make sure that they get properly propagated to work alignment when merging in the changes.
</blockquote></details>

I believe these have been carried over. I went back through the PRs since December and tried to carry over any changes. Let me know if it looks like I missed something.
___
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 32 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdB7MJ3rZhNOWdOHaO:-OIBXM267JD7hN3K6QqT:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Note that when merging in main, executionData will need to be added to word alignment as well.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentBuildDto.cs` line 30 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdCau0-LlWJpa_e0RK:-OIBY3o44aSoZtXGxtIq:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentBuildDto.cs#L30)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This will need executionData.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Models/Build.cs` line 20 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdEELY-yYebAxw_5XB:-OIBY5_L93XdHBwIh43N:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Models/Build.cs#L20)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Needs ExecutionData.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Services/BuildService.cs` line 16 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdIE98EG6_JFY_mb8t:-OIBZT8t6mXD2yYt6RN8:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Services/BuildService.cs#L16)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

The Translation "BuildService" has GetAsync - checking whether it is initialized or not.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Services/WordAlignmentPlatformServiceV1.cs` line 6 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdKTOf8-IM6W-LaYIH:-OIBZboo6unWhnn-Kbat:b-n25tbo) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Services/WordAlignmentPlatformServiceV1.cs#L6)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

ExecutionData will need to be passed up in this function.
</blockquote></details>

Done. I think.


<!-- Sent from Reviewable.io -->

2025-02-03 19:39 UTC, Enkidu93 reviewed
@ddaspit, @johnml1135, I believe I've responded to all comments and that this PR is ready for re-review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OICJdnr6VhX1FRdz7aO:b-nrdubk)* status: 154 of 227 files reviewed, 14 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-03 19:49 UTC, johnml1135 commented
*[`-- commits` line 76 at r8](https://reviewable.io/reviews/sillsdev/serval/506#-OHwoztZ6CQSXPju9i82:-OICLzXd4NJfu09F262H:b-a4dh8q):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Yes, still working on responding to comments here and on the Machine PR, but some things have already been addressed and the rebase has been done. @ddaspit @johnml1135
</blockquote></details>

Can you squash most of these commits?  They all appear doubled - and a simple 2 commit "John gave me this and then I made these changes" is often helpful.


<!-- Sent from Reviewable.io -->

2025-02-03 19:50 UTC, johnml1135 commented
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OICMHfS-5wggbUGNzWD:b5hcurj) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, I'm happy either way.
</blockquote></details>

Without a vote from Damien, I am assuming to stay with Statistical.


<!-- Sent from Reviewable.io -->

2025-02-03 19:52 UTC, johnml1135 commented
*[`src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs` line 81 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmrT4BDHY7M6nuIR0:-OICMknCEMcot73Lek8F:b-7h7uei) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs#L81)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This looks like a place where a rebase is needed. This is what it looked like before I added the ParallelCorpus changes.
</blockquote></details>

This has still not been resolved, if I am correct.


<!-- Sent from Reviewable.io -->

2025-02-03 19:54 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 108 at r11](https://reviewable.io/reviews/sillsdev/serval/506#-OICNAte0UCalGAPPV5H:-OICNAte0UCalGAPPV5I:br5e8c3) ([raw file](https://github.com/sillsdev/serval/blob/49b1260166f26f8f8dffb7bbd4ad30828ee3bf1d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L108)):*
> ```Smalltalk
>     }
> 
>     //TODO: Move this method to translation-specific PreprocessBuildJob
> ```

Hanging TODO...


<!-- Sent from Reviewable.io -->

2025-02-03 20:19 UTC, johnml1135 commented
*[`src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs` line 81 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmrT4BDHY7M6nuIR0:-OICSxJABQdQhHniToUK:b-tatwal) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs#L81)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This has still not been resolved, if I am correct.
</blockquote></details>

Never mind.


<!-- Sent from Reviewable.io -->

2025-02-03 20:23 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 135 of 227 files reviewed, 15 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 76 at r8](https://reviewable.io/reviews/sillsdev/serval/506#-OHwoztZ6CQSXPju9i82:-OICTSMW57spnSI-e9bC:b-dvg1e7):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Can you squash most of these commits?  They all appear doubled - and a simple 2 commit "John gave me this and then I made these changes" is often helpful.
</blockquote></details>

Sorry the commit messages are still messy I'm realizing - I can fix that if you'd like. It is squashed though.
___
*[`.github/workflows/ci.yml` line 22 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcm1Fd6efaw60lLrYD:-OICN1-f5LpxjUd9VP2W:b-2m8dg3) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/.github/workflows/ci.yml#L22)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This has not been updated.
</blockquote></details>

Oops, sorry - done!
___
*[`src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs` line 81 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHcmrT4BDHY7M6nuIR0:-OICTen7B4mLtLnSVZvr:bmukyw5) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Echo/src/EchoEngine/TranslationEngineServiceV1.cs#L81)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Never mind.
</blockquote></details>

No, I think you're right. This should be using the `ParallelCorpusPreprocessingService`. I just lost track of this thread since I had responded - sorry!


<!-- Sent from Reviewable.io -->

2025-02-03 20:28 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 135 of 227 files reviewed, 15 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 76 at r8](https://reviewable.io/reviews/sillsdev/serval/506#-OHwoztZ6CQSXPju9i82:-OICUxcX0D_B3_FiyvlM:bp1fmwd):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry the commit messages are still messy I'm realizing - I can fix that if you'd like. It is squashed though.
</blockquote></details>

Cleaned it up a bit.


<!-- Sent from Reviewable.io -->

2025-02-03 21:36 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OICj1Ds7qs-SmZpGWON:bs9o82d) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I think it's the AlignedWordPair string parsing that's key, and I don't think the protobuf serialization add-on would cover that / could be adapted to cover that - can it?
</blockquote></details>

Options:
A. Keep as is.
B. Move the parsing of AlignedWordPair to the MachineEngine and pass the data back to serval in the non-string format
C. Preserve the data in Serval in the "string" format

My best guess is to go with option B - convert in machine-engine before it goes over GRPC (probably as the message is enqueued to be sent in the outbox).  That might be cleanest - having the"knowledge" of how to parse that type of word alignment string be in the lower statistical level. 


<!-- Sent from Reviewable.io -->

2025-02-03 22:00 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineState.cs` line 68 at r15](https://reviewable.io/reviews/sillsdev/serval/506#-OICoY2Z7FeFI4pJUjmG:-OICoY2Z7FeFI4pJUjmH:b-qfwto2) ([raw file](https://github.com/sillsdev/serval/blob/6da569a9133ebbdb6de5eb0fae053b4fcc42208d/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineState.cs#L68)):*
> ```Smalltalk
>             CurrentBuildRevision = buildRevision;
> 
>         SaveModel();
> ```

If I am correct, the training of the model (either in ClearML or dotnet) is separate from this.  Also, we do not "update" this model. but only the SMT model.  Therefore. we have no reason to actually "save" the model at any time, as it is never updated unless it is retrained with a new build.


<!-- Sent from Reviewable.io -->

2025-02-04 13:08 UTC, johnml1135 commented
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs` line 9 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdAZG43MYQVCqWHs5I:-OIG3dZSDyUU_Gf3__WP:b8skrbv) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Serval/src/Serval.WordAlignment/Configuration/IMediatorRegistrationConfiguratorExtensions.cs#L9)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I believe these have been carried over. I went back through the PRs since December and tried to carry over any changes. Let me know if it looks like I missed something.
</blockquote></details>

It looks like everything is good.


<!-- Sent from Reviewable.io -->

2025-02-04 13:09 UTC, johnml1135 reviewed
> Reviewed 8 of 27 files at r6, 1 of 48 files at r7, 1 of 23 files at r9, 59 of 59 files at r14, 24 of 24 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2025-02-06 15:49 UTC, Enkidu93 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 108 at r11](https://reviewable.io/reviews/sillsdev/serval/506#-OICNAte0UCalGAPPV5H:-OIMwa4t2BbnrXvgMROW:b-dy7bzi) ([raw file](https://github.com/sillsdev/serval/blob/49b1260166f26f8f8dffb7bbd4ad30828ee3bf1d/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L108)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Hanging TODO...
</blockquote></details>

Thank you. I'll remove it and create an issue.


<!-- Sent from Reviewable.io -->

2025-02-07 13:48 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdBctcExmKiB7f7z-w:-OIVejLF-cqe5qn_UPnT:b5bdjdt) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L1)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Will do. It's an undertaking :laughing:. Starting on it now.
</blockquote></details>

Eli - I believe that you have completed this - is that correct?


<!-- Sent from Reviewable.io -->

2025-02-07 13:49 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OIVerxI9uq0fD_uhV1G:b3nm5al) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Options:
A. Keep as is.
B. Move the parsing of AlignedWordPair to the MachineEngine and pass the data back to serval in the non-string format
C. Preserve the data in Serval in the "string" format

My best guess is to go with option B - convert in machine-engine before it goes over GRPC (probably as the message is enqueued to be sent in the outbox).  That might be cleanest - having the"knowledge" of how to parse that type of word alignment string be in the lower statistical level.
</blockquote></details>

What have you decided with this?


<!-- Sent from Reviewable.io -->

2025-02-07 20:14 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 225 of 227 files reviewed, 3 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHdBctcExmKiB7f7z-w:-OIX1RFz5JnkCuLNQChu:b-xkxqwx) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Eli - I believe that you have completed this - is that correct?
</blockquote></details>

I believe so, yes.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OIMxX1P7X4LnDtT82SB:b-qgu1pv) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What have you decided with this?
</blockquote></details>

Sorry - I had drafted a message and apparently it hadn't sent. I originally agreed that B would be cleaner, but now I'm thinking that it'd be better if possible just to store the word pairs in a more JSONy way coming out of the machine.py job itself. How does that strike you?


<!-- Sent from Reviewable.io -->

2025-02-10 15:48 UTC, Enkidu93 reviewed
I've fixed the out-of-date parallel corpus preprocessing in the EchoEngine. I think the last outstanding issue is the parsing of the alignments. Options are: 1. Change the output of the machine.py job to be a proper JSONification of the aligned word pairs (rather than the string representation). 2. Leave as is (convert them at serialization in Serval). 3. Parse the strings at the MachinEngine-level while passing on the inference stream.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OIkWYEi51GimjEmbsD-:b-4s5gg8)* status: 195 of 227 files reviewed, 2 unresolved discussions (waiting on @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineState.cs` line 68 at r15](https://reviewable.io/reviews/sillsdev/serval/506#-OICoY2Z7FeFI4pJUjmG:-OIkWCzPCTRWTb8U2oU5:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/6da569a9133ebbdb6de5eb0fae053b4fcc42208d/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentEngineState.cs#L68)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If I am correct, the training of the model (either in ClearML or dotnet) is separate from this.  Also, we do not "update" this model. but only the SMT model.  Therefore. we have no reason to actually "save" the model at any time, as it is never updated unless it is retrained with a new build.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-10 19:24 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OIlGi-y1QVjHfMryRGi:bu6q84b) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Sorry - I had drafted a message and apparently it hadn't sent. I originally agreed that B would be cleaner, but now I'm thinking that it'd be better if possible just to store the word pairs in a more JSONy way coming out of the machine.py job itself. How does that strike you?
</blockquote></details>

Hmm - as long as the old format is still able to be created - non breaking API.  The "alignment format" that is used I believe is a "standard" of sorts and I would expect people to be able to get that format out   If a "to_json" routine were added (or similar) I would be ok with it.

I generally like things to be super-compact and Json would be less compact than the existing format.  My biggest concern would be the readability of the Json format - where something like `1:1:0.5 2:2:0.25 3:3:0.75` becomes:
```
[
  [
    "sourceIndex": 1,
    "targetIndex": 1,
    "alignmentScore": 0.5,
  ],
  [
    "sourceIndex: 2, ...
```
It would expand the total amount of data 5-10 fold and take 50-100 times as many lines.

If there is a better way around this issue, I am all ears.  Potentially it could be something like:
```
[
  [
    "SourceTokens": ["hello", "world"],
    "TargetTokens": ["hola", "mundo"],
    "SourceTargetScore": [ (1, 1, 0.5), (2, 2, 0.75) ],
  ], ...
```

That would allow the "extra text" to be less, and keep the extra lines under control while maintaining visual flow and needing no custom parsing.  The scores could be floats (as above) or some int16 scaled so that 65,535 = 1.0, or some such thing.


<!-- Sent from Reviewable.io -->

2025-02-10 19:26 UTC, johnml1135 commented
See comment below.





<!-- Sent from Reviewable.io -->

2025-02-14 22:14 UTC, ddaspit requested changes
> Reviewed 20 of 83 files at r1, 6 of 9 files at r2, 58 of 136 files at r3, 49 of 116 files at r4, 8 of 27 files at r6, 1 of 23 files at r9, 53 of 59 files at r14, 2 of 2 files at r16, 30 of 30 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 57 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OJ-sHHq0qaOr6sKxh4j:bfi2bhv) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Without a vote from Damien, I am assuming to stay with Statistical.
</blockquote></details>

I'm good with "Statistical". I don't think there is a better option. I have a small concern that Eflomal might not fit into the current word alignment model that was designed around IBM models. Eflomal is still a statistical model, it is Bayesian as opposed to frequentist.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OJ5RgCt6rVfmHpCWgfJ:bfvs7o) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Hmm - as long as the old format is still able to be created - non breaking API.  The "alignment format" that is used I believe is a "standard" of sorts and I would expect people to be able to get that format out   If a "to_json" routine were added (or similar) I would be ok with it.

I generally like things to be super-compact and Json would be less compact than the existing format.  My biggest concern would be the readability of the Json format - where something like `1:1:0.5 2:2:0.25 3:3:0.75` becomes:
```
[
  [
    "sourceIndex": 1,
    "targetIndex": 1,
    "alignmentScore": 0.5,
  ],
  [
    "sourceIndex: 2, ...
```
It would expand the total amount of data 5-10 fold and take 50-100 times as many lines.

If there is a better way around this issue, I am all ears.  Potentially it could be something like:
```
[
  [
    "SourceTokens": ["hello", "world"],
    "TargetTokens": ["hola", "mundo"],
    "SourceTargetScore": [ (1, 1, 0.5), (2, 2, 0.75) ],
  ], ...
```

That would allow the "extra text" to be less, and keep the extra lines under control while maintaining visual flow and needing no custom parsing.  The scores could be floats (as above) or some int16 scaled so that 65,535 = 1.0, or some such thing.
</blockquote></details>

I'm fine with this approach. The confidences can be passed in the alignment string. We will probably need to update the `AlignedWordPair.Parse` method to populate the scores.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 29 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ59axzB1JtcPU0Ia0Y:-OJ59axzB1JtcPU0Ia0Z:bdmee6j) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L29)):*
> ```Smalltalk
>     private readonly Dictionary<string, ProgressStatus> _curBuildStatus = new();
> 
>     private readonly IReadOnlyDictionary<string, string> _queuePerEngineType =
> ```

Why aren't we using the `EngineType` enum here?
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/ClearMLBuildQueue.cs` line 5 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ50XgLBnh8C7Dl5wCc:-OJ50XgLBnh8C7Dl5wCd:bvkipj7) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/ClearMLBuildQueue.cs#L5)):*
> ```Smalltalk
> public class ClearMLBuildQueue
> {
>     public string EngineType { get; set; } = "";
> ```

Shouldn't this be `EngineType`?
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-qIH-JTLTl67UvPS:-OJ5-qIH-JTLTl67UvPT:bnrvd8g) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs#L3)):*
> ```Smalltalk
> namespace Serval.Machine.Shared.Configuration;
> 
> public class WordAlignmentEngineOptions
> ```

This should be named `StatisticalWordAlignmentEngineOptions`.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 203 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ52iNsCfvVhwZyJdKb:-OJ52iNsCfvVhwZyJdKc:b5n74mg) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L203)):*
> ```Smalltalk
>                 case EngineType.SmtTransfer:
>                     builder.Services.AddSingleton<SmtTransferEngineStateService>();
>                     builder.Services.AddHostedService<SmtTransferEngineCommitService>();
> ```

I would prefer not to add the commit service on the Hangfire server, since the Hangfire could be scaled horizontally.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 271 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ51U149WknQ7uGSf16:-OJ51U149WknQ7uGSf17:b5qbzqo) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L271)):*
> ```Smalltalk
>                 o.AddRepository<WordAlignmentEngine>(
>                     "word_alignment_engines",
>                     mapSetup: m => m.SetIgnoreExtraElements(true),
> ```

Why are we ignoring extra elements?
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 453 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ53HLD4avdMOlgK-0H:-OJ53HLD4avdMOlgK-0I:b-i7323c) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L453)):*
> ```Smalltalk
>                     break;
>                 default:
>                     throw new ArgumentOutOfRangeException(engineType.ToString());
> ```

You should use `InvalidEnumArgumentException`.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 497 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ513Yv4tGPNy7BbU8g:-OJ513Yv4tGPNy7BbU8h:b6r4y65) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L497)):*
> ```Smalltalk
>         try
>         {
>             builder.AddThotSmtModel().AddTransferEngine().AddUnigramTruecaser().AddWordAlignmentModel();
> ```

This should be separated into two calls: one for SMT and one for word alignment.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentModelOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-jkH-WBpfVlO0HTp:-OJ5-jkI8-y4vELEOcaZ:b4aaot3) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentModelOptions.cs#L3)):*
> ```Smalltalk
> namespace Serval.Machine.Shared.Configuration;
> 
> public class WordAlignmentModelOptions
> ```

This should be named `ThotWordAlignmentModelOptions`.
___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5 [...]

2025-02-17 14:07 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5TPFR8lqoXLPTVG1E:-OJJDyff8ZtjoQrmqPVg:bmj6iws) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs#L81)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It shouldn't be necessary to call `ComputeAlignedWordPairScores`.
</blockquote></details>

If I remember correctly, just getting the best aligned word pairs does not calculate/return a score, but it needs to be populated separately.  @Enkidu93 - can you check that out?


<!-- Sent from Reviewable.io -->

2025-02-17 14:17 UTC, johnml1135 commented
@Enkidu93 - I gave a once over on Damien's comments and commented where I thought it was needed.





<!-- Sent from Reviewable.io -->

2025-02-17 15:26 UTC, Enkidu93 reviewed
Thank you, John & Damien. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OJJW0gp0wIVW1eSaKlv:b-ky9ldh)* status: all files reviewed, 57 unresolved discussions (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-17 17:01 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 202 of 230 files reviewed, 57 unresolved discussions (waiting on @ddaspit, @Enkidu93, and @johnml1135)

___
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OJJmw0DEUgwhJSLDqRU:bf7bazh) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm good with "Statistical". I don't think there is a better option. I have a small concern that Eflomal might not fit into the current word alignment model that was designed around IBM models. Eflomal is still a statistical model, it is Bayesian as opposed to frequentist.
</blockquote></details>

OK. Yeah, we might need to refactor a bit to accommodate eflomal. Cross that bridge when we come to it?
___
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 43 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ50BKJ3O3o31DlkTZZ:-OJJX_-g65wn_02QLYWm:bokc8kc) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What is this reference needed for?
</blockquote></details>

It's not needed :D. Removed. 
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 203 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ52iNsCfvVhwZyJdKb:-OJJZs_62kwI7RH86Ax_:b9l3mvn) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L203)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would prefer not to add the commit service on the Hangfire server, since the Hangfire could be scaled horizontally.
</blockquote></details>

Done. @johnml1135, if you had a particular reason for doing this, I'll let you argue for it. Otherwise, I've reverted it.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 271 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ51U149WknQ7uGSf16:-OJJ_YaxBAX2Z2Rhg9gC:b-7ncshx) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L271)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why are we ignoring extra elements?
</blockquote></details>

I'm assuming that that was just a copy-paste error since it's there for translation engines to support some data reorganization you did when refactoring build jobs a long time ago. Removed.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 453 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ53HLD4avdMOlgK-0H:-OJJaTLQ93jnxHMPPVni:bctpdcc) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L453)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should use `InvalidEnumArgumentException`.
</blockquote></details>

Makes sense. Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 497 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ513Yv4tGPNy7BbU8g:-OJJaeuQ-G935l8ualyl:b9ikpkq) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L497)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be separated into two calls: one for SMT and one for word alignment.
</blockquote></details>

Is this what you mean? Or make two separate functions entirely?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 29 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ59axzB1JtcPU0Ia0Y:-OJJbcvn5g4b4bwjU7ug:b-ybg5a2) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L29)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why aren't we using the `EngineType` enum here?
</blockquote></details>

That's a great question haha. I changed it to use `EngineType`. 
___
*[`src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs` line 26 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5EN0h-bYxAvxLsVst:-OJJc0y3DDxgbOemUdr7:b1z3zbe) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs#L26)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't love the name of this method. Maybe `InsertInferenceResultsAsync`.
</blockquote></details>

OK, sounds good.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 89 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5FSB82YTPgCP2uXx4:-OJJcTi97_2MMJmnC6Y4:b-4k6owl) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L89)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It probably isn't a huge deal, but I don't really like that this doesn't match the name of the inference results for each engine type, i.e. pretranslation or word alignment. It is also kind of a breaking change. If we could fix that, it would be great. Also, this should probably be called `inferenceCount`.
</blockquote></details>

I agree. I have issue out that I think is relevant: https://github.com/sillsdev/serval/issues/617. Should I just go ahead and do that now then?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs` line 84 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5Gc_p-rgkif7UU7_M:-OJJdWd3EBfjFNoRSSva:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs#L84)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should probably throw if `content` is required.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OIkWNhi4DLrVvoI05gY:bqcdav7) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm fine with this approach. The confidences can be passed in the alignment string. We will probably need to update the `AlignedWordPair.Parse` method to populate the scores.
</blockquote></details>

Just to clarify: You're fine with the approach already coded in this PR currently?

Do you positively want the confidences passed in the string? Or how is that connected to the rest of this thread? I had put in a TODO/comment which I've since removed because it also seemed awkward to me that the confidences are passed separately from the word pairs. However, that is the way that the word pairs are being handle [...]

2025-02-17 17:06 UTC, Enkidu93 reviewed
Sorry, Damien, I responded to some comments but missed a lot of others - I have this issue with Reviewable sometimes that I just haven't figured out. If you answered a question I asked in another comment, don't worry about responding. Working through the rest now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OJJrk7N3aHh1KZ-FUfJ:b-31xndu)* status: 202 of 227 files reviewed, 57 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-17 21:44 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 202 of 227 files reviewed, 57 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJKTJbB6FIRLjuJTAo8:b-eetdjt) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `EchoEngine`, `Serval.WordAlignment`, and `Serval.WordAlignment.Tests` are in the wrong solution folder.
</blockquote></details>

In what way? It's not clear to me that they aren't, but my IDE doesn't interact as cleanly with the solution file. 
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/ClearMLBuildQueue.cs` line 5 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ50XgLBnh8C7Dl5wCc:-OJKTyLE8ztAcgbPwo5H:b60r506) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/ClearMLBuildQueue.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Shouldn't this be `EngineType`?
</blockquote></details>

Yes, done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-qIH-JTLTl67UvPS:-OJKUIRp9u8huLJFNfWd:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `StatisticalWordAlignmentEngineOptions`.
</blockquote></details>

Done
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentModelOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-jkH-WBpfVlO0HTp:-OJKUZhwB1rMfLGk9yGJ:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentModelOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be named `ThotWordAlignmentModelOptions`.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/EngineType.cs` line 18 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ50S603r2fhNM9_zTO:-OJKVkSJ5JMj1bj1XbGb:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/EngineType.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make this an extension method.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/IBuildJobServiceBase.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5B2Dh0NsTU66ftOzL:-OJKWUim3ryxNtVFwOm9:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/IBuildJobServiceBase.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this to `IBuildJobService` and move this to the `IBuildJobService.cs` file.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ModelFactoryBase.cs` line 19 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5WIS510v2h-AaE1Cl:-OJKYzFp4AmiZhNwQOpI:bphieyx) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ModelFactoryBase.cs#L19)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This will need to be implemented separately for each engine type.
</blockquote></details>

Done - although this might need to change if a cfg can be specified
___
*[`src/Machine/src/Serval.Machine.Shared/Services/NmtEngineService.cs` line 14 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5DWCQ5HWHUVw5MyWN:-OJKgccUDqk28y-CSZ5I:b-5h8kv3) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/NmtEngineService.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

ASP.NET Core now supports keyed services in DI.
</blockquote></details>

Yay! Done.
___
*[`src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto` line 15 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ-yGe27-OYebhQmK09:-OJKmKD40l9TjZlIJGHj:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto#L15)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This name is kind of weird now. Maybe we can rename this to `IncrementEngineCorpusSize`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Grpc/Protos/serval/word_alignment/v1/platform.proto` line 17 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ-yyjLCS-Xz_gmZh-r:-OJKmLo758MZ1DdkxZ8k:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.Grpc/Protos/serval/word_alignment/v1/platform.proto#L17)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my comment on `TranslationPlatformApi`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/using.cs` line  at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ02elhEmb64VAOzCMZ:-OJKnJrD3yxWjLferJB8:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/using.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This file should be called `Usings.cs`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 34 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ4wBFb6W_vEOn8KXEY:-OJKnSPPAzS4-adeqElO:bjg6x97) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we need this.
</blockquote></details>

Yep. Done.
___
*[`src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentParallelCorpusConfigDto.cs` line 10 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ4uW1c8XGPCC6INCR-:-OJKnc6sBqwY-Zs_6tRd:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/Contracts/WordAlignmentParallelCorpusConfigDto.cs#L10)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The default value isn't necessary.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Controllers/WordAlignmentEnginesController.cs` line 166 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ04lVCAByr7Zt12zzN:-OJKnoDJ6GOfqFdzLNkU:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/Controllers/WordAlignmentEnginesController.cs#L166)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would rename this endpoint to `align`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.WordAlignment/Models/TrainingCorpus.cs` l [...]

2025-02-18 16:42 UTC, ddaspit reviewed
> Reviewed 8 of 25 files at r18, 53 of 53 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 15 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJOuK8d6VaNoxi_Tjr4:b7el252) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

In what way? It's not clear to me that they aren't, but my IDE doesn't interact as cleanly with the solution file.
</blockquote></details>

If you open the project in Visual Studio, you will see that it is incorrect. Do you have access to Visual Studio? Should I fix it?
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 497 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ513Yv4tGPNy7BbU8g:-OJOjbj51Qij7ScO-zb4:b17isbp) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L497)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is this what you mean? Or make two separate functions entirely?
</blockquote></details>

I mean they should be two separate functions. If we separate word alignment and translation into two separate instances, then we would be unnecessarily adding services that aren't needed.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 89 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5FSB82YTPgCP2uXx4:-OJOudgr9LN19K66geHa:b4aipki) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L89)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I agree. I have issue out that I think is relevant: https://github.com/sillsdev/serval/issues/617. Should I just go ahead and do that now then?
</blockquote></details>

As long as we have an issue to capture the issue and plan on fixing it before release, we don't need to do it now.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OJOnDFm5oLYz3phdkO2:br6zxmr) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Just to clarify: You're fine with the approach already coded in this PR currently?

Do you positively want the confidences passed in the string? Or how is that connected to the rest of this thread? I had put in a TODO/comment which I've since removed because it also seemed awkward to me that the confidences are passed separately from the word pairs. However, that is the way that the word pairs are being handled on the translation side already :shrug:.
</blockquote></details>

Yes, I'm referring to the already implemented approach. I think we should pass the confidence inside each word pair. On the translation side, the confidences are for each target token, which are strings, so we have to pass them separately.  
___
*[`src/Serval/src/Serval.WordAlignment/Models/WordAlignment.cs` line 14 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ4r4Tw9lTFGzej2mN-:-OJOuvgD4E-6wUoczw-g:bwh7br4) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/Models/WordAlignment.cs#L14)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I agree. What about on the translation side though?
</blockquote></details>

See my comment elsewhere about why the translation side is different.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-qIH-JTLTl67UvPS:-OJOkS8G1l0nz3WUUzxp:b1etntp) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs#L3)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Actually, I was wrong. It should be named `StatisticalEngineOptions` to be consistent with the naming of other classes related to the statistical word alignment engine.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs` line 84 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5Gc_p-rgkif7UU7_M:-OJOm0I37W208EMabwJY:b-yrwiw7) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs#L84)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Once you add the null check, you shouldn't need the null-forgiving operators anymore.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs` line 12 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5MdwXAMHDiwNCDdZY:-OJOsdg484ctyfEndvN1:b-yjjmkw) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs#L12)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Could you point me to an example of this? This is similar to 
```
string smtConfigFileName = Path.Combine(engineDir, "smt.cfg");

ITrainer trainer = new ThotSmtModelTrainer(ThotWordAlignmentModelType.Hmm, corpus, smtConfigFileName)
```
in SMT?
</blockquote></details>

See the `AlignmentModelCommandSpec.CreateWordAlignmentModel` method in `SIL.Machine.Tool`.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs` line 28 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5MovA9acd8VDePWDi:-OJOs-FcByviPZzIJ293:bllsa3z) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs#L28)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Do you mean via the `build_options` in the Serval API or the `WordAlignmentOptions` (or similar)? There isn't something similar for SMT, is there?
</blockquote></details>

I was referring to the `build_options` from the Serval API. We need some way to allow the calling application to choose what type of statistical word alignment model they want to use based on their needs. `build_options` seems the best way. This isn't as necessary for SMT, since the word alignment model that is used doesn't have a large impact on the quality of the model.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs` line 5 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOko_j-xubImlA1HG5:-OJOko_j-xubImlA1HG6:b-58p3pb) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs#L5)):*
> ```Smalltalk
> public class StatisticalWordAlignmentEngineOptions
> {
>     public const string Key = "WordAlignmentEngine";
> ```

You forgot to update the `Key` to match the name change.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformO [...]

2025-02-19 22:54 UTC, Enkidu93 reviewed
I'll follow up with more changes tomorrow, but here's a batch/progress.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OJVPl74-F7YQXe7Ss-R:b-zbjttq)* status: all files reviewed, 16 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJTteRk8rL3sId3NsgJ:bp681a8) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If you open the project in Visual Studio, you will see that it is incorrect. Do you have access to Visual Studio? Should I fix it?
</blockquote></details>

I don't have access to Visual Studio, no. John and I both use VSCode. There has to be an extension though, I bet. @johnml1135? If you could do it, that might be the most straightforward in the near term.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 497 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ513Yv4tGPNy7BbU8g:-OJTv3nf7nGTpETeuLIY:b-yg3z88) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L497)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I mean they should be two separate functions. If we separate word alignment and translation into two separate instances, then we would be unnecessarily adding services that aren't needed.
</blockquote></details>

That makes more sense. Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 22 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOkIhqCtMmECSaCgPk:-OJTu4WO4VrqystaZ8du:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L22)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to rename this method to match the class name change.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 455 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOjQvV5XPptVxY6Xio:-OJTuWjvAAETM0z7jvfH:b-tnq5kv) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L455)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The first parameter should be `nameof(engineType)`.
</blockquote></details>

Oh, yes, thank you!
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 89 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5FSB82YTPgCP2uXx4:-OJTvqMq1a4IUz9zSpkZ:b-ocwcl4) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L89)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

As long as we have an issue to capture the issue and plan on fixing it before release, we don't need to do it now.
</blockquote></details>

OK, so I guess that's more John's call then: @johnml1135, would you rather I just get this PR through and then immediately follow up with the above or just do it a part of this PR? 
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs` line 111 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHd0T_q6ie2j5_cPvcW:-OJTwfe7DyifXHL-CFMp:b2vhlvk) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxMessageHandler.cs#L111)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Yes, I'm referring to the already implemented approach. I think we should pass the confidence inside each word pair. On the translation side, the confidences are for each target token, which are strings, so we have to pass them separately.
</blockquote></details>

OK, I see - that makes sense. I'll go ahead and put in a Machine PR.
___
*[`src/Serval/src/Serval.WordAlignment/Models/WordAlignment.cs` line 14 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ4r4Tw9lTFGzej2mN-:-OJVMcWfDwDMU5DJE5xM:brujzsz) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Serval/src/Serval.WordAlignment/Models/WordAlignment.cs#L14)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my comment elsewhere about why the translation side is different.
</blockquote></details>

OK, thanks!
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs` line 5 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOko_j-xubImlA1HG5:-OJTvmDp0LGy5eYiQKyZ:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to update the `Key` to match the name change.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs` line 3 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5-qIH-JTLTl67UvPS:-OJTvipwAivF7QEk-W1-:broubdk) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/WordAlignmentEngineOptions.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Actually, I was wrong. It should be named `StatisticalEngineOptions` to be consistent with the naming of other classes related to the statistical word alignment engine.
</blockquote></details>

Yes, done
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs` line 84 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5Gc_p-rgkif7UU7_M:-OJTwZqu4Iig-AiWP496:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs#L84)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Once you add the null check, you shouldn't need the null-forgiving operators anymore.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs` line 21 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOmIIu63ITRjQHDJZ6:-OJTwa4Z3BrX_wRGslkH:b-llqefw) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Services/ServalTranslationPlatformOutboxMessageHandler.cs#L21)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Aren't there cases where `content` can be `null`, i.e. `ServalTranslationPlatformOutboxConstants.InsertPretranslations`? Also, you should throw for the cases where `contentStream` is required
</blockquote></details>

That's true. Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs` line 12 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5MdwXAMHDiwNCDdZY:-OJU4nR0BqxPkabN-TEZ:btcr28m) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services [...]

2025-02-20 18:27 UTC, johnml1135 commented
*[`docker-compose.yml` line 26 at r4](https://reviewable.io/reviews/sillsdev/serval/506#-OHclXyeAbkLEKRO7EOR:-OJZbNXb09uimL8R-bfO:b-ba7jcz) ([raw file](https://github.com/sillsdev/serval/blob/3a6c3cf447c7a9ce05a75980853fd85f6f2a61ae/docker-compose.yml#L26)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK. Yeah, we might need to refactor a bit to accommodate eflomal. Cross that bridge when we come to it?
</blockquote></details>

Sounds good to me.


<!-- Sent from Reviewable.io -->

2025-02-20 20:05 UTC, ddaspit reviewed
> Reviewed 16 of 16 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 10 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs` line 7 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJTvbaV8UmvzfAACqDl:-OJZrIPEEQXKYy0pNEvy:brld5vh) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/StatisticalWordAlignmentEngineOptions.cs#L7)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I assume you think it's fine to leave this as just "word_alignment_engines" though, @ddaspit?
</blockquote></details>

Yes, that's fine.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs` line 12 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5MdwXAMHDiwNCDdZY:-OJZsZUV3-i8TL8Oneg_:br4c96u) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs#L12)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Thanks! Does this look right, then? I don't love duplicating this helper function. I suppose I could add a method to `ThotWordAlignmentModelType` itself instead and have both call that? Not sure how big a deal it is.
</blockquote></details>

It would be nice to define it in Machine, but I won't be upset if you don't want to bother.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ThotWordAlignmentModelFactory.cs` line 49 at r20](https://reviewable.io/reviews/sillsdev/serval/506#-OJZxKNN592nuPhdN5hN:-OJZxKNN592nuPhdN5hO:b-fygo1c) ([raw file](https://github.com/sillsdev/serval/blob/ad0a22f60d580224c06aa72ae6b043e5a8b0e9e3/src/Machine/src/Serval.Machine.Shared/Services/ThotWordAlignmentModelFactory.cs#L49)):*
> ```Smalltalk
>     }
> 
>     public ITrainer CreateTrainer(
> ```

We don't need two implementations of `CreateTrainer`. You can remove `CreateTrainer` from the `IModelFactory` interface.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/StatisticalTrainBuildJob.cs` line 31 at r20](https://reviewable.io/reviews/sillsdev/serval/506#-OJZsGuV3V13nJrGYC96:-OJZsGuW-9RVYDHaHHzQ:bfxhu5k) ([raw file](https://github.com/sillsdev/serval/blob/ad0a22f60d580224c06aa72ae6b043e5a8b0e9e3/src/Machine/src/Serval.Machine.Shared/Services/StatisticalTrainBuildJob.cs#L31)):*
> ```Smalltalk
>         string? modelType = null;
>         if (buildOptions is not null)
>             modelType = (string?)JsonSerializer.Deserialize<JsonObject>(buildOptions)?["model_type"];
> ```

I believe that `model_type` is defined under `thot_align`. See Machine.py.


<!-- Sent from Reviewable.io -->

2025-02-21 18:07 UTC, johnml1135 commented
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJdg4YJ3c4x0j6lAxFe:bweclxy) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I don't have access to Visual Studio, no. John and I both use VSCode. There has to be an extension though, I bet. @johnml1135? If you could do it, that might be the most straightforward in the near term.
</blockquote></details>

Actually, since @ddaspit is the only one with Visual Studio, it probably would be best for him to make the update.


<!-- Sent from Reviewable.io -->

2025-02-21 18:07 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 203 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ52iNsCfvVhwZyJdKb:-OJdgPJ09Dr3Q16WaK3Q:bxuqxbp) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L203)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. @johnml1135, if you had a particular reason for doing this, I'll let you argue for it. Otherwise, I've reverted it.
</blockquote></details>

Probably in error.  I'm fine reverting it.


<!-- Sent from Reviewable.io -->

2025-02-21 18:08 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs` line 271 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ51U149WknQ7uGSf16:-OJdgV8E0e5SMuBYS839:b-pbdqz3) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Configuration/IMachineBuilderExtensions.cs#L271)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I'm assuming that that was just a copy-paste error since it's there for translation engines to support some data reorganization you did when refactoring build jobs a long time ago. Removed.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2025-02-21 18:13 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 89 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5FSB82YTPgCP2uXx4:-OJdhghb6Mg6Hw6whJYQ:bzd5xuw) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L89)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK, so I guess that's more John's call then: @johnml1135, would you rather I just get this PR through and then immediately follow up with the above or just do it a part of this PR?
</blockquote></details>

Let's just do it here.


<!-- Sent from Reviewable.io -->

2025-02-21 19:54 UTC, ddaspit reviewed
> Reviewed 4 of 4 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 7 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJdzP2nDkY4Z4APoBjz:b-7srhxh) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Actually, since @ddaspit is the only one with Visual Studio, it probably would be best for him to make the update.
</blockquote></details>

I fixed it.


<!-- Sent from Reviewable.io -->

2025-02-21 20:03 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 225 of 230 files reviewed, 6 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`Serval.sln` line 81 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ03O2L0BfM9AN-CWZ5:-OJe5jPQAkpRut6mprGz:b-ucfknh) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/Serval.sln#L81)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I fixed it.
</blockquote></details>

Thanks!
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 89 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5FSB82YTPgCP2uXx4:-OJe5sCQ3gQd2zgFph50:bbdqnxj) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L89)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Let's just do it here.
</blockquote></details>

Done...or at least, attempted :laughing: 
___
*[`src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs` line 12 at r17](https://reviewable.io/reviews/sillsdev/serval/506#-OJ5MdwXAMHDiwNCDdZY:-OJe5xG337L3N401u5Ka:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a7c0e7cbfe477e343bb43027e1663fa460b63c77/src/Machine/src/Serval.Machine.Shared/Services/WordAlignmentModelFactory.cs#L12)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be nice to define it in Machine, but I won't be upset if you don't want to bother.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-21 20:15 UTC, ddaspit reviewed
> Reviewed 5 of 5 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-24 20:45 UTC, Enkidu93 reviewed
Sorry, Damien, I once again missed some of your comments - not sure why, but they didn't show up as I worked through comments in Reviewable (maybe because I'm both a contributor and reviewer and John looked at them before I did?). I think this addresses all outstanding comments. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OJtgyUC3DfRC0vnk_OY:bj3da4c)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj` line 53 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOipSr9sGUVk9G5EWd:-OJtWKRA5uBV7Km-Hrh7:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Serval.Machine.Shared.csproj#L53)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You missed the project reference.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 109 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOvMiY9GS2A_vHEGGx:-OJtYGjO2ZqgaLxm4YAN:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L109)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is now the only place where we use the `ToEngineGroup` extension method. It might be simpler just to convert to the engine group here instead of defining a separate extension method.

Also, you should use `GetRequiredKeyedService` instead.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Configuration/ThotWordAlignmentModelOptions.cs` line 5 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJOkx-O226n8X39NiAr:-OJtWUoy3tw4xnQt0xlb:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Configuration/ThotWordAlignmentModelOptions.cs#L5)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to update the `Key` to match the name change.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-24 22:43 UTC, ddaspit reviewed
> Reviewed 25 of 25 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 4 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Shared/Models/AlignedWordPair.cs` line 7 at r24](https://reviewable.io/reviews/sillsdev/serval/506#-OJu6BG538gsMY-CDxCt:-OJu6BG538gsMY-CDxCu:bhc3ih2) ([raw file](https://github.com/sillsdev/serval/blob/a020acf5704355bea50149ee15c0d2ce6728028e/src/Serval/src/Serval.Shared/Models/AlignedWordPair.cs#L7)):*
> ```Smalltalk
>     public required int SourceIndex { get; set; }
>     public required int TargetIndex { get; set; }
>     public double? Score { get; set; }
> ```

This model is different between the two contexts (translation and alignment), so it should not be shared.

Also, the corresponding DTO needs to be updated to include the `Score` property.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 1 at r24](https://reviewable.io/reviews/sillsdev/serval/506#-OJu4qW8-Y3fRHHZh-dw:-OJu4qW8-Y3fRHHZh-dx:b-usyxim) ([raw file](https://github.com/sillsdev/serval/blob/a020acf5704355bea50149ee15c0d2ce6728028e/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L1)):*
> ```Smalltalk
> using System.ComponentModel;
> ```

Can this go in the global usings?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs` line 84 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJu6xy-A4uNmb2Ymfs5:-OJu6xy-A4uNmb2Ymfs6:biuoyec) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs#L84)):*
> ```Smalltalk
>                     TargetTokens = { targetTokens },
>                     Alignment = { wordPairs.Select(Map) },
>                     Confidences = { wordPairs.Select(wp => wp.AlignmentScore).ToList() }
> ```

`Score` needs to be set on the word pairs. We want to use `TranslationScore`.


<!-- Sent from Reviewable.io -->

2025-02-25 16:37 UTC, Enkidu93 reviewed
I'm going to go ahead and try to confirm that the E2E tests are passing locally.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OJxxtPb8aVFAkWSb0od:bttqbtj)* status: 217 of 232 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs` line 1 at r24](https://reviewable.io/reviews/sillsdev/serval/506#-OJu4qW8-Y3fRHHZh-dw:-OJxxfS6EzQwVtYscYX8:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a020acf5704355bea50149ee15c0d2ce6728028e/src/Machine/src/Serval.Machine.Shared/Services/ClearMLMonitorService.cs#L1)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Can this go in the global usings?
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs` line 84 at r19](https://reviewable.io/reviews/sillsdev/serval/506#-OJu6xy-A4uNmb2Ymfs5:-OJxxigR5L2XeyHw_y9M:b7oq016) ([raw file](https://github.com/sillsdev/serval/blob/0c07bd1b1c7d9df4efbf1681315c29ef1c84b709/src/Machine/src/Serval.Machine.Shared/Services/StatisticalEngineService.cs#L84)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`Score` needs to be set on the word pairs. We want to use `TranslationScore`.
</blockquote></details>

Done. I believe.
___
*[`src/Serval/src/Serval.Shared/Models/AlignedWordPair.cs` line 7 at r24](https://reviewable.io/reviews/sillsdev/serval/506#-OJu6BG538gsMY-CDxCt:-OJxxlZ6EsdySe8mMkUp:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/a020acf5704355bea50149ee15c0d2ce6728028e/src/Serval/src/Serval.Shared/Models/AlignedWordPair.cs#L7)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This model is different between the two contexts (translation and alignment), so it should not be shared.

Also, the corresponding DTO needs to be updated to include the `Score` property.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-25 17:21 UTC, ddaspit reviewed
> Reviewed 15 of 15 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Client/Client.g.cs` line 10555 at r25](https://reviewable.io/reviews/sillsdev/serval/506#-OJy67qI55X3frolOWOo:-OJy67qI55X3frolOWOp:bfo5rfg) ([raw file](https://github.com/sillsdev/serval/blob/ac0aae57d2e5bc151949e5626a2cbb106a926e54/src/Serval/src/Serval.Client/Client.g.cs#L10555)):*
> ```Smalltalk
> 
>     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
>     public partial class AlignedWordPair2
> ```

The name of this class is not good. We either need to have different names for the translation and alignment DTOs or just use the same DTO for both and make sure `Score` is optional. I tried to prefix DTOs with "Translation" in order to avoid this kind of name collision. Unfortunately, I did not do that with `AlignedWordPair`. I don't want to break the translation API in "Serval.Client", so we probably have to share the DTO for both contexts. Basically, you will need to revert the split of the aligned word pair model/DTO.


<!-- Sent from Reviewable.io -->

2025-02-25 17:50 UTC, Enkidu93 commented
> > Reviewed 15 of 15 files at r25, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)_ status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)
> 
> _[`src/Serval/src/Serval.Client/Client.g.cs` line 10555 at r25](https://reviewable.io/reviews/sillsdev/serval/506#-OJy67qI55X3frolOWOo:-OJy67qI55X3frolOWOp:bfo5rfg) ([raw file](https://github.com/sillsdev/serval/blob/ac0aae57d2e5bc151949e5626a2cbb106a926e54/src/Serval/src/Serval.Client/Client.g.cs#L10555)):_
> 
> > ```smalltalk
> >     [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
> >     public partial class AlignedWordPair2
> > ```
> 
> The name of this class is not good. We either need to have different names for the translation and alignment DTOs or just use the same DTO for both and make sure `Score` is optional. I tried to prefix DTOs with "Translation" in order to avoid this kind of name collision. Unfortunately, I did not do that with `AlignedWordPair`. I don't want to break the translation API in "Serval.Client", so we probably have to share the DTO for both contexts. Basically, you will need to revert the split of the aligned word pair model/DTO.

I see. What about something like `ScoredWordPair` or `ScoredAlignedWordPair` or is it better just to revert like you said?

2025-02-25 17:51 UTC, Enkidu93 commented
I've noticed some changes are needed to the `ServalWordAlignmentPlatformOutboxMessageHandler` (and accompanying tests), so I'm working on that.

2025-02-26 16:39 UTC, Enkidu93 commented
> I've noticed some changes are needed to the `ServalWordAlignmentPlatformOutboxMessageHandler` (and accompanying tests), so I'm working on that.

Done.

2025-02-27 15:45 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 229 of 233 files reviewed, 2 unresolved discussions (waiting on @ddaspit)

___
*[`src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxConstants.cs` line 13 at r26](https://reviewable.io/reviews/sillsdev/serval/506#-OK3IzBf9CEovAvHiG1B:-OK74JhuEV4Q51Zhn0Aw:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/cda698fd3a6858e5f9d0bd51ef6a86e7af71adcc/src/Machine/src/Serval.Machine.Shared/Services/ServalWordAlignmentPlatformOutboxConstants.cs#L13)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This can be shortened to `InsertWordAlignments`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-27 15:48 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 229 of 233 files reviewed, 2 unresolved discussions (waiting on @ddaspit)

___
*[`src/Serval/src/Serval.Client/Client.g.cs` line 10555 at r25](https://reviewable.io/reviews/sillsdev/serval/506#-OJy67qI55X3frolOWOo:-OK74N2O0WM1hMnbRi-8:b-xqjm5s) ([raw file](https://github.com/sillsdev/serval/blob/ac0aae57d2e5bc151949e5626a2cbb106a926e54/src/Serval/src/Serval.Client/Client.g.cs#L10555)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This is a bigger issue than just `AlignedWordPairDto`. This also impacts `ParallelCorpusFilterConfigDto`, `ParallelCorpusFilterDto`, `TrainingCorpusConfigDto`, and `TrainingCorpusDto`. The name collisions happen in the Swagger JSON file as well. This means that we need to make a breaking change to get this right. We have two options:

1. Prefix all DTO names with "Translation" or "WordAlignment". This was what I originally was trying to do, but clearly failed, since I allowed some DTO names without the prefix. We can do this automatically using the `ServalSchemaNameGenerator`. We could remove the prefix from DTOs that already have the prefix, i.e. `TranslationEngineDto` could be renamed to `EngineDto`. 
2. Add custom hooks in NSwag to generate DTOs in "Serval.Client" with different namespaces. For example, `Serval.Translation.AlignedWordPairDto` would be generated in the client as `Serval.Translation.AlignedWordPair` instead of `Serval.Client.AlignedWordPair`. The translation engines client interface would be generated as `Serval.Translation.ITranslationEnginesClient`. I don't think NSwag supports this out-of-the-box. We would need to create our own console application that calls NSwag. See this [issue](https://github.com/RicoSuter/NSwag/issues/2728) for more information.

We should probably meet to discuss what approach we want to take.
</blockquote></details>

OK. How 'breaking' of a change would that be? Like, Serval v2 kinda breaking? Could we just prefix the WordAlignment data classes with `WordAlignment` for now (since Serval = CAT = translation-first, i.e., translation is kinda the default for Serval), and then when we, in the near future, remove the deprecated corpora and make a v2, we could fix this as well?


<!-- Sent from Reviewable.io -->

2025-02-27 20:40 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506)* status: 218 of 237 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Client/Client.g.cs` line 10555 at r25](https://reviewable.io/reviews/sillsdev/serval/506#-OJy67qI55X3frolOWOo:-OK87t2p0DA5vZTdf3Kx:bizrk6c) ([raw file](https://github.com/sillsdev/serval/blob/ac0aae57d2e5bc151949e5626a2cbb106a926e54/src/Serval/src/Serval.Client/Client.g.cs#L10555)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

OK. How 'breaking' of a change would that be? Like, Serval v2 kinda breaking? Could we just prefix the WordAlignment data classes with `WordAlignment` for now (since Serval = CAT = translation-first, i.e., translation is kinda the default for Serval), and then when we, in the near future, remove the deprecated corpora and make a v2, we could fix this as well?
</blockquote></details>

Done. I created an issue to track this. For now, these dtos have been moved to Serval.Shared.


<!-- Sent from Reviewable.io -->

2025-02-27 21:16 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> Yay! 🎉

> Reviewed 4 of 4 files at r27, 15 of 15 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OK8DsAsBgolGS-zwu8R:berzve2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-02-27 21:40 UTC, johnml1135 commented
@Enkidu93 - can you rebase and make sure that Machine is at the latest version?  That should enable all the tests to pass again.

2025-02-27 21:41 UTC, Enkidu93 commented
> @Enkidu93 - can you rebase and make sure that Machine is at the latest version? That should enable all the tests to pass again.

Just pushed to update Machine. Yes, I'll go ahead and rebase.

2025-02-27 21:50 UTC, Enkidu93 commented
> <img alt=":lgtm_strong:" width="61" height="20" src="https://camo.githubusercontent.com/d6a46917134d5bd730f097a11c6d84fb9efc0c89be40f13b7f42d3ce9f79e198/68747470733a2f2f72657669657761626c652e696f2f6c67746d5f7374726f6e672e706e67"> Yay! 🎉
> 
> > Reviewed 4 of 4 files at r27, 15 of 15 files at r28, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/serval/506#-:-OK8DsAsBgolGS-zwu8R:berzve2)_ status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johnml1135)

Finally! :grin: 

@johnml1135, I think the 3.6.0 release was done before https://github.com/sillsdev/machine/pull/287 made it in

2025-02-27 23:10 UTC, johnml1135 commented
@Enkidu93 the tests are still failing and there are some conflicts that need to be resolved.

2025-02-28 15:30 UTC, merged