Cleanup builds & engines
sillsdev/serval pull request #510
Opened 2024-10-15 13:40 UTC by Enkidu93

Fixes #374

2024-10-15 16:01 UTC, ddaspit requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: all files reviewed, 9 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FoL0H69RJEMoOLI4q:-O9FoL0H69RJEMoOLI4r:b-ipb4uw) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Models/Build.cs#L18)):*
> ```Smalltalk
>     public DateTime? DateFinished { get; init; }
>     public IReadOnlyDictionary<string, object>? Options { get; init; }
>     public bool SuccessfullyStarted { get; init; }
> ```

I would name this `IsCreated` or `IsInitialized`. Since this is a new property, it should be optional.
___
*[`src/Serval/src/Serval.Translation/Models/Engine.cs` line 19 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FoQ8p4ECb2etg7smk:-O9FoQ8p4ECb2etg7sml:b-ipb4uw) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Models/Engine.cs#L19)):*
> ```Smalltalk
>     public double Confidence { get; init; }
>     public int CorpusSize { get; init; }
>     public bool SuccessfullyCreated { get; init; }
> ```

I would name this `IsCreated` or `IsInitialized`. Since this is a new property, it should be optional.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FstmtCB04GJ83QtVD:-O9FstmtCB04GJ83QtVE:b5pk62k) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L6)):*
> ```Smalltalk
> namespace Serval.Translation.Services;
> 
> public class BuildCleanupService(
> ```

I wonder if we could find a way to make this class generic. I feel like this will be a normal pattern in Serval. We could create a new interface for these types of models. It would extend `IEntity` and contain the flag property. If this isn't clear, we can meet to discuss further.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 25 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqK79A_-2xt6XqVpm:-O9FqK79A_-2xt6XqVpn:b-tcvl4r) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L25)):*
> ```Smalltalk
>     public async Task CheckBuildsAsync(IRepository<Build> builds, CancellationToken cancellationToken)
>     {
>         IReadOnlyList<Build> allBuilds = await builds.GetAllAsync(cancellationToken);
> ```

You should filter the builds in the query.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqAjG4CXFkf0s-ino:-O9FqAjG4CXFkf0s-inp:bv90di6) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L27)):*
> ```Smalltalk
>         IReadOnlyList<Build> allBuilds = await builds.GetAllAsync(cancellationToken);
>         IEnumerable<Build> notStartedBuilds = allBuilds.Where(b => !b.SuccessfullyStarted);
>         await Task.Delay(_timeout, cancellationToken); //Make sure the builds are not midway through starting
> ```

Using a `DateCreated` property would be more deterministic and reliable. It would be a useful property to have anyway.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqQij1ydLSVPOSlT8:-O9FqQij1ydLSVPOSlT9:bdi9qya) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L30)):*
> ```Smalltalk
>         foreach (
>             Build build in await builds.GetAllAsync(
>                 b => notStartedBuilds.Select(c => c.Id).Contains(b.Id),
> ```

I would perform the `Select` in the original query.
___
*[`src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9Fqi5z79BTTMHajeXn:-O9Fqi5z79BTTMHajeXo:b-6t1d0y) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs#L30)):*
> ```Smalltalk
>     )
>     {
>         IReadOnlyList<Engine> allEngines = await engines.GetAllAsync(cancellationToken);
> ```

See my comments for `BuildCleanupService`.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FrPrZ2TfgcYX4qCqJ:-O9FrPr_0c_xzaQ0bJhS:bsi5rgw) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L149)):*
> ```Smalltalk
>                 IsModelPersisted = createResponse.IsModelPersisted
>             };
>             await Entities.UpdateAsync(
> ```

We should update `IsModelPersisted` in the same call. We shouldn't pass a cancellation token to this call.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 300 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FroPg1jbq8upU43Pz:-O9FroPg1jbq8upU43Q-:b-1tbjxk) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L300)):*
> ```Smalltalk
>             }
>             await client.StartBuildAsync(request, cancellationToken: cancellationToken);
>             await _builds.UpdateAsync(
> ```

We shouldn't pass a cancellation token to this call.


<!-- Sent from Reviewable.io -->

2024-10-15 17:34 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: all files reviewed, 9 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FstmtCB04GJ83QtVD:-O9GDu1-En67o-OrFWHv:b-ulto4r) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I wonder if we could find a way to make this class generic. I feel like this will be a normal pattern in Serval. We could create a new interface for these types of models. It would extend `IEntity` and contain the flag property. If this isn't clear, we can meet to discuss further.
</blockquote></details>

No, I understand and I considered doing something like that. Really, the only substantial difference between these classes besides the model they're operating on is how they're deleted (i.e., via the engine service in the `EngineCleanupService`) but that just be an overridden method. I'll go ahead and do something like that and ping you for review once I'm done. 


<!-- Sent from Reviewable.io -->

2024-10-16 18:12 UTC, Enkidu93 reviewed
I know I should be focusing my attention on the other PR, but I had this commit just about ready to push, so I figured I should just get it out there. I'm not so sure about the naming, so let me know if you think there would be better names for the new class and interface etc.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-O9LWLJC0SAnhNBLVhDP:bdwkgzo)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 18 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FoL0H69RJEMoOLI4q:-O9LVp65565rx4saHv5_:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Models/Build.cs#L18)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would name this `IsCreated` or `IsInitialized`. Since this is a new property, it should be optional.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Models/Engine.cs` line 19 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FoQ8p4ECb2etg7smk:-O9LVq1I6491OMIl9eJg:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Models/Engine.cs#L19)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would name this `IsCreated` or `IsInitialized`. Since this is a new property, it should be optional.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 6 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FstmtCB04GJ83QtVD:-O9LVt-p3a3g_r0EB_qS:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L6)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

No, I understand and I considered doing something like that. Really, the only substantial difference between these classes besides the model they're operating on is how they're deleted (i.e., via the engine service in the `EngineCleanupService`) but that just be an overridden method. I'll go ahead and do something like that and ping you for review once I'm done.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 25 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqK79A_-2xt6XqVpm:-O9LVuxgDDh_VSI-84iP:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L25)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should filter the builds in the query.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqAjG4CXFkf0s-ino:-O9LVvZXCy1OJBozkZ7c:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Using a `DateCreated` property would be more deterministic and reliable. It would be a useful property to have anyway.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FqQij1ydLSVPOSlT8:-O9LVwGf1C9SSt1jQ0jt:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/BuildCleanupService.cs#L30)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would perform the `Select` in the original query.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs` line 30 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9Fqi5z79BTTMHajeXn:-O9LW7Yg97Ci_YcWwF-X:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs#L30)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

See my comments for `BuildCleanupService`.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FrPrZ2TfgcYX4qCqJ:-O9LW9Rj3M1ITIOYTIAw:bftz4j6) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L149)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We should update `IsModelPersisted` in the same call. We shouldn't pass a cancellation token to this call.
</blockquote></details>

Like this? I'm not sure I totally understand the point of the `updateIsModelPersisted` flag. And does it need to be updated outside of the try like it was previously?
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 300 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FroPg1jbq8upU43Pz:-O9LWIiSBTHHPkZXWXwZ:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L300)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We shouldn't pass a cancellation token to this call.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-17 15:17 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FrPrZ2TfgcYX4qCqJ:-O9Q0DDg2eirvoBnNnb0:b5ry4ag) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L149)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Like this? I'm not sure I totally understand the point of the `updateIsModelPersisted` flag. And does it need to be updated outside of the try like it was previously?
</blockquote></details>

If IsModelPersisted was specified from the API, it is set properly in the Entities it doesn't need to be updated, otherwise, it does from the Machine level defaults.  There is no issue with the change.


<!-- Sent from Reviewable.io -->

2024-10-17 15:36 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 47 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q6nWqAmQIw8tg8Nno:-O9Q6nWqAmQIw8tg8Nnp:b77e88h) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L47)):*
> ```Smalltalk
>     )
>     {
>         await entities.DeleteAsync(e => e.Id == entity.Id, cancellationToken);
> ```

How does this actually do anything?  How is it cleaning up the builds (this is not overridden)?


<!-- Sent from Reviewable.io -->

2024-10-17 15:41 UTC, ddaspit reviewed
In the `EngineService` and `BuildService`, we should treat engines and builds that haven't been initialized as if they don't exist.

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-O9Q7_Sf4HrDrBCB-Rxm:b-pb64pw)* status: all files reviewed, 4 unresolved discussions (waiting on @Enkidu93 and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q76iI1fAw1FwKqU1Y:-O9Q76iI1fAw1FwKqU1Z:bfe6fgw) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs#L27)):*
> ```Smalltalk
>         if (EngineService == null)
>             return;
>         await EngineService.DeleteAsync(engine.Id, cancellationToken);
> ```

I don't think we need to use the service to delete the engine. We can just use the repository. If an engine wasn't initialized properly, then you won't be able to create builds and pretranslations.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 156 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q5Aa97IAFgVaEO4vC:-O9Q5Aa97IAFgVaEO4vD:b-f8jlmp) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/EngineService.cs#L156)):*
> ```Smalltalk
>                     u.Set(e => e.IsModelPersisted, engine.IsModelPersisted);
>                 },
>                 cancellationToken: cancellationToken
> ```

You shouldn't pass a cancellation token to this call.
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q63cT5asi-8SqhR3S:-O9Q63cT5asi-8SqhR3T:b2j4qk8) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L27)):*
> ```Smalltalk
>     {
>         var now = DateTime.UtcNow;
>         IEnumerable<T> uninitializedEntities = (await entities.GetAllAsync(cancellationToken)).Where(b =>
> ```

The `Where` class should be included in the database query, i.e. `entities.GetAllAsync(e => e.IsInitalized != null && !e.IsInitialized && e.DateCreated != null && e.DateCreated > expired)`.


<!-- Sent from Reviewable.io -->

2024-10-17 16:51 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 47 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q6nWqAmQIw8tg8Nno:-O9QO-l_CqISsYgFCf1K:b-j5pfkc) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L47)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How does this actually do anything?  How is it cleaning up the builds (this is not overridden)?
</blockquote></details>

I misunderstood - now I see what is going on.


<!-- Sent from Reviewable.io -->

2024-10-17 16:55 UTC, johnml1135 requested changes
> Reviewed 1 of 9 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-18 13:24 UTC, Enkidu93 reviewed
Done. Let me know if you think there's a cleaner way to do this. It'd be nice if I could make them inherit from some kind of `InitializableEntityServiceBase` maybe but  - alas - no multiple inheritance. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-O9UmH8k8JV8wkkQllsJ:bgiwxdf)* status: 7 of 13 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q76iI1fAw1FwKqU1Y:-O9Un-8C6emr-mDainW0:b35wj2g) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/EngineCleanupService.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I don't think we need to use the service to delete the engine. We can just use the repository. If an engine wasn't initialized properly, then you won't be able to create builds and pretranslations.
</blockquote></details>

Done. Good point.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 149 at r1](https://reviewable.io/reviews/sillsdev/serval/510#-O9FrPrZ2TfgcYX4qCqJ:-O9Un1k47NqcGo_bherA:bm5nuu0) ([raw file](https://github.com/sillsdev/serval/blob/39de60ff5a3725f48c48198b2391dcde0834d9c3/src/Serval/src/Serval.Translation/Services/EngineService.cs#L149)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If IsModelPersisted was specified from the API, it is set properly in the Entities it doesn't need to be updated, otherwise, it does from the Machine level defaults.  There is no issue with the change.
</blockquote></details>

OK, great
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 156 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q5Aa97IAFgVaEO4vC:-O9Un3K37iAxnk2EWaDk:b-a4wcvv) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/EngineService.cs#L156)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You shouldn't pass a cancellation token to this call.
</blockquote></details>

Oops. Done!
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 27 at r2](https://reviewable.io/reviews/sillsdev/serval/510#-O9Q63cT5asi-8SqhR3S:-O9Un5RaCENGPeNVQRRN:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/6ddce7944ecceff0e9ee23e90892d0369019e769/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The `Where` class should be included in the database query, i.e. `entities.GetAllAsync(e => e.IsInitalized != null && !e.IsInitialized && e.DateCreated != null && e.DateCreated > expired)`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 19:03 UTC, ddaspit reviewed
I think this is fine. You could add `InitializableEntityServiceBase` and `OwnedInitializableEntityServiceBase`, and duplicate the code between the two. I don't love it, but it would work. The other option is to make everything an initializable entity. For entities that don't need the two-stage initialization, you could just set `IsInitialized` to `true` when the entity is created.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-O9VzTd_AT7MF0_HE-hE:b5yr7j9)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93)

___
*[`src/Serval/src/Serval.Translation/Services/BuildService.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VufcR85aCvm1BqWSw:-O9VufcR85aCvm1BqWSx:b5avh3x) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/BuildService.cs#L3)):*
> ```Smalltalk
> namespace Serval.Translation.Services;
> 
> public class BuildService(IRepository<Build> builds) : EntityServiceBase<Build>(builds), IBuildService
> ```

Do you need to override `GetAsync`?
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VxBXQ3QWZH1ypaGTl:-O9VxBXQ3QWZH1ypaGTm:b-yid6vh) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/EngineService.cs#L6)):*
> ```Smalltalk
> namespace Serval.Translation.Services;
> 
> public class EngineService(
> ```

Don't you need to override `GetAllAsync`?
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 365 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VxKkLEnyBLcwfHbBE:-O9VxKkLEnyBLcwfHbBF:b-g3a0j6) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/EngineService.cs#L365)):*
> ```Smalltalk
>     }
> 
>     public Task AddCorpusAsync(string engineId, Models.Corpus corpus, CancellationToken cancellationToken = default)
> ```

All of the corpus methods need to check the flag.
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 0 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VwcUZCK5wJO4C983D:-O9VwcUZCK5wJO4C983E:b5jy3xj) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L0)):*
This class should go in Serval.Shared.
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 27 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9W-nMf-WHS9sz-v_KI:-O9W-nMf-WHS9sz-v_KJ:b-81q8m9) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L27)):*
> ```Smalltalk
>     {
>         var now = DateTime.UtcNow;
>         IEnumerable<T> uninitializedEntities = await entities.GetAllAsync(
> ```

Would an index be appropriate for this query?


<!-- Sent from Reviewable.io -->

2024-10-28 19:17 UTC, johnml1135 reviewed
> Reviewed 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: all files reviewed, 5 unresolved discussions (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-11-01 19:57 UTC, johnml1135 commented
Doesn't this also resolve #468?

2024-12-02 16:18 UTC, Enkidu93 reviewed
I don't think so? How do you envision this solving that issue?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-OD78-4g69UyXqXNDYvK:b-4m7io7)* status: 7 of 14 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/BuildService.cs` line 3 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VufcR85aCvm1BqWSw:-OD78RfD0S5tQVyq6xJP:b-4alr9x) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/BuildService.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Do you need to override `GetAsync`?
</blockquote></details>

Done. This is called in the controller, yes.
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 6 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VxBXQ3QWZH1ypaGTl:-OD78ZZw3ZyyaLQQh7Bf:biqkqer) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/EngineService.cs#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Don't you need to override `GetAllAsync`?
</blockquote></details>

Done. For completeness. I'm not sure where this is called though. Or were you envisioning a `GetAllAsync(string *owner*...)` method?
___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 365 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VxKkLEnyBLcwfHbBE:-OD78dIn2snSnFFk1YBd:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/EngineService.cs#L365)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

All of the corpus methods need to check the flag.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 27 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9W-nMf-WHS9sz-v_KI:-OD78CalBefm_25U8rS6:b-pdp5hr) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L27)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Would an index be appropriate for this query?
</blockquote></details>

Done. Let me know if this looks right to you. I'm not sure what kind of optimizations are done automatically.
___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line  at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9VwcUZCK5wJO4C983D:-OD6yea5AYMe3msod8oG:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This class should go in Serval.Shared.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 16:18 UTC, Enkidu93 reviewed
Sorry - just jumping back into this and trying to catch my brain up with where I was, so sorry if I'm asking stupid questions. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-OD79ZrU7Y3zAN4Vg0q8:b-lvg30q)* status: 7 of 14 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-12-03 01:56 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1335 at r4](https://reviewable.io/reviews/sillsdev/serval/510#-OD9DsTR6zMOwkh9BpDw:-OD9DsTR6zMOwkh9BpDx:b-c5q9mz) ([raw file](https://github.com/sillsdev/serval/blob/413000b670f188d7fa121c5569383c0d502649b1/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1335)):*
> ```Smalltalk
>             TrainOn = Map(engine, source.TrainOn),
>             Options = Map(source.Options),
>             IsInitialized = false,
> ```

Please rebase rather than merging in from main.


<!-- Sent from Reviewable.io -->

2024-12-03 01:56 UTC, johnml1135 reviewed
> Reviewed 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: 8 of 14 files reviewed, 6 unresolved discussions (waiting on @ddaspit, @Enkidu93, and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-12-03 01:57 UTC, johnml1135 commented
Please rebase rather than merging from main - it confuses the diff's.





<!-- Sent from Reviewable.io -->

2024-12-03 18:14 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510#-:-ODCid-l0RDZ82-jBGDU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Enkidu93)

___
*[`src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs` line 27 at r3](https://reviewable.io/reviews/sillsdev/serval/510#-O9W-nMf-WHS9sz-v_KI:-ODCi0yz12-9YYtd_zCG:b-69nzva) ([raw file](https://github.com/sillsdev/serval/blob/65c72c4e5109d886aa2fed9907d7cedbc72451e2/src/Serval/src/Serval.Translation/Services/UnitializedEntityCleanupService.cs#L27)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Done. Let me know if this looks right to you. I'm not sure what kind of optimizations are done automatically.
</blockquote></details>

We can always track how much the index is used and remove it if it isn't used.


<!-- Sent from Reviewable.io -->

2024-12-04 12:44 UTC, johnml1135 approved these changes
> Reviewed 1 of 6 files at r3, 6 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/510)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-12-04 12:52 UTC, merged