Move preprocess logic to toolkit
sillsdev/serval pull request #512
Opened 2024-10-16 14:54 UTC by Enkidu93

Fixes #396 

How should we go about testing the new Echo engine functionality? Just add integration tests?

2024-10-16 16:40 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Shared/Serval.Shared.csproj` line 22 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LBkzX5w4XoR1QYxGD:-O9LBkzX5w4XoR1QYxGE:bkx74dk) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/Serval/src/Serval.Shared/Serval.Shared.csproj#L22)):*
> ```XML
> 		<PackageReference Include="Grpc.HealthCheck" Version="2.65.0" />
> 		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.65.0" />
> 		<PackageReference Include="SIL.Machine" Version="3.2.8" Condition="!Exists('..\..\..\..\..\machine\src\SIL.Machine\SIL.Machine.csproj')" />
> ```

Pull the most recent from main - we are up to Machine 3.4.0 - and there are 4 locations that all need to be updated together.


<!-- Sent from Reviewable.io -->

2024-10-16 16:53 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 157 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LDXPbCOJY_z272GSf:-O9LDXPbCOJY_z272GSg:b-uwe0le) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L157)):*
> ```Smalltalk
>             }
> 
>             foreach (Row row in AlignPretranslateCorpus(sourcePretranslateCorpora, targetCorpora[0].TextCorpus))
> ```

Pretranslations are not universal.  Could this be broken up into a few major pieces - and then one Machine specific function inherit from this class to tie the main pieces together?  The main processing of "monocorpus" and "parallelCorpus" are universal - and we should be able to have a few routines to slice and dice these things so that the 10 line linq expression only happens once...


<!-- Sent from Reviewable.io -->

2024-10-16 17:00 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 179 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LGNqHAsgBrNOeWV4J:-O9LGNqHAsgBrNOeWV4K:b-nu98f2) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L179)):*
> ```Smalltalk
>     )
>     {
>         srcCorpora = srcCorpora.Select(sc => sc.Transform(CleanSegment)).ToArray();
> ```

So does this follow the logic - Mix the sources, chose the first target?  I can't see it clearly - should it be documented here?


<!-- Sent from Reviewable.io -->

2024-10-16 17:02 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 295 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LFLlqD9dkQHeE9N5J:-O9LFLlqD9dkQHeE9N5K:b-tgd66q) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L295)):*
> ```Smalltalk
>     }
> 
>     private static IEnumerable<Row> AlignPretranslateCorpus(ITextCorpus[] srcCorpora, ITextCorpus trgCorpus)
> ```

Align Train and Align Pretranslate.  If these will be in the ServiceToolkit, could we change the name to something more generic?  AlignTrainCorpus may be good enough, but I would prefer something like "AlignResultsGenerationCorpus"  or even more generically, "AlignMixSource" and "AlignChooseFirstSource".  Would that work?


<!-- Sent from Reviewable.io -->

2024-10-16 17:45 UTC, johnml1135 commented
Add a new set of unit tests in service toolkit?





<!-- Sent from Reviewable.io -->

2024-10-16 17:45 UTC, johnml1135 requested changes
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-17 00:19 UTC, Enkidu93 reviewed
I've added a unit test in the toolkit. I think ideally we'll port almost all the current PreprocessBuildTests to the toolkit. I'm wondering though if we should try to get this in first and then follow up with that in a separate PR since this PR will be difficult to merge once other changes have been put through.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512#-:-O9Mojk69AfEBYNcmnGs:b-odho76)* status: 17 of 29 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Echo/src/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 98 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9Mp3a340xX3YIuDICj:-O9Mp3a340xX3YIuDICk:brdddk6) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/Echo/src/EchoTranslationEngine/TranslationEngineServiceV1.cs#L98)):*
> ```Smalltalk
>                                     },
>                                     cancellationToken
>                                 );
> ```

@ddaspit, it might just be because it's late, but it's not clear to me how to go about doing this: I seem to be doing something wrong with how I'm passing in this async delegate and it's causing the Echo engine to hang and not respond. Any thoughts? I've not exhausted my debugging (although the debugger keeps crashing on me), but I thought maybe you'd just see it right off.
___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 94 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9MpS7Y2dWvmTlhZssV:-O9MpS7ZBz6blLDhmUXJ:b-7cmi9r) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L94)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task RunAsync_PretranslateTextIdsOverlapWithTrainOnTextIds()
> ```

I also fixed a bug regarding this situation and added a test.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 157 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LDXPbCOJY_z272GSf:-O9MpZJzCCsh93kCRXc2:b-5ny3tm) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L157)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Pretranslations are not universal.  Could this be broken up into a few major pieces - and then one Machine specific function inherit from this class to tie the main pieces together?  The main processing of "monocorpus" and "parallelCorpus" are universal - and we should be able to have a few routines to slice and dice these things so that the 10 line linq expression only happens once...
</blockquote></details>

Discussed in meeting
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 179 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LGNqHAsgBrNOeWV4J:-O9Mp_ik2IDaYZOD9tYc:bj7e7zp) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L179)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

So does this follow the logic - Mix the sources, chose the first target?  I can't see it clearly - should it be documented here?
</blockquote></details>

That happens elsewhere, but yep, that's the logic. I can add more comments if something seems unclear.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 295 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LFLlqD9dkQHeE9N5J:-O9Mpk9F5Oh4Lgk9CAqc:b-xk56ig) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L295)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Align Train and Align Pretranslate.  If these will be in the ServiceToolkit, could we change the name to something more generic?  AlignTrainCorpus may be good enough, but I would prefer something like "AlignResultsGenerationCorpus"  or even more generically, "AlignMixSource" and "AlignChooseFirstSource".  Would that work?
</blockquote></details>

Discussed in meeting.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 313 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9MpmU48j1xMf1vDTPz:-O9MpmU48j1xMf1vDTQ-:b-qsgy2f) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L313)):*
> ```Smalltalk
>                 .SelectMany(sc => trgCorpora.Select(tc => sc.AlignRows(tc, allSourceRows: true)))
>                 .ZipMany(rows =>
>                     rows.Where(r => r.SourceSegment.Count > 0 && r.TargetSegment.Count == 0).FirstOrDefault()
> ```

This addresses https://github.com/sillsdev/serval/issues/514
___
*[`src/Serval/src/Serval.Shared/Serval.Shared.csproj` line 22 at r1](https://reviewable.io/reviews/sillsdev/serval/512#-O9LBkzX5w4XoR1QYxGD:-O9Mpv_FDPfqz_sAkFJS:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/5a612918cf806817d92f3b1e3e65404867490dcf/src/Serval/src/Serval.Shared/Serval.Shared.csproj#L22)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Pull the most recent from main - we are up to Machine 3.4.0 - and there are 4 locations that all need to be updated together.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-17 01:59 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: 17 of 29 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Echo/src/EchoTranslationEngine/TranslationEngineServiceV1.cs` line 98 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9Mp3a340xX3YIuDICj:-O9NBe0jDpEUkWb-gpbx:b-ip8q55) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/Echo/src/EchoTranslationEngine/TranslationEngineServiceV1.cs#L98)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

@ddaspit, it might just be because it's late, but it's not clear to me how to go about doing this: I seem to be doing something wrong with how I'm passing in this async delegate and it's causing the Echo engine to hang and not respond. Any thoughts? I've not exhausted my debugging (although the debugger keeps crashing on me), but I thought maybe you'd just see it right off.
</blockquote></details>

Nevermind. It didn't have to do with that at all. I just had an outdated version of Machine locally and was hitting the bug John had fixed in the `ZipMany` function where it hits and infinite loop.


<!-- Sent from Reviewable.io -->

2024-10-17 11:55 UTC, johnml1135 commented
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 209 at r4](https://reviewable.io/reviews/sillsdev/serval/512#-O9PKFmy78XSStNtaox6:-O9PKFmy78XSStNtaox7:b4ywbch) ([raw file](https://github.com/sillsdev/serval/blob/5033bd33d8f0b8a70c04b105f450a75e60809a56/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L209)):*
> ```Smalltalk
>             Assert.That(termCount, Is.EqualTo(0));
>         });
>         Assert.That(
> ```

Were these tests wrong originally?  Why did the values change?


<!-- Sent from Reviewable.io -->

2024-10-17 12:01 UTC, johnml1135 commented
*[`src/ServiceToolkit/test/SIL.ServiceToolkit/Utils/data/source2.txt` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/512#-O9PLXTK7K2TB7FbOeKk:-O9PLXTK7K2TB7FbOeKl:buqy6q7) ([raw file](https://github.com/sillsdev/serval/blob/5033bd33d8f0b8a70c04b105f450a75e60809a56/src/ServiceToolkit/test/SIL.ServiceToolkit/Utils/data/source2.txt#L1)):*
> ```help
> Source two, Line 1
> ```

These should be removed from Machine/test, they are no longer needed.


<!-- Sent from Reviewable.io -->

2024-10-17 12:04 UTC, johnml1135 commented
Agreed.  Let's just do this small thing and get it released to solve the immediate issue.





<!-- Sent from Reviewable.io -->

2024-10-17 12:04 UTC, johnml1135 commented
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 94 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9MpS7Y2dWvmTlhZssV:-O9PMPlu81RnzuXJi_44:btojbfd) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L94)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

I also fixed a bug regarding this situation and added a test.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2024-10-17 12:05 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 313 at r3](https://reviewable.io/reviews/sillsdev/serval/512#-O9MpmU48j1xMf1vDTPz:-O9PMV2V2f3oeM1Oz4Zb:b9j9n43) ([raw file](https://github.com/sillsdev/serval/blob/60d40844d8e8ab4bf9a2f64f4670ea4ba2dbb5a4/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L313)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This addresses https://github.com/sillsdev/serval/issues/514
</blockquote></details>

Looks good to me.


<!-- Sent from Reviewable.io -->

2024-10-17 14:19 UTC, Enkidu93 reviewed
To my knowledge, everything is working properly now on this branch. The echo engine is only covered by an E2E test, so we should consider either giving up on testing the Echo engine too extensively OR adding an echo-specific suite of tests. I'm not too bothered by this since the logic is now shared via the toolkit (i.e., the tricky part is tested elsewhere). Also, like I mentioned above, the preprocess build job tests should be ported eventually.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512#-:-O9Pp-YO8sBh-XQZOrXP:bhsip2u)* status: 16 of 31 files reviewed, 10 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 209 at r4](https://reviewable.io/reviews/sillsdev/serval/512#-O9PKFmy78XSStNtaox6:-O9PpWvg4yy8cvBiy59P:bqcon7x) ([raw file](https://github.com/sillsdev/serval/blob/5033bd33d8f0b8a70c04b105f450a75e60809a56/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L209)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Were these tests wrong originally?  Why did the values change?
</blockquote></details>

Most of these are reversions to the values they had pre-mixed-source-support. I was confused about the intended functionality regarding pretranslation, so I changed the values. But with the changes in this PR, they can be changed back. Let me hand reckon the numbers one more time to make sure.
___
*[`src/Serval/test/Serval.E2ETests/ServalClientHelper.cs` line 194 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9Ppweq5U-8X1f16aPt:-O9Ppweq5U-8X1f16aPu:b1h3gtx) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/Serval/test/Serval.E2ETests/ServalClientHelper.cs#L194)):*
> ```Smalltalk
>                 FileFormat.Text,
>                 targetLanguage,
>                 isTarget: true
> ```

@johnml1135, do you mind if I just do it like this? I found the echo-specific logic in the helper to be confusing.
___
*[`src/ServiceToolkit/test/SIL.ServiceToolkit/Utils/data/source2.txt` line 1 at r4](https://reviewable.io/reviews/sillsdev/serval/512#-O9PLXTK7K2TB7FbOeKk:-O9Pq4i0EnwT4_RDhTny:b-zaujig) ([raw file](https://github.com/sillsdev/serval/blob/5033bd33d8f0b8a70c04b105f450a75e60809a56/src/ServiceToolkit/test/SIL.ServiceToolkit/Utils/data/source2.txt#L1)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

These should be removed from Machine/test, they are no longer needed.
</blockquote></details>

Once the other tests are ported, they won't be needed, right. But for now, they're duplicated.


<!-- Sent from Reviewable.io -->

2024-10-17 14:51 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 687 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9PxU7K7qsucbEcsCVP:-O9PxU7K7qsucbEcsCVQ:b-e1g1x8) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L687)):*
> ```Smalltalk
>         if (sourceCorpus.Files.Count > 0)
>             corpus.SourceCorpora.Add(sourceCorpus);
>         if (targetCorpus.Files.Count > 0)
> ```

What is the significance of the logic change?


<!-- Sent from Reviewable.io -->

2024-10-17 14:52 UTC, johnml1135 commented
*[`src/Serval/test/Serval.E2ETests/ServalClientHelper.cs` line 194 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9Ppweq5U-8X1f16aPt:-O9PxjAdEoDwd5AsBPYo:bbaxu10) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/Serval/test/Serval.E2ETests/ServalClientHelper.cs#L194)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

@johnml1135, do you mind if I just do it like this? I found the echo-specific logic in the helper to be confusing.
</blockquote></details>

That's fine - it looks clearer.


<!-- Sent from Reviewable.io -->

2024-10-17 14:57 UTC, johnml1135 commented
I agree - all complicated things in echo are either tested elsewhere (like in the service toolkit) or are themselves needed for testing, at which time we would be testing test code.  The E2E echo tests are more about testing the Serval API independently of the Machine engines.





<!-- Sent from Reviewable.io -->

2024-10-17 14:57 UTC, johnml1135 reviewed
> Reviewed 2 of 3 files at r2, 8 of 10 files at r3, 2 of 2 files at r4, 2 of 3 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-10-17 15:44 UTC, Enkidu93 reviewed
OK

Still working on a pretranslation bug. I'll ping when it should finally be reviewed. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512#-:-O9Q8Yen2_UfwJFqVF4L:b-y24n7h)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-10-18 20:57 UTC, ddaspit requested changes
> Reviewed 16 of 22 files at r1, 2 of 3 files at r2, 7 of 10 files at r3, 1 of 2 files at r4, 2 of 3 files at r5, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 3 unresolved discussions (waiting on @Enkidu93)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 3 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9QA1B-0vIQ_v4MBoNC:-O9QA1B-0vIQ_v4MBoND:b50w3ap) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L3)):*
> ```Smalltalk
> namespace SIL.ServiceToolkit.Utils;
> 
> public class ParallelCorpusPreprocessor
> ```

This should be implemented as a service that we inject using DI. You should create an extension method that adds the required services to the DI in an `IServiceCollectionExtensions` class.
___
*[`src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj` line 0 at r7](https://reviewable.io/reviews/sillsdev/serval/512#-O9WPSJB2ygUC1vS0r5z:-O9WPSJB2ygUC1vS0r6-:bn2yh76) ([raw file](https://github.com/sillsdev/serval/blob/6ceee183f3d000abee4ae7f01fe64665b920dc0f/src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj#L0)):*
The directory name should match the assembly name.


<!-- Sent from Reviewable.io -->

2024-10-22 16:25 UTC, ddaspit requested changes
> Reviewed 21 of 21 files at r8, 1 of 1 files at r9, 9 of 9 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 6 unresolved discussions (waiting on @Enkidu93)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 43 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p-kz3BU4fvI97WzNE:-O9p-kz3BU4fvI97WzNF:b-jeghdx) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L43)):*
> ```Smalltalk
>                 .Select(sc =>
>                 {
>                     ITextCorpus textCorpus = sc.TextCorpus;
> ```

The filtering logic for source and target are the same. This should be pulled out into a separate function. 
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 46 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p0BdL5QjiHaX54xgr:-O9p0BdL5QjiHaX54xgs:b-w2oo31) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L46)):*
> ```Smalltalk
>                     if (sc.Corpus.TrainOnTextIds is not null)
>                         return textCorpus.FilterTexts(sc.Corpus.TrainOnTextIds);
>                     return textCorpus.Where(row =>
> ```

There is no need to perform this `Where` operation if `TrainOnChapters` is `null`. Also, we should call `FilterTexts` on the books specified in `TrainOnChapters`, so we don't unnecessarily parse books.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 56 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p00W-AXHHU3N3mRqZ:-O9p00W-AXHHU3N3mRq_:bzg4m) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L56)):*
> ```Smalltalk
>                 .Select(sc =>
>                 {
>                     ITextCorpus textCorpus = sc.TextCorpus;
> ```

I would go ahead and pull this out to a separate function as well to improve readability.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 63 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p0kbg3wiFqn9U0BQj:-O9p0kbg3wiFqn9U0BQk:b-wmnnz8) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L63)):*
> ```Smalltalk
>                         );
>                     }
>                     return textCorpus.Where(row =>
> ```

We exclude verses from the training corpus when `PretranslateTextIds` or `PretranslateChapters` is specified. We should also exclude verses from the training corpus when neither is specified.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 89 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p1eoc565ethe5STL4:-O9p1eoc565ethe5STL5:b9jfitb) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L89)):*
> ```Smalltalk
>                 .ToArray();
> 
>             if (sourceCorpora.Length == 0)
> ```

This check can be moved up higher.


<!-- Sent from Reviewable.io -->

2024-11-08 21:59 UTC, Enkidu93 commented
I'll go ahead and rebase this once the machine side is through, but I've made the updates here so you can see how the NParallelTextCorpus will be used.

2024-11-11 14:45 UTC, Enkidu93 commented
Also fixes https://github.com/sillsdev/serval/issues/536

2024-11-11 14:46 UTC, Enkidu93 commented
Fixes https://github.com/sillsdev/serval/issues/533 as well

2024-11-26 01:31 UTC, Enkidu93 commented
This also follows up on https://github.com/sillsdev/machine/pull/263

2024-11-26 01:31 UTC, Enkidu93 commented
I believe that this is ready for review, @ddaspit & @johnml1135

2024-11-26 13:39 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 43 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p-kz3BU4fvI97WzNE:-OCcgcIUBF6RiISTyQ8Y:b71z33i) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L43)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The filtering logic for source and target are the same. This should be pulled out into a separate function.
</blockquote></details>

I agree - the readability would be improved.


<!-- Sent from Reviewable.io -->

2024-11-26 13:56 UTC, Enkidu93 commented
> I believe that this is ready for review, @ddaspit & @johnml1135

Oh, I'm sorry, @ddaspit. I don't know how I missed your earlier comments. I'll get right on those.

2024-11-26 15:57 UTC, johnml1135 requested changes
> Reviewed 10 of 22 files at r8, 3 of 10 files at r10, 2 of 6 files at r11, 2 of 5 files at r12, 1 of 1 files at r13, 1 of 2 files at r14, 6 of 6 files at r15, 1 of 1 files at r16, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-11-26 15:58 UTC, johnml1135 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: all files reviewed, 5 unresolved discussions (waiting on @ddaspit and @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-11-26 16:19 UTC, Enkidu93 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: 38 of 39 files reviewed, 5 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/EngineService.cs` line 687 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9PxU7K7qsucbEcsCVP:-OCcvFlp8G-_Gk_1Nkue:b-r5xq3n) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/Serval/src/Serval.Translation/Services/EngineService.cs#L687)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

What is the significance of the logic change?
</blockquote></details>

It's been a while, so I might not be answering your question correctly: If a deprecated corpus has no source files or target files, that ought to map to a parallel corpus that has no source corpora or target corpora respectively.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 43 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p-kz3BU4fvI97WzNE:-OCdDaM27iJnQyZF350-:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L43)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I agree - the readability would be improved.
</blockquote></details>

Done.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 46 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p0BdL5QjiHaX54xgr:-OCcy0N5087QiSGp7-eb:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L46)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is no need to perform this `Where` operation if `TrainOnChapters` is `null`. Also, we should call `FilterTexts` on the books specified in `TrainOnChapters`, so we don't unnecessarily parse books.
</blockquote></details>

Done.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 56 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p00W-AXHHU3N3mRqZ:-OCdD_mMDOZWgwBL1gnm:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L56)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would go ahead and pull this out to a separate function as well to improve readability.
</blockquote></details>

Done.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 63 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p0kbg3wiFqn9U0BQj:-OCdDb5b0cZrb2NevDL1:b-qc0pck) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L63)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We exclude verses from the training corpus when `PretranslateTextIds` or `PretranslateChapters` is specified. We should also exclude verses from the training corpus when neither is specified.
</blockquote></details>

At the moment, we're doing it the other way around: excluding training content from pretranslation, not pretranslation from training content. Regardless, is this the behavior we want? At the moment,  I think the issue you are describing is 'covered' in the `PreprocessBuildJob`: 

```
if (row.SourceSegment.Length > 0 && row.TargetSegment.Length == 0)
{
    pretranslateWriter.WriteStartObject();
    ...
    pretranslateCount++;
}
```
If `trainOn` is null but so is `pretranslate` or if `pretranslateTextIds` has a value, what should our behavior be? Do we only want to exclude things at the textId/book level or in these circumstances, wouldn't it  be better to look at the row-level? Otherwise, how could you get the train-on-all-parallel-data-pretranslate-all-non-parallel data functionality (which seems like the most straightforward use)?
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 89 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p1eoc565ethe5STL4:-OCcuKwY0kxrP2WsISbW:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L89)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This check can be moved up higher.
</blockquote></details>

Done.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 3 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9QA1B-0vIQ_v4MBoNC:-OCcv6K36OWUXmMuq4gQ:b-vet34x) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L3)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This should be implemented as a service that we inject using DI. You should create an extension method that adds the required services to the DI in an `IServiceCollectionExtensions` class.
</blockquote></details>

This is something you fixed while I was gone, right?
___
*[`src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj` line  at r7](https://reviewable.io/reviews/sillsdev/serval/512#-O9WPSJB2ygUC1vS0r5z:-OCctjc674kS-1TEBYwT:b-vet34x) ([raw file](https://github.com/sillsdev/serval/blob/6ceee183f3d000abee4ae7f01fe64665b920dc0f/src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj#L)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The directory name should match the assembly name.
</blockquote></details>

This is something you fixed while I was gone, right?


<!-- Sent from Reviewable.io -->

2024-11-26 16:31 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 119 at r18](https://reviewable.io/reviews/sillsdev/serval/512#-OCdHt337qEtMd5OTJc7:-OCdHt347FRJWUfjonK8:b87q3s6) ([raw file](https://github.com/sillsdev/serval/blob/5c6950af3e42cbacb34df50f32847c72cc3543fd/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L119)):*
> ```Smalltalk
>         if (corpus.PretranslateTextIds is not null)
>         {
>             return textCorpus.FilterTexts(corpus.PretranslateTextIds.Except(corpus.TrainOnTextIds ?? new()));
> ```

Sorry for beating the dead horse - but I thought that we arrived at this logic for pretranslating: https://github.com/sillsdev/serval/issues/533#issuecomment-2460856764 - On a per ParallelCorpus basis, if there is target training data that passes the filter, those verses will not be pretranslated.  Therefore, the following would hold:
* The training filters are not used at all when filtering for pretranslation
* The filtered training target is aligned with the filtered source pretranslations and if the length of the target is > 0, don't pretranslate (which is already implemented in the action passed from PreprocessBuildJob).


<!-- Sent from Reviewable.io -->

2024-11-26 17:04 UTC, Enkidu93 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 119 at r18](https://reviewable.io/reviews/sillsdev/serval/512#-OCdHt337qEtMd5OTJc7:-OCdQ8z6DtxCB2WUqTHy:b7x4vky) ([raw file](https://github.com/sillsdev/serval/blob/5c6950af3e42cbacb34df50f32847c72cc3543fd/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L119)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Sorry for beating the dead horse - but I thought that we arrived at this logic for pretranslating: https://github.com/sillsdev/serval/issues/533#issuecomment-2460856764 - On a per ParallelCorpus basis, if there is target training data that passes the filter, those verses will not be pretranslated.  Therefore, the following would hold:
* The training filters are not used at all when filtering for pretranslation
* The filtered training target is aligned with the filtered source pretranslations and if the length of the target is > 0, don't pretranslate (which is already implemented in the action passed from PreprocessBuildJob).
</blockquote></details>

You're totally right, John. There's an inconsistency here. I think I misunderstood the #533 comment and missed the 'if there is data' part, so I was thinking that we were only using the filters to include/exclude, but I kept the old behavior with train on all. If that is what we want, then the changes I just made should make it function like that. This also addresses my comment elsewhere to @ddaspit  regarding filtering behavior. This is more consistent.


<!-- Sent from Reviewable.io -->

2024-11-26 17:39 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r11, 4 of 5 files at r12, 2 of 2 files at r14, 5 of 6 files at r15, 1 of 1 files at r16, 4 of 4 files at r17, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512#-:-OCdYDoREJ4GeFj6itsK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135)

___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 63 at r10](https://reviewable.io/reviews/sillsdev/serval/512#-O9p0kbg3wiFqn9U0BQj:-OCdX_9EE-uzvEy8pueR:b2xsxts) ([raw file](https://github.com/sillsdev/serval/blob/891f0671c2185559433b38b7219bfac6256c9747/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L63)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

At the moment, we're doing it the other way around: excluding training content from pretranslation, not pretranslation from training content. Regardless, is this the behavior we want? At the moment,  I think the issue you are describing is 'covered' in the `PreprocessBuildJob`: 

```
if (row.SourceSegment.Length > 0 && row.TargetSegment.Length == 0)
{
    pretranslateWriter.WriteStartObject();
    ...
    pretranslateCount++;
}
```
If `trainOn` is null but so is `pretranslate` or if `pretranslateTextIds` has a value, what should our behavior be? Do we only want to exclude things at the textId/book level or in these circumstances, wouldn't it  be better to look at the row-level? Otherwise, how could you get the train-on-all-parallel-data-pretranslate-all-non-parallel data functionality (which seems like the most straightforward use)?
</blockquote></details>

The code in `PreprocessBuildJob` should cover it. Yes, we need to check on a row-level if `trainOn` and `pretranslate` are not specified.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs` line 3 at r6](https://reviewable.io/reviews/sillsdev/serval/512#-O9QA1B-0vIQ_v4MBoNC:-OCdViE52zAHRski12HY:b-xxywvh) ([raw file](https://github.com/sillsdev/serval/blob/d3300c75aec8cb8df538c1f8a9c398c31c12c05b/src/ServiceToolkit/src/SIL.ServiceToolkit/Utils/ParallelCorpusPreprocessor.cs#L3)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This is something you fixed while I was gone, right?
</blockquote></details>

Yes, you're correct.
___
*[`src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj` line  at r7](https://reviewable.io/reviews/sillsdev/serval/512#-O9WPSJB2ygUC1vS0r5z:-OCdWq_H7o64kTJv3gYL:b-27pj1y) ([raw file](https://github.com/sillsdev/serval/blob/6ceee183f3d000abee4ae7f01fe64665b920dc0f/src/ServiceToolkit/test/SIL.ServiceToolkit/SIL.ServiceToolkit.Tests.csproj#L)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

This is something you fixed while I was gone, right?
</blockquote></details>

Yes, I fixed it.


<!-- Sent from Reviewable.io -->

2024-11-26 17:54 UTC, johnml1135 reviewed
> Reviewed 1 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/512)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Enkidu93)



<!-- Sent from Reviewable.io -->

2024-11-26 17:58 UTC, merged