Build summary gprc
sillsdev/serval pull request #541
Opened 2024-11-18 07:34 UTC by mudiagaobrikisil

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/serval/541)

2024-11-19 13:53 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PostprocessBuildJob.cs` line 36 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gfQuB-D61DSqknER:-OC3gfQuB-D61DSqknES:bogjwru) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Services/PostprocessBuildJob.cs#L36)):*
> ```Smalltalk
>         }
> 
>         // here's where to add more data to send
> ```

This comment needs to be removed (or addressed).


<!-- Sent from Reviewable.io -->

2024-11-19 13:56 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hQeXAjFU1BMQulIY:-OC3hQeXAjFU1BMQulIZ:b-rknb51) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/Build.cs#L21)):*
> ```Smalltalk
>     public string? DeploymentVersion { get; init; }
>     public Dictionary<string, string> Statistics { get; init; } =
>         new Dictionary<string, string>() { { "trainCount", "0" } };
> ```

I would initialize the statistics to an empty array.


<!-- Sent from Reviewable.io -->

2024-11-19 13:58 UTC, johnml1135 commented
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-OC3hniy5IG_K6LEQgnW:b-cb2k9n) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
> ```Smalltalk
>         TranslationBuild build = await _helperClient.TranslationEnginesClient.GetCurrentBuildAsync(engineId);
>         Assert.That(build.Statistics, Is.Not.Null);
>         Assert.That(build.Statistics, Contains.Key("trainCount"));
> ```

I think that a unit test it likely not needed.


<!-- Sent from Reviewable.io -->

2024-11-19 13:59 UTC, johnml1135 commented
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-OC3hxYP6U2Fimlxy6Dz:b33xjnv) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I think that a unit test it likely not needed.
</blockquote></details>

But an E2E test is needed - add to an existing E2E test such as NmtBatch and verify that the build statistics is properly created.


<!-- Sent from Reviewable.io -->

2024-11-19 13:59 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Client/Client.g.cs` line 4552 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iAVU1mH1NdN_A05Z:-OC3iAVU1mH1NdN_A05_:bh8k0qy) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Client/Client.g.cs#L4552)):*
> ```Smalltalk
>         /// <returns>The build summary</returns>
>         /// <exception cref="ServalApiException">A server side error occurred.</exception>
>         System.Threading.Tasks.Task<TranslationBuildSummary> GetBuildSummaryAsync(string id, string buildId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
> ```

See comment in controller.


<!-- Sent from Reviewable.io -->

2024-11-19 14:00 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Models/TranslationBuildSummary.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iM1w39FgdH5IX1eD:-OC3iM1w39FgdH5IX1eE:bpyarp8) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/TranslationBuildSummary.cs#L7)):*
> ```Smalltalk
>     public int LinesTrainedOn { get; set; }
>     public int LinesPretranslated { get; set; }
>     public TimeSpan TotalBuildTime { get; set; }
> ```

This data structure is not needed.


<!-- Sent from Reviewable.io -->

2024-11-19 14:03 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iQYw4RMaEY2wh0Jm:-OC3iQYx-X-gGRb4nFAI:bjjdx7f) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/Build.cs#L16)):*
> ```Smalltalk
>     public int? QueueDepth { get; init; }
>     public JobState State { get; init; } = JobState.Pending;
>     public DateTime DateStarted { get; init; } = DateTime.UtcNow;
> ```

This can be fine - it allows the users to calculated the total time between creation and date finished.  Still, I would name this "Date created".


<!-- Sent from Reviewable.io -->

2024-11-19 14:04 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1198 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3h3Yx3Tv6tvuSYL5r:-OC3h3Yy3nIDsFaOoEA4:b57nmtu) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1198)):*
> ```Smalltalk
>     }
> 
>     /// <summary>
> ```

This is actually not needed.  The build summary should be present when just normally getting the build.

To do this, you will need to update BuildDto and the map function that maps the fields in the internal "Build" data structure to the BuildDto "data transfer object".


<!-- Sent from Reviewable.io -->

2024-11-19 14:04 UTC, johnml1135 reviewed
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 9 unresolved discussions (waiting on @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-11-26 05:36 UTC, mudiagaobrikisil commented
Hi John,

Will update the PR for this today and have a call with you when you are
available. Thanks.

On Mon, 25 Nov 2024, 10:45 pm John Lambert, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> The comments still need to be resolved.
>
> *Reviewable
> <https://reviewable.io/reviews/sillsdev/serval/541#-:-OC_H6dE7kEQq8mN5l6n:bhzceys>*
> status: all files reviewed, 9 unresolved discussions (waiting on
> @mudiagaobrikisil <https://github.com/mudiagaobrikisil>)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sillsdev/serval/pull/541#pullrequestreview-2459697462>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLIZ45LJF5ST6G7JW4DYWVL2COK55AVCNFSM6AAAAABR67I2LGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDINJZGY4TONBWGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-26 14:03 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: 6 of 17 files reviewed, 9 unresolved discussions (waiting on @johnml1135)

___
*[`src/Serval/src/Serval.Client/Client.g.cs` line 4552 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iAVU1mH1NdN_A05Z:-OCclJ6w5sX9Jn1HLp7a:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Client/Client.g.cs#L4552)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

See comment in controller.
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1198 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3h3Yx3Tv6tvuSYL5r:-OCckVvG2Ct4wfpCEspV:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1198)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This is actually not needed.  The build summary should be present when just normally getting the build.

To do this, you will need to update BuildDto and the map function that maps the fields in the internal "Build" data structure to the BuildDto "data transfer object".
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hQeXAjFU1BMQulIY:-OCcksovA0V0bXGbvZ8O:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/Build.cs#L21)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I would initialize the statistics to an empty array.
</blockquote></details>

Done.
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PostprocessBuildJob.cs` line 36 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gfQuB-D61DSqknER:-OCclEg9BrilP3qOXMyK:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Services/PostprocessBuildJob.cs#L36)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This comment needs to be removed (or addressed).
</blockquote></details>

Done.
___
*[`src/Serval/src/Serval.Translation/Models/TranslationBuildSummary.cs` line 7 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iM1w39FgdH5IX1eD:-OCclFzs2n7Vlzijl_K6:b-896fix) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/TranslationBuildSummary.cs#L7)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This data structure is not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 16:11 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 279 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCdE5873Y7EInC-Jfaa:-OCdE5873Y7EInC-Jfab:bktmc7h) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L279)):*
> ```Smalltalk
>         }
> 
>         var newStatistics = new Dictionary<string, string>();
> ```

Why was this change made?  I am concerned that it will not accurately update parameters, but rather drop existing ones.  Some thing you can do is make a unit test for this to ensure that the following happens:
Starting data:
* A: Init
* B: Init
Updated data:
* B: Update
* C: Update
Final data:
* A: Init
* B: Update
* C: Update


<!-- Sent from Reviewable.io -->

2024-11-26 16:13 UTC, johnml1135 commented
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-OCdEgc5Ezn5wgNMw5cg:b5sznzf) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

But an E2E test is needed - add to an existing E2E test such as NmtBatch and verify that the build statistics is properly created.
</blockquote></details>

Correction: this is an E2E test (I read it wrong).  All statistics fields and values should be confirmed (both the train and pretranslate count).


<!-- Sent from Reviewable.io -->

2024-11-26 16:15 UTC, johnml1135 reviewed
> Reviewed 10 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-11-26 20:31 UTC, ddaspit requested changes
> Reviewed 6 of 15 files at r1, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 6 unresolved discussions (waiting on @johnml1135 and @mudiagaobrikisil)

___
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-OCdxPuPCXtxE_R6ehB-:bbhy7z2) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

runData?
</blockquote></details>

Maybe `ExecutionData`?
___
*[`src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs` line 34 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCdy78_13c5IHKC5hiG:-OCdy78_13c5IHKC5hiH:b24v3t1) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs#L34)):*
> ```Smalltalk
>         string engineId,
>         string buildId,
>         IDictionary<string, string> statistics,
> ```

I would make this a `IReadOnlyDictionary`.
___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 20 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-FvyA0ht6S3LJlHe:-OCe-FvyA0ht6S3LJlHf:bc33t8p) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Models/Build.cs#L20)):*
> ```Smalltalk
>     public IReadOnlyDictionary<string, object>? Options { get; init; }
>     public string? DeploymentVersion { get; init; }
>     public Dictionary<string, string>[] Statistics { get; init; } = [];
> ```

I'm not sure I understand why this is an array of dictionaries. This should be a single dictionary that gets updated with the most recent values.
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-OCe-cBD6f27IUtgzrcp:b-964heb) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
> ```Smalltalk
>         var updatedStatistics = build.Statistics.Concat(new[] { newStatistics }).ToArray();
> 
>         await _builds.UpdateAsync(
> ```

The update needs to be atomic or we will face race conditions. We should merge `newStatistics` into the existing statistics of the model. We will need to add a new "merge" operator to the `IUpdateBuilder` interface to support this.


<!-- Sent from Reviewable.io -->

2024-11-27 12:59 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 6 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 20 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-FvyA0ht6S3LJlHe:-OChgJnWBeHap__tDvjU:b-b7egts) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Models/Build.cs#L20)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure I understand why this is an array of dictionaries. This should be a single dictionary that gets updated with the most recent values.
</blockquote></details>

Just to be sure. Will it keep track of the previous statistics?
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-OChgbJtAiZA-HSHqUZN:b-83od3n) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The update needs to be atomic or we will face race conditions. We should merge `newStatistics` into the existing statistics of the model. We will need to add a new "merge" operator to the `IUpdateBuilder` interface to support this.
</blockquote></details>

Noted


<!-- Sent from Reviewable.io -->

2024-11-27 14:27 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-OCi0A9fE0cyRG8PODyL:b8eau52) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Maybe `ExecutionData`?
</blockquote></details>

I like it.


<!-- Sent from Reviewable.io -->

2024-11-27 14:50 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-OCi5WGA1C5Hb8fTnSGR:b-42zitl) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I like it.
</blockquote></details>

Please change all instances of "Statistics" to "ExecutionData".


<!-- Sent from Reviewable.io -->

2024-11-28 23:04 UTC, mudiagaobrikisil reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541#-:-OCp03gCCEsCoi7ymvPF:bb6un1j)* status: all files reviewed, 6 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-OCp-VnL4Lf0utwiimC7:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Please change all instances of "Statistics" to "ExecutionData".
</blockquote></details>

Done
___
*[`src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs` line 34 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCdy78_13c5IHKC5hiG:-OCp-YSc6uRW3R7zRomi:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Machine/src/Serval.Machine.Shared/Services/IPlatformService.cs#L34)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I would make this a `IReadOnlyDictionary`.
</blockquote></details>

Done
___
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 1241 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hBHGDp6BOBE8ATgb:-OCp-_McDzVnlSLixrSA:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L1241)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

All commented out code should be removed.
</blockquote></details>

Done
___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 16 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3iQYw4RMaEY2wh0Jm:-OCp0AZl4JpkOHvFDm-v:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/src/Serval.Translation/Models/Build.cs#L16)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This can be fine - it allows the users to calculated the total time between creation and date finished.  Still, I would name this "Date created".
</blockquote></details>

Done
___
*[`src/Serval/src/Serval.Translation/Models/Build.cs` line 20 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-FvyA0ht6S3LJlHe:-OCp-bwDDi1AMycSXVlx:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Models/Build.cs#L20)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

Just to be sure. Will it keep track of the previous statistics?
</blockquote></details>

Done
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 279 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCdE5873Y7EInC-Jfaa:-OCp-dXuBqX2944pYb4-:b-zk9uy) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L279)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Why was this change made?  I am concerned that it will not accurately update parameters, but rather drop existing ones.  Some thing you can do is make a unit test for this to ensure that the following happens:
Starting data:
* A: Init
* B: Init
Updated data:
* B: Update
* C: Update
Final data:
* A: Init
* B: Update
* C: Update
</blockquote></details>

E2E test done but need a little help with knowing how to track the init and final values in the unit tests, since the ExecutionData is initialized to an empty dictionary
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-OCp00PrD77FZnLbU7Ye:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Correction: this is an E2E test (I read it wrong).  All statistics fields and values should be confirmed (both the train and pretranslate count).
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-02 14:47 UTC, Enkidu93 requested changes
> Reviewed 4 of 11 files at r3, 13 of 13 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 7 unresolved discussions (waiting on @ddaspit, @johnml1135, and @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto` line 67 at r4](https://reviewable.io/reviews/sillsdev/serval/541#-OD6pGso67EW1XZSSzaW:-OD6pGso67EW1XZSSzaX:bt3hwru) ([raw file](https://github.com/sillsdev/serval/blob/2d797915c9a335a33c190dee8c37f4fb470e1c12/src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto#L67)):*
> ```proto
>     string engine_id = 1;
>     string build_id = 2;
>     map<string, string> ExecutionData = 3;
> ```

Why pascal case here? 


<!-- Sent from Reviewable.io -->

2024-12-02 19:41 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: 13 of 17 files reviewed, 7 unresolved discussions (waiting on @ddaspit, @Enkidu93, and @johnml1135)

___
*[`src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto` line 67 at r4](https://reviewable.io/reviews/sillsdev/serval/541#-OD6pGso67EW1XZSSzaW:-OD7svho5mIJNRC_R7gr:b-fl5ivp) ([raw file](https://github.com/sillsdev/serval/blob/2d797915c9a335a33c190dee8c37f4fb470e1c12/src/Serval/src/Serval.Grpc/Protos/serval/translation/v1/platform.proto#L67)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why pascal case here?
</blockquote></details>

Sorry. Was an oversight. Done


<!-- Sent from Reviewable.io -->

2024-12-03 01:43 UTC, johnml1135 commented
*[`-- commits` line 107 at r5](https://reviewable.io/reviews/sillsdev/serval/541#-OD9AjWu-qdrc8rzGQy-:-OD9AjWv4jYLKhpyedRY:bgfifmh):*
Please rebase these into a single commit on the latest main branch commit.  I can show you how to do that.


<!-- Sent from Reviewable.io -->

2024-12-03 01:44 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 192 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OD9B7O_B7u7Nboks6fx:-OD9B7O_B7u7Nboks6fy:b3w2o91) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L192)):*
> ```Smalltalk
> 
>             int skipCount = 0;
>             foreach (Row?[] rows in AlignTrainCorpus(sourceTrainingCorpora, targetTrainingCorpora))
> ```

These changes are from merging in from main.   After you rebase, these changes should disappear.


<!-- Sent from Reviewable.io -->

2024-12-03 01:47 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-OD9Bc2O0wXf46yUSg6l:bk58936) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

Noted
</blockquote></details>

I told Mudi to get the plain implementation in now and I (or he) could work on updating the DataAccess layer after the other changes are in.


<!-- Sent from Reviewable.io -->

2024-12-03 01:48 UTC, johnml1135 commented
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-OD9Bzo8AsoxVRqMkcVE:b-4liscz) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

Done
</blockquote></details>

Please verify the counts in the execution data as well.


<!-- Sent from Reviewable.io -->

2024-12-03 01:48 UTC, johnml1135 commented
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-OD9C6rjDKoVbIpBeqWp:b-pzzz9l) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

Done
</blockquote></details>

Where did the execution data go?


<!-- Sent from Reviewable.io -->

2024-12-03 01:49 UTC, johnml1135 reviewed
> Reviewed 9 of 13 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 8 unresolved discussions (waiting on @ddaspit and @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-12-03 06:22 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 8 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`-- commits` line 107 at r5](https://reviewable.io/reviews/sillsdev/serval/541#-OD9AjWu-qdrc8rzGQy-:-ODAAOO08xY9F_npyiWB:bsbjct5):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Please rebase these into a single commit on the latest main branch commit.  I can show you how to do that.
</blockquote></details>

Okay. Will do that
___
*[`src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs` line 192 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OD9B7O_B7u7Nboks6fx:-ODAAge70SabB9Me391e:b-83od3n) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Machine/src/Serval.Machine.Shared/Services/PreprocessBuildJob.cs#L192)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

These changes are from merging in from main.   After you rebase, these changes should disappear.
</blockquote></details>

Noted
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 279 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCdE5873Y7EInC-Jfaa:-ODAAcyV-TogpVCCDu2J:bb71kmx) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L279)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Ok - we can talk later.
</blockquote></details>

Okay
___
*[`src/Serval/test/Serval.E2ETests/ServalApiTests.cs` line 142 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3hniy5IG_K6LEQgnV:-ODAALKb7UDrLsGpoDyX:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Serval/test/Serval.E2ETests/ServalApiTests.cs#L142)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Please verify the counts in the execution data as well.
</blockquote></details>

Done
___
*[`src/Machine/src/Serval.Machine.Shared/Models/Build.cs` line 32 at r1](https://reviewable.io/reviews/sillsdev/serval/541#-OC3gKo0E6qCsw1tnnl9:-ODA5w152CoLwRpfVLDC:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/2b9184205e2433bc03a7e661e12a829db85b34c6/src/Machine/src/Serval.Machine.Shared/Models/Build.cs#L32)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Where did the execution data go?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-05 14:40 UTC, johnml1135 commented
*[`samples/ApiExample/ApiExample.csproj` line 24 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMFqEE8oeocBHEhp4S:-ODMFqEE8oeocBHEhp4T:b5sr0vw) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/samples/ApiExample/ApiExample.csproj#L24)):*
> ```XML
>     <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
>     <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.1" />
>     <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
> ```

I am assuming that the line endings changed, or similar.  We should (somehow) remove these "changes" from the history.


<!-- Sent from Reviewable.io -->

2024-12-05 14:41 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs` line 5 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMGEka3_bptNPHSLE3:-ODMGEkb5Pg-WSRVNyjt:bkxg7pa) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/src/Serval/src/Serval.Translation/Controllers/TranslationEnginesController.cs#L5)):*
> ```Smalltalk
> #pragma warning disable CS0612 // Type or member is obsolete
> 
> #pragma warning disable CS0612 // Type or member is obsolete
> ```

Duplicated pragma


<!-- Sent from Reviewable.io -->

2024-12-05 14:42 UTC, johnml1135 commented
*[`src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs` line 274 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMGMUH2eyH2PXWydB2:-ODMGMUH2eyH2PXWydB3:b-og65yo) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/src/Serval/test/Serval.ApiServer.IntegrationTests/TranslationEngineTests.cs#L274)):*
> ```Smalltalk
>         await _env.Builds.InsertAsync(build);
>         // Call client.UpdateBuildExecutionData with the new data
>         // Assert.That(build, Is.Not.Null);
> ```

This test needs to be finished.


<!-- Sent from Reviewable.io -->

2024-12-05 14:44 UTC, johnml1135 requested changes
> Reviewed 14 of 14 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 9 unresolved discussions (waiting on @ddaspit and @mudiagaobrikisil)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 79 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMG8CnEQWR58ZNXILd:-ODMG8CnEQWR58ZNXILe:bf8xiic) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L79)):*
> ```Smalltalk
>         await env.RunBuildJobAsync(corpus1);
> 
>         Assert.That(await env.GetPretranslateCountAsync(), Is.EqualTo(2));
> ```

Why is the pretranslate count changing?


<!-- Sent from Reviewable.io -->

2024-12-05 15:11 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: 20 of 25 files reviewed, 9 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 79 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMG8CnEQWR58ZNXILd:-ODMMzXk41fqym2bZIWC:b3r7ucf) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L79)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

I can't tell. I think you added that test some time ago with the comment "so we don't pretranslate everything". Not really certain what the test does
</blockquote></details>

Changed it back to 4. I guess it got changed somehow doing the rebase


<!-- Sent from Reviewable.io -->

2024-12-05 22:12 UTC, johnml1135 commented
*[`samples/ApiExample/ApiExample.csproj` line 24 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMFqEE8oeocBHEhp4S:-ODNrkGaDiBMMdYMOelM:bmmtohd) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/samples/ApiExample/ApiExample.csproj#L24)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I am assuming that the line endings changed, or similar.  We should (somehow) remove these "changes" from the history.
</blockquote></details>

This still should be addressed.  It is saying "the file changed" when it has not.  Have the file endings changed?

Line endings?  File metadata?
https://stackoverflow.com/questions/69349158/git-lists-files-as-changed-but-there-are-no-changes

Permissions?
https://stackoverflow.com/questions/14564946/git-status-shows-changed-files-but-git-diff-doesnt


<!-- Sent from Reviewable.io -->

2024-12-05 22:12 UTC, johnml1135 reviewed
> Reviewed 1 of 3 files at r7, 2 of 3 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-12-06 13:23 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 4 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`samples/ApiExample/ApiExample.csproj` line 24 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMFqEE8oeocBHEhp4S:-ODR7kc20Ik4VCHxE3IZ:b-dqirf0) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/samples/ApiExample/ApiExample.csproj#L24)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

This still should be addressed.  It is saying "the file changed" when it has not.  Have the file endings changed?

Line endings?  File metadata?
https://stackoverflow.com/questions/69349158/git-lists-files-as-changed-but-there-are-no-changes

Permissions?
https://stackoverflow.com/questions/14564946/git-status-shows-changed-files-but-git-diff-doesnt
</blockquote></details>

On the rebased and squashed commits, it no longer shows that those files changed
___
*[`src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs` line 144 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMGoaiEnii7SUWxvp7:-ODR6GoiBwr6mFVBJ8eJ:b-s5n9b6) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs#L144)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

How were these values updated?  Does this test pass?
</blockquote></details>

The test has passed.


<!-- Sent from Reviewable.io -->

2024-12-06 14:56 UTC, ddaspit reviewed
> Reviewed 5 of 13 files at r4, 2 of 4 files at r5, 9 of 14 files at r6, 1 of 3 files at r7, 2 of 3 files at r8, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 3 unresolved discussions (waiting on @johnml1135 and @mudiagaobrikisil)

___
*[`samples/ApiExample/ApiExample.csproj` line 24 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMFqEE8oeocBHEhp4S:-ODRNVz61qrKZwUd8VGx:b-r1zxsv) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/samples/ApiExample/ApiExample.csproj#L24)):*
<details><summary><i>Previously, mudiagaobrikisil wrote…</i></summary><blockquote>

On the rebased and squashed commits, it no longer shows that those files changed
</blockquote></details>

It looks like the BOM is getting stripped out of all of the csproj files. I believe that Visual Studio adds them by default for csproj files. We don't really need them. We could strip them from all csproj files to make it consistent.
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-ODRSLK24xsvjX-S6rv4:btx397c) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

I told Mudi to get the plain implementation in now and I (or he) could work on updating the DataAccess layer after the other changes are in.
</blockquote></details>

I thought about this a bit more and realized that we don't need a new operator to do this. This update call should do what we want:

``` cs
await _builds.UpdateAsync(
    b => b.Id == request.BuildId,
    u =>
    {
        foreach (KeyValuePair<string, string> entry in request.ExecutionData)
            u.Set(b => b.ExecutionData[entry.Key], entry.Value);
    },
    cancellationToken: context.CancellationToken
);
```
___
*[`src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs` line 126 at r10](https://reviewable.io/reviews/sillsdev/serval/541#-ODRQW8TA8Cafxws4it0:-ODRQW8TA8Cafxws4it1:b-8eett) ([raw file](https://github.com/sillsdev/serval/blob/fd86e95d35925af2603c62dc6d9d30c90a638e5a/src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs#L126)):*
> ```Smalltalk
>         Assert.That(build.ExecutionData, Is.Not.Null);
> 
>         var executionData = build.ExecutionData!;
> ```

The null-forgiving operator shouldn't be necessary, since you check that it is not null with the assert.


<!-- Sent from Reviewable.io -->

2024-12-09 15:09 UTC, johnml1135 commented
*[`samples/ApiExample/ApiExample.csproj` line 24 at r6](https://reviewable.io/reviews/sillsdev/serval/541#-ODMFqEE8oeocBHEhp4S:-ODfxkq53CnatQp8nuUc:brj6qux) ([raw file](https://github.com/sillsdev/serval/blob/295c847d2febfb08f29e7a353743f250e46bd3aa/samples/ApiExample/ApiExample.csproj#L24)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like the BOM is getting stripped out of all of the csproj files. I believe that Visual Studio adds them by default for csproj files. We don't really need them. We could strip them from all csproj files to make it consistent.
</blockquote></details>

As long as we know what changed - stripping the BOM out is fine by me.


<!-- Sent from Reviewable.io -->

2024-12-09 15:11 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-ODfyHnn7JTMgOGGJ1kU:b-phao6k) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I thought about this a bit more and realized that we don't need a new operator to do this. This update call should do what we want:

``` cs
await _builds.UpdateAsync(
    b => b.Id == request.BuildId,
    u =>
    {
        foreach (KeyValuePair<string, string> entry in request.ExecutionData)
            u.Set(b => b.ExecutionData[entry.Key], entry.Value);
    },
    cancellationToken: context.CancellationToken
);
```
</blockquote></details>

If it works, that looks like a fine solution to me.


<!-- Sent from Reviewable.io -->

2024-12-09 15:39 UTC, johnml1135 commented
This pull request addresses https://github.com/sillsdev/serval/issues/558.

2024-12-11 10:00 UTC, mudiagaobrikisil reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 287 at r3](https://reviewable.io/reviews/sillsdev/serval/541#-OCe-cBD6f27IUtgzrco:-ODp6Qri-yyHSnSzwk2B:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/40084eb689f97741c1d0ed3865c33c343ad6685c/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L287)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

If it works, that looks like a fine solution to me.
</blockquote></details>

Done
___
*[`src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs` line 126 at r10](https://reviewable.io/reviews/sillsdev/serval/541#-ODRQW8TA8Cafxws4it0:-ODp6M8R6sMnHRSYGh9v:bb6un1j) ([raw file](https://github.com/sillsdev/serval/blob/fd86e95d35925af2603c62dc6d9d30c90a638e5a/src/Serval/test/Serval.Translation.Tests/Services/PlatformServiceTests.cs#L126)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The null-forgiving operator shouldn't be necessary, since you check that it is not null with the assert.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-12-11 14:29 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541#-:-ODq6sA87H0IBOwBYnYW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @johnml1135 and @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-12-11 14:30 UTC, johnml1135 reviewed
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 1 unresolved discussion (waiting on @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2024-12-11 14:46 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODqAoV57q_agY0fSkBt:b-oowni5) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
> ```Smalltalk
>                 await c.UpdateManyAsync(
>                     Builders<Build>.Filter.Exists(b => b.ExecutionData, false),
>                     Builders<Build>.Update.Set(b => b.ExecutionData, new Dictionary<string, string>())
> ```

@ddaspit - what do you think of this - updating the database.


<!-- Sent from Reviewable.io -->

2024-12-11 14:56 UTC, johnml1135 commented
There is still a failing test - ###  [Serval.Translation.Services.PlatformServiceTests](https://github.com/sillsdev/serval/runs/34261739687#r6s4).  This needs to be addressed.





<!-- Sent from Reviewable.io -->

2024-12-11 15:33 UTC, mudiagaobrikisil reviewed
I have addressed it. I will make a push later on

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541#-:-ODqLY9D4dU2XWbtqMkO:b-9rcedj)* status: 20 of 26 files reviewed, 2 unresolved discussions (waiting on @ddaspit, @Enkidu93, and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-12-11 16:05 UTC, ddaspit requested changes
> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135 and @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODqS3GHAvThVwSjOYfL:b-hu3nvy) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - what do you think of this - updating the database.
</blockquote></details>

`ExecutionData` should be marked as an optional property or we need a migration like this. If we are going to continue to add migrations, then we should implement more full-fledged migration support with model versions, etc.


<!-- Sent from Reviewable.io -->

2024-12-11 16:48 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODqbheT4tubnrrGDeZz:b-a2n2xx) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

`ExecutionData` should be marked as an optional property or we need a migration like this. If we are going to continue to add migrations, then we should implement more full-fledged migration support with model versions, etc.
</blockquote></details>

Do we want to do another "one off" for this?  I believe it will crash if this is not done.


<!-- Sent from Reviewable.io -->

2024-12-11 16:53 UTC, johnml1135 reviewed
> Reviewed 6 of 6 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-12-12 13:16 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODv-t3QB0ws-DYf9JIt:b-szhq2q) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

Do we want to do another "one off" for this?  I believe it will crash if this is not done.
</blockquote></details>

@ddaspit - does this edit meet your expectations?


<!-- Sent from Reviewable.io -->

2024-12-12 14:26 UTC, ddaspit reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135 and @mudiagaobrikisil)

___
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODvFcHK5i8PiR8hf50q:b-c006f0) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
<details><summary><i>Previously, johnml1135 (John Lambert) wrote…</i></summary><blockquote>

@ddaspit - does this edit meet your expectations?
</blockquote></details>

I'm not sure we need this. We should be able to mark `ExecutionData` as optional and get it to work.
___
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 288 at r13](https://reviewable.io/reviews/sillsdev/serval/541#-ODvFOesDSpacGtDyxeV:-ODvFOesDSpacGtDyxeW:b-emuijm) ([raw file](https://github.com/sillsdev/serval/blob/ff00cb55b9edc5e7c8498ba9295452e574396da4/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L288)):*
> ```Smalltalk
>         await _builds.UpdateAsync(
>             b => b.Id == request.BuildId,
>             u => u.Set(b => b.ExecutionData, updatedExecutionData),
> ```

Why was this changed back?


<!-- Sent from Reviewable.io -->

2024-12-12 18:09 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs` line 36 at r12](https://reviewable.io/reviews/sillsdev/serval/541#-ODqAoV57q_agY0fSkBs:-ODw2XPO8P29Yh70BvpJ:b-491jmy) ([raw file](https://github.com/sillsdev/serval/blob/8c227a4de0258e5fc702000f4cd7e9be4292f78a/src/Serval/src/Serval.Translation/Configuration/IMongoDataAccessConfiguratorExtensions.cs#L36)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I'm not sure we need this. We should be able to mark `ExecutionData` as optional and get it to work.
</blockquote></details>

Do we really want it as optional?  There will always be execution data (even if it is blank).  If it is nullable, the update routine that you wrote before becomes more complicated - I didn't find a good way to initialize the field only if it was null (in a single transaction).


<!-- Sent from Reviewable.io -->

2024-12-16 12:33 UTC, johnml1135 commented
*[`src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs` line 288 at r13](https://reviewable.io/reviews/sillsdev/serval/541#-ODvFOesDSpacGtDyxeV:-OEES7gw2NBVAIWin6-B:bocbvxs) ([raw file](https://github.com/sillsdev/serval/blob/ff00cb55b9edc5e7c8498ba9295452e574396da4/src/Serval/src/Serval.Translation/Services/TranslationPlatformServiceV1.cs#L288)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Why was this changed back?
</blockquote></details>

The bug was in MemoryUpdateBuilder.  When it was resolved, the correct implementation could be put in.


<!-- Sent from Reviewable.io -->

2024-12-16 12:33 UTC, johnml1135 reviewed
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-12-20 14:45 UTC, Enkidu93 approved these changes
> Reviewed 2 of 4 files at r5, 6 of 14 files at r6, 1 of 3 files at r7, 2 of 3 files at r10, 1 of 2 files at r11, 6 of 6 files at r12, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit)



<!-- Sent from Reviewable.io -->

2024-12-20 15:22 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/541#-:-OEZdp7G5OV8nWn5A4u7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @mudiagaobrikisil)



<!-- Sent from Reviewable.io -->

2025-01-02 14:54 UTC, merged