If no other training data, don't add any keyterms
sillsdev/serval pull request #580
Opened 2024-12-12 21:48 UTC by johnml1135

Resolves #569

2024-12-13 16:58 UTC, Enkidu93 requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/580)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)

___
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 747 at r1](https://reviewable.io/reviews/sillsdev/serval/580#-OE-wOJw55563R2uhgrk:-OE-wOJw55563R2uhgrl:b-715ehr) ([raw file](https://github.com/sillsdev/serval/blob/0cfd14502a9968b6577f6ad030e34049daa8167d/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L747)):*
> ```Smalltalk
>         Assert.That(
>             pretranslations[2]!["translation"]!.ToString(),
>             Is.EqualTo("Source one, chapter twelve, verse one.")
> ```

Is there a way to 'save' this test? Or are we happy for it just to be saved in the commit history? I think ultimately we'll need a test like this once we enable some kind of filtering and, as you can see, it's a fairly long test.
___
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 89 at r1](https://reviewable.io/reviews/sillsdev/serval/580#-OE-x6Qv-swr4NbM-ZPF:-OE-x6Qv-swr4NbM-ZPG:b-i7l22j) ([raw file](https://github.com/sillsdev/serval/blob/b0c02868f51daf83f92b519a3edb2655f112a909/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L89)):*
> ```Smalltalk
>             }
> 
>             if (useKeyTerms)
> ```

Why not just `&& parallelTrainingDataPresent`?


<!-- Sent from Reviewable.io -->

2024-12-13 17:01 UTC, Enkidu93 reviewed
My only other concern is that I think the EITL team needs to 'buy in' before we do this. It's my impression that they already feel undermined in how KBT changes were done/unstable in regard to what the behavior is in Serval/SF. Even a quick email or Slack message that has an asking-not-telling tone would do it. Not sure if that's already been done. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/580#-:-OE-xKui1wQSuplbkHUl:bne6act)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ddaspit and @johnml1135)



<!-- Sent from Reviewable.io -->

2024-12-13 19:10 UTC, ddaspit reviewed
I agree. We need buy-in from the EITL team before we proceed.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/580#-:-OE0PyAr3lxOCdn6BEq8:blf2ji3)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2024-12-16 12:35 UTC, johnml1135 commented
*[`src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs` line 747 at r1](https://reviewable.io/reviews/sillsdev/serval/580#-OE-wOJw55563R2uhgrk:-OEEScDw60251cX2PvpD:bn7rrp5) ([raw file](https://github.com/sillsdev/serval/blob/0cfd14502a9968b6577f6ad030e34049daa8167d/src/Machine/test/Serval.Machine.Shared.Tests/Services/PreprocessBuildJobTests.cs#L747)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Is there a way to 'save' this test? Or are we happy for it just to be saved in the commit history? I think ultimately we'll need a test like this once we enable some kind of filtering and, as you can see, it's a fairly long test.
</blockquote></details>

We could "ignore" or otherwise pass over the test.  That would be about equivalent as to saving it in commit history, but just more visible.  I am fine either way.  Also, if we actually implement this, we will likely want to change it to "filter on the pretranslations" rather than on the training data.


<!-- Sent from Reviewable.io -->

2024-12-16 12:37 UTC, johnml1135 commented
*[`src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs` line 89 at r1](https://reviewable.io/reviews/sillsdev/serval/580#-OE-x6Qv-swr4NbM-ZPF:-OEET53E1mn4FDUyz7tu:b-kszrrb) ([raw file](https://github.com/sillsdev/serval/blob/b0c02868f51daf83f92b519a3edb2655f112a909/src/ServiceToolkit/src/SIL.ServiceToolkit/Services/ParallelCorpusPreprocessingService.cs#L89)):*
<details><summary><i>Previously, Enkidu93 (Eli C. Lowry) wrote…</i></summary><blockquote>

Why not just `&& parallelTrainingDataPresent`?
</blockquote></details>

Because we won't know until every corpus has been run through whether there is any data at all.  The simplest solution that I could think of was to collect them all and if there was data, add them when all the corpora are looped through.  Otherwise, we would have to loop through the corpora twice.


<!-- Sent from Reviewable.io -->

2024-12-16 12:42 UTC, johnml1135 commented
Request for input made.





<!-- Sent from Reviewable.io -->

2024-12-20 14:41 UTC, Enkidu93 commented
In the meeting that you had to leave, @johnml1135, I got the go-ahead from the EITL team for this PR.

2024-12-20 14:42 UTC, Enkidu93 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/serval/580#-:-OEZWKzf3X8SXMAjLWxM:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @johnml1135)



<!-- Sent from Reviewable.io -->

2025-01-02 14:55 UTC, johnml1135 commented
@ddaspit - can you finish this review?





<!-- Sent from Reviewable.io -->

2025-01-06 15:06 UTC, merged